Repository scala/scala3, pull requests merged in 2018-09, with the labels that each got.

#5029 Fix #5007 (aka scala/bug#5063)
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  tests/neg/t5063.scala
  tests/untried/neg/t5063.check
  tests/untried/neg/t5063.scala
Labels: stat:needs review

#4789 Support `-from-tasty` in Dottydoc
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/core/Comments.scala
  compiler/src/dotty/tools/dotc/core/tasty/CommentPickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/CommentUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyFormat.scala
  compiler/src/dotty/tools/dotc/fromtasty/ReadTastyTreesFromClasses.scala
  compiler/src/dotty/tools/dotc/interactive/InteractiveCompiler.scala
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
  compiler/src/dotty/tools/dotc/transform/CookComments.scala
  compiler/src/dotty/tools/dotc/typer/Docstrings.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/src/dotty/tools/io/Directory.scala
  compiler/src/dotty/tools/repl/ReplCompiler.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test/dotty/tools/dotc/core/tasty/CommentPicklingTest.scala
  compiler/test/dotty/tools/repl/DocTests.scala
  doc-tool/src/dotty/tools/dottydoc/DocCompiler.scala
  doc-tool/src/dotty/tools/dottydoc/DocFrontEnd.scala
  doc-tool/src/dotty/tools/dottydoc/core/AlternateConstructorsPhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/DocASTPhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/DocstringPhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/LinkCompanionsPhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/PackageObjectsPhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/RemoveEmptyPackagesPhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/SortMembersPhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/TypeLinkingPhases.scala
  doc-tool/src/dotty/tools/dottydoc/core/UsecasePhase.scala
  doc-tool/src/dotty/tools/dottydoc/core/transform.scala
  doc-tool/src/dotty/tools/dottydoc/model/comment/Comment.scala
  doc-tool/src/dotty/tools/dottydoc/model/entities.scala
  doc-tool/src/dotty/tools/dottydoc/model/factories.scala
  doc-tool/src/dotty/tools/dottydoc/model/internal.scala
  doc-tool/src/dotty/tools/dottydoc/model/references.scala
  doc-tool/src/dotty/tools/dottydoc/staticsite/DefaultParams.scala
  doc-tool/src/dotty/tools/dottydoc/staticsite/MarkdownLinkVisitor.scala
  doc-tool/src/dotty/tools/dottydoc/staticsite/Site.scala
  doc-tool/src/dotty/tools/dottydoc/util/MemberLookup.scala
  doc-tool/src/dotty/tools/dottydoc/util/internal/mutate.scala
  doc-tool/test/ConstructorTest.scala
  doc-tool/test/DottyDocTest.scala
  doc-tool/test/JavaConverterTest.scala
  doc-tool/test/MarkdownTests.scala
  doc-tool/test/PackageStructure.scala
  doc-tool/test/SimpleComments.scala
  doc-tool/test/TemplateErrorTests.scala
  doc-tool/test/UsecaseTest.scala
  doc-tool/test/WhitelistedStdLib.scala
  doc-tool/test/dotty/tools/dottydoc/staticsite/PageTests.scala
  doc-tool/test/dotty/tools/dottydoc/staticsite/SiteTests.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/HoverTest.scala
Labels: area:doctool, area:ide, area:pickling, area:repl

#5012 Fix #4999: allow pattern matching against by-name arguments
  compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala
  tests/pos/i4999.scala
Labels: prio:blocker, stat:needs review

#5098 Respect `-color:never` in REPL output
  compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala
  compiler/src/dotty/tools/repl/JLineTerminal.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test/dotty/tools/dotc/printing/SyntaxHighlightingTests.scala
Labels: area:repl

#4304 Let VSCode start the language server
  project/Build.scala
  vscode-dotty/package.json
  vscode-dotty/src/extension.ts
Labels: area:ide, itype:enhancement, stat:needs review

#5134 Fix output of test compilation
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
Labels: stat:needs review

#5165 Do not print stack trace for QuoteError
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
Labels: stat:needs review

#5153 Fix #5152: Use context of the target location
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/run-with-compiler/i5152.check
  tests/run-with-compiler/i5152.scala
Labels: stat:needs review

#5154 Fix #5144: Avoid Expr of method type
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/run-with-compiler/i5144.check
  tests/run-with-compiler/i5144.scala
  tests/run-with-compiler/i5144b.check
  tests/run-with-compiler/i5144b.scala
Labels: stat:needs review

#5137 New highlighter based on tokens and untyped trees
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/printing/Formatting.scala
  compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala
  compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala
  compiler/src/dotty/tools/repl/JLineTerminal.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test-resources/repl/errmsgs
  compiler/test/dotty/tools/dotc/printing/SyntaxHighlightingTests.scala
Labels: stat:needs review

#5174 Don't report Dynamic inheritance warning on Dynamic itself
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tests/pos-special/fatal-warnings/Dynamic.scala
Labels: stat:needs review
