Repository scala/scala3, pull requests merged in 2018-12, with the labels that each got.

#5534 Add regression test for `dotc -decompile xyz.tasty`
  project/scripts/cmdTests
  project/scripts/cmdTestsCommon.inc.sh
Labels: stat:needs review

#5543 Add `List[Expr[T]]` to `Expr[List[T]]` conversion in the library
  library/src-scala3/scala/quoted/package.scala
  library/src/scala/quoted/package.scala
  tests/run-separate-compilation/xml-interpolation-2/XmlQuote_1.scala
Labels: stat:needs review

#5532 Add minimal prototype for f interpolator macro
  tests/run-separate-compilation/f-interpolation-1/FQuote_1.scala
  tests/run-separate-compilation/f-interpolation-1/Test_2.scala
Labels: stat:needs review

#5520 Prepare dotty-library for bootstrap
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  library/src-bootstrapped/scala/StagedTuple.scala
  library/src-bootstrapped/scala/Tuple.scala
  library/src-bootstrapped/scala/quoted/package.scala
  library/src-bootstrapped/scala/typelevel/package.scala
  library/src-non-bootstrapped/scala/Tuple.scala
  project/Build.scala
Labels: stat:needs review

#5552 Fix race condition in worksheet output
  vscode-dotty/src/worksheet.ts
Labels: area:ide

#5576 Always use Module suffix for abstract modules in TASTy Reflect
  compiler/src/dotty/tools/dotc/tastyreflect/CaseDefOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/ConstantOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/IdOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/ImportSelectorOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/PatternOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/SignatureOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/StandardDefinitions.scala
  compiler/src/dotty/tools/dotc/tastyreflect/SymbolOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/CaseDefOps.scala
  library/src/scala/tasty/reflect/ConstantOps.scala
  library/src/scala/tasty/reflect/IdOps.scala
  library/src/scala/tasty/reflect/ImportSelectorOps.scala
  library/src/scala/tasty/reflect/PatternOps.scala
  library/src/scala/tasty/reflect/SignatureOps.scala
  library/src/scala/tasty/reflect/StandardDefinitions.scala
  library/src/scala/tasty/reflect/SymbolOps.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
Labels: stat:needs review

#5575 Allow macros calling inherited methods on modules
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  tests/run/tasty-interpolation-1.check
  tests/run/tasty-interpolation-1/Macro.scala
  tests/run/tasty-interpolation-1/Test_2.scala
Labels: stat:needs review

#5577 Fix #4785: Change typing rule for wildcard star args
  compiler/src/dotty/tools/dotc/core/TypeApplications.scala
  compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala
  compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/repeatedArgs213.scala
  tests/pos/i4785.scala
  tests/pos/repeatedArgs.scala
Labels: stat:needs review

#5586 Polishing to `InteractiveDriver.classesFromZip`
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
Labels: stat:needs review

#5589 Move TASTy Reflect decorators to top level
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
Labels: stat:needs review

#5601 Propagate dependencies through implicit parameters
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i5427.scala
  tests/pos/i5427.scala
Labels: area:typer

#5603 Add tasty seal methods
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/tastyreflect/QuotedOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsOpsImpl.scala
  docs/docs/reference/principled-meta-programming.md
  library/src/scala/quoted/Expr.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  tests/run-with-compiler/quote-function-applied-to.check
  tests/run-with-compiler/quote-function-applied-to.scala
  tests/run/tasty-seal-method/quoted_1.scala
  tests/run/tasty-seal-method/quoted_2.scala
Labels: stat:needs review

#5628 Fix #5527: Fix companion module for hk opaque type aliases
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  tests/run/i5527.scala
Labels: fasttrack

#5632 Fix #5411: varargs with intersection type elements
  compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala
  tests/pos/i5411.scala
Labels: fasttrack

#5623 Fix #5556: Check SAM types for realizability
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  tests/neg/i5556.scala
Labels: fasttrack

#5438 Add TASTy reflect constructors
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/tastyreflect/CaseDefOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/CoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/PatternOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/CaseDefOps.scala
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/PatternOps.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TreeUtils.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  tests/run/f-interpolation-1/FQuote_1.scala
  tests/run/i5119.check
  tests/run/tasty-extractors-1.check
  tests/run/tasty-interpolation-1/Macro.scala
  tests/run/tasty-tree-map.check
  tests/run/tasty-tree-map/quoted_1.scala
  tests/run/tasty-tree-map/quoted_2.scala
  tests/run/xml-interpolation-1/XmlQuote_1.scala
  tests/run/xml-interpolation-2/XmlQuote_1.scala
Labels: stat:needs review

#5627 Better error messages for missing symbols
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/Denotations.scala
  compiler/src/dotty/tools/dotc/core/Symbols.scala
Labels: fasttrack
