Repository scala/scala3, pull requests merged in 2018-08, with the labels that each got.

#4857 Fix inline scripted
  sbt-dotty/sbt-test/source-dependencies/inline/changes/B2.scala
  sbt-dotty/sbt-test/source-dependencies/inline/test
  sbt-dotty/sbt-test/source-dependencies/restore-classes/pending
  sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala
  sbt-dotty/src/dotty/tools/sbtplugin/TastyFileManager.scala
Labels: prio:blocker

#4887 Add <:< and =:= to testy reflect Type
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  tests/run/tasty-subtyping.check
  tests/run/tasty-subtyping/quoted_1.scala
  tests/run/tasty-subtyping/quoted_2.scala
Labels: stat:needs review

#4865 Fix tasty hash
  compiler/src/dotty/tools/dotc/core/tasty/TastyHash.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyPickler.scala
  compiler/test/dotty/tools/dotc/TastyHashTest.scala
Labels: stat:needs review

#4895 Add standard definitions on Tasty reflect
  compiler/src/dotty/tools/dotc/tastyreflect/FromSymbol.scala
  compiler/src/dotty/tools/dotc/tastyreflect/StandardDefinitions.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/reflect/StandardDefinitions.scala
  tests/run/tasty-definitions.check
  tests/run/tasty-definitions/quoted_1.scala
  tests/run/tasty-definitions/quoted_2.scala
Labels: stat:needs review

#4910 Add some regression tests for #4526
  tests/pos/i4526a.decompiled
  tests/pos/i4526a.scala
  tests/pos/i4526b.decompiled
  tests/pos/i4526b.scala
Labels: stat:needs review

#4909 Fix TASTy reflect Any and Nothing definitions
  compiler/src/dotty/tools/dotc/tastyreflect/FromSymbol.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  tests/run/tasty-definitions.check
  tests/run/tasty-extractors-3.check
Labels: stat:needs review

#4904 Remove class tags from Tasty reflect interface
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  library/src/scala/tasty/util/TreeAccumulator.scala
  tests/run/tasty-custom-show/quoted_1.scala
  tests/run/tasty-extractors-owners/quoted_1.scala
Labels: prio:blocker, stat:needs review

#4905 Split TASTy reflect interface and implementation
  compiler/src/dotty/tools/dotc/tastyreflect/CaseDefOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/ConstantOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/ContextOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/FlagSet.scala
  compiler/src/dotty/tools/dotc/tastyreflect/Helpers.scala
  compiler/src/dotty/tools/dotc/tastyreflect/IdOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/ImportSelectorOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/PatternOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/PositionOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/PrintersImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/QuotedOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/SignatureOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyCoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/reflect/CaseDefOps.scala
  library/src/scala/tasty/reflect/ConstantOps.scala
  library/src/scala/tasty/reflect/ContextOps.scala
  library/src/scala/tasty/reflect/FlagSet.scala
  library/src/scala/tasty/reflect/IdOps.scala
  library/src/scala/tasty/reflect/ImportSelectorOps.scala
  library/src/scala/tasty/reflect/PatternOps.scala
  library/src/scala/tasty/reflect/PositionOps.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/QuotedOps.scala
  library/src/scala/tasty/reflect/SignatureOps.scala
  library/src/scala/tasty/reflect/StandardDefinitions.scala
  library/src/scala/tasty/reflect/TastyCore.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  library/src/scala/tasty/util/ShowExtractors.scala
Labels: stat:needs review

#4941 Remove buggy override
  bench/src/main/scala/Benchmarks.scala
Labels: stat:needs review

#4885 Fix #4734: Pickle positions for quotes
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  tests/pos/i4734/Macro_1.scala
  tests/pos/i4734/Test_2.scala
  tests/run/i4734.check
  tests/run/i4734/Macro_1.scala
  tests/run/i4734/Test_2.scala
Labels: stat:needs review

#4723 Fix #4611
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/neg/i4611a.scala
  tests/neg/i4611b.scala
  tests/run/implicitFuns2.scala
Labels: stat:needs review

#4976 Add back symbols to TASTy reflect
  compiler/src/dotty/tools/dotc/tastyreflect/SymbolOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyCoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/reflect/SymbolOps.scala
  library/src/scala/tasty/reflect/TastyCore.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/util/TreeAccumulator.scala
  project/scripts/cmdTests
  tests/run/tasty-definitions-1.check
  tests/run/tasty-definitions-1/quoted_1.scala
  tests/run/tasty-definitions-1/quoted_2.scala
  tests/run/tasty-definitions-2.check
  tests/run/tasty-definitions-2/Macro_1.scala
  tests/run/tasty-definitions-2/Test_2.scala
  tests/run/tasty-definitions-3.check
  tests/run/tasty-definitions-3/Macro_1.scala
  tests/run/tasty-definitions-3/Test_2.scala
Labels: stat:needs review

#4967 Add test for #2864
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
Labels: area:ide

#4991 Use symbol instead of definition tree in TASTy reflect
  compiler/src/dotty/tools/dotc/tastyreflect/ContextOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/StandardDefinitions.scala
  compiler/src/dotty/tools/dotc/tastyreflect/SymbolOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsOpsImpl.scala
  library/src/scala/tasty/reflect/ContextOps.scala
  library/src/scala/tasty/reflect/StandardDefinitions.scala
  library/src/scala/tasty/reflect/SymbolOps.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/neg/tasty-macro-assert/quoted_1.scala
  tests/run/tasty-custom-show/quoted_1.scala
  tests/run/tasty-definitions-1.check
  tests/run/tasty-eval/quoted_1.scala
  tests/run/tasty-extractors-1.check
  tests/run/tasty-extractors-2.check
  tests/run/tasty-extractors-3.check
  tests/run/tasty-extractors-owners/quoted_1.scala
  tests/run/tasty-extractors-types.check
  tests/run/tasty-location/quoted_1.scala
  tests/run/tasty-macro-assert/quoted_1.scala
Labels: stat:needs review

#4949 Fix #4947: Do not replace positions of inlined arguments
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala
  compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala
  tests/run/i4947.check
  tests/run/i4947.scala
  tests/run/i4947a.check
  tests/run/i4947a.scala
  tests/run/i4947b.check
  tests/run/i4947b/Lib_1.scala
  tests/run/i4947b/Test_2.scala
  tests/run/i4947c.check
  tests/run/i4947c.scala
Labels: stat:needs review

#4998 Fix ambiguous unapply for TASTy reflect Parent
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/TastyCore.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  tests/pos-special/fatal-warnings/tasty-parent-unapply.scala
Labels: stat:needs review

#4893 Fix #4890: Mark level of pattern bindings
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/neg/i4890.scala
Labels: stat:needs review

#5030 Improve robustness of Namer for #5004
  compiler/src/dotty/tools/dotc/typer/Namer.scala
Labels: stat:needs review

#5057 Support go-to-definition on named arguments
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/DefinitionTest.scala
Labels: area:ide
