Repository scala/scala3, pull requests merged in 2018-05, with the labels that each got.

#4458 Fix #4455: Lift inlined values when quoted
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/run/i4455.check
  tests/run/i4455/Macro_1.scala
  tests/run/i4455/Test_2.scala
Labels: stat:needs review

#4474 Fix #4395: Handle ## when it is an Ident
  compiler/src/dotty/tools/dotc/transform/InterceptedMethods.scala
  tests/pos/i4395.scala
  tests/pos/i4395b.scala
Labels: stat:needs review

#4422 Fix #4373: reject wildcard types in syntactically invalid positions
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala
  tests/neg/i4373.scala
  tests/neg/i4373a.scala
  tests/neg/i4373b.scala
  tests/neg/i4373c.scala
Labels: stat:needs review

#4478 Fix current working directory for building Dotty from cmdline wrappers
  bin/common
Labels: area:tooling, exp:novice, stat:needs review

#4477 Eliminate nested blocks in functionAppliedTo
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
Labels: stat:needs review

#4266 Test compilation of decompiled code
  compiler/src/dotty/tools/dotc/decompiler/DecompilationPrinter.scala
  compiler/src/dotty/tools/dotc/decompiler/Main.scala
  compiler/src/dotty/tools/dotc/printing/DecompilerPrinter.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/test/dotty/tools/dotc/FromTastyTests.scala
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
  tests/pos/lambda.decompiled
  tests/pos/methodTypes.decompiled
  tests/pos/simpleCaseObject.decompiled
  tests/pos/simpleClass-2.decompiled
  tests/pos/simpleClass.decompiled
  tests/pos/simpleDoWhile.decompiled
  tests/pos/simpleWhile.decompiled
  tests/run/puzzle.decompiled
Labels: stat:needs review

#4480 FIx source of performance regression in #3961
  bench/tests/power-macro/PowerInlined-1.scala
  bench/tests/power-macro/PowerInlined.scala
  bench/tests/power-macro/PowerMacro.scala
  compiler/src/dotty/tools/dotc/transform/localopt/StringInterpolatorOpt.scala
Labels: stat:needs review

#4517 Docs: Unbreak link to proofs
  docs/docs/reference/principled-meta-programming.md
  docs/docs/reference/simple-smp.md
Labels: area:docs, stat:needs review

#4519 Selectable: catch correct exception when the field isn't found
  library/src/scala/reflect/Selectable.scala
  tests/run/i4496a.scala
Labels: itype:bug, stat:needs review

#4462 Fix #3932: ANSI color leak in repl
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/printing/ReplPrinter.scala
  compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala
  compiler/test-resources/repl/3932
  compiler/test-resources/repl/erased
  compiler/test-resources/repl/erased-implicit
Labels: stat:wip

#4457 Fix #4456: Pickle quote before compiling
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  library/src/scala/quoted/Expr.scala
  library/src/scala/quoted/FreeVariableError.scala
  tests/neg/quote-run-in-macro-1/quoted_1.scala
  tests/neg/quote-run-in-macro-1/quoted_2.scala
  tests/run/quote-run-in-macro-1.check
  tests/run/quote-run-in-macro-1/quoted_1.scala
  tests/run/quote-run-in-macro-1/quoted_2.scala
  tests/run/quote-run-in-macro-2.check
  tests/run/quote-run-in-macro-2/quoted_1.scala
  tests/run/quote-run-in-macro-2/quoted_2.scala
Labels: stat:needs review

#4460 Fix #4431: Change semantics of inline params in macro
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  docs/docs/reference/principled-meta-programming.md
  tests/neg/i4433.scala
  tests/run/i4431.check
  tests/run/i4431/quoted_1.scala
  tests/run/i4431/quoted_2.scala
Labels: stat:needs review

#4533 Fix printing of classes with companion objects in the decompiler (#4526)
  compiler/src/dotty/tools/dotc/printing/DecompilerPrinter.scala
  tests/pos/classWithCompObj.decompiled
  tests/pos/classWithCompObj.scala
Labels: stat:needs review

#4538 Pickle quotes directly as expressions in TASTY
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/core/tasty/DottyUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  tests/run-with-compiler/quote-owners-2.check
  tests/run-with-compiler/quote-owners-2.scala
  tests/run-with-compiler/quote-owners.check
  tests/run-with-compiler/quote-owners.scala
  tests/run-with-compiler/quote-run-large.scala
Labels: stat:needs review

#4518 Fix #4493 and #4514
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/pos/i4493-b.scala
  tests/pos/i4493-c.scala
  tests/pos/i4493.scala
  tests/pos/i4514.scala
Labels: stat:needs review

#4479 Handle QuotedError when evaluating holes in quotes
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  tests/neg/quote-error-2/Macro_1.scala
  tests/neg/quote-error-2/Test_2.scala
Labels: stat:needs review

#4491 Fix impure by name macro parameters
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  tests/run/quote-impure-by-name.check
  tests/run/quote-impure-by-name/quoted_1.scala
  tests/run/quote-impure-by-name/quoted_2.scala
  tests/run/quote-indexed-map-by-name/quoted_1.scala
  tests/run/quote-indexed-map-by-name/quoted_2.scala
Labels: stat:needs review

#4556 Fix #4542: Enable Dotty LSP on `.scala` files only
  vscode-dotty/src/extension.ts
Labels: area:ide

#4567 Fix macros with array parameters
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  tests/pos/macro-with-array/Macro_1.scala
  tests/pos/macro-with-array/Test_2.scala
Labels: stat:needs review

#4571 Fix #4492: Load module instance instead of calling static methods
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  tests/run/i4492.check
  tests/run/i4492/quoted_1.scala
  tests/run/i4492/quoted_2.scala
Labels: stat:needs review

#4576 Do not allow running Expr that came as macro arguments
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  library/src/scala/quoted/Expr.scala
  library/src/scala/quoted/FreeVariableError.scala
  tests/neg/quote-run-in-macro-2/quoted_1.scala
  tests/neg/quote-run-in-macro-2/quoted_2.scala
  tests/run/quote-run-in-macro-1.check
  tests/run/quote-run-in-macro-2.check
  tests/run/quote-run-in-macro-2/quoted_1.scala
  tests/run/quote-run-in-macro-2/quoted_2.scala
Labels: stat:needs review

#4581 Improve string representation of Tasty extractors
  library/src/scala/tasty/util/ShowExtractors.scala
  tests/run/tasty-extractors-1.check
  tests/run/tasty-extractors-2.check
  tests/run/tasty-extractors-3.check
  tests/run/tasty-extractors-owners.check
  tests/run/tasty-extractors-types.check
  tests/run/tasty-macro-assert.check
Labels: stat:needs review

#4574 Add `-Ycook-comments` to cook comments
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  doc-tool/src/dotty/tools/dottydoc/DocDriver.scala
  doc-tool/test/DottyDocTest.scala
Labels: area:docs, stat:needs review

#4529 Fix #4496: call ensureAccessible to bypass class-level accessibility
  library/src/scala/reflect/Selectable.scala
  tests/neg/i4496b.scala
  tests/run/i4496b.scala
Labels: stat:needs review

#4594 Fix #3651: Add regression test
  tests/neg/inlineAccess/C_1.scala
  tests/neg/inlineAccess/Test_2.scala
Labels: stat:needs review

#4531 Fix #4405 REPL highlight for StringLiteral
  compiler/src/dotty/tools/dotc/printing/SyntaxHighlighting.scala
  compiler/test/dotty/tools/dotc/printing/SyntaxHighlightingTests.scala
Labels: stat:wip

#4595 Split -print-tasty from -decompile
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/decompiler/DecompilationPrinter.scala
  dist/bin/dotc
  project/Build.scala
Labels: stat:needs review

#4602 Stop rewriting withFilter to filter
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/t6455.scala
  tests/pos/for-filter.scala
  tests/untried/neg/t6455.check
Labels: stat:needs review

#4548 Make 'namePos' return a point position if name is 'nme.ERROR'
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/interactive/SourceTree.scala
Labels: stat:needs review
