Repository scala/scala3, pull requests merged in 2018-10, with the labels that each got.

#5136 Fix offset of token EOF
  compiler/src/dotty/tools/dotc/parsing/CharArrayReader.scala
  compiler/test-resources/repl/i2213
  tests/neg/i2494.scala
  tests/neg/i4373a.scala
  tests/neg/i4373b.scala
  tests/neg/i4373c.scala
  tests/neg/parser-stability-1.scala
  tests/neg/parser-stability-10.scala
  tests/neg/parser-stability-11.scala
  tests/neg/parser-stability-12.scala
  tests/neg/parser-stability-14.scala
  tests/neg/parser-stability-15.scala
  tests/neg/parser-stability-16.scala
  tests/neg/parser-stability-18.scala
  tests/neg/parser-stability-19.scala
  tests/neg/parser-stability-2.scala
  tests/neg/parser-stability-20.scala
  tests/neg/parser-stability-21.scala
  tests/neg/parser-stability-22.scala
  tests/neg/parser-stability-3.scala
  tests/neg/parser-stability-4.scala
  tests/neg/parser-stability-5.scala
  tests/neg/parser-stability-9.scala
  tests/neg/parser-stability.scala
Labels: stat:needs review

#5187 Fix varargs in macros
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/test/dotc/run-test-pickling.blacklist
  tests/run/inline-varargs-1.check
  tests/run/inline-varargs-1/Macro_1.scala
  tests/run/inline-varargs-1/Main_2.scala
Labels: stat:needs review

#4968 TASTy reflect use complete definition trees
  compiler/src/dotty/tools/dotc/tastyreflect/FromSymbol.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-2.check
  tests/run-custom-args/Yretain-trees/tasty-definitions-2/Macro_1.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-2/Test_2.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-3.check
  tests/run-custom-args/Yretain-trees/tasty-definitions-3/Macro_1.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-3/Test_2.scala
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners.check
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners/quoted_2.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-1.check
  tests/run-custom-args/Yretain-trees/tasty-load-tree-1/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-1/quoted_2.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-2.check
  tests/run-custom-args/Yretain-trees/tasty-load-tree-2/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-2/quoted_2.scala
  tests/run/tasty-definitions-2.check
  tests/run/tasty-definitions-3.check
  tests/run/tasty-extractors-owners.check
Labels: stat:needs review

#5072 Fix level checking for this.type in macros
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/neg/quote-this.scala
  tests/pos/quote-this.scala
Labels: prio:blocker, stat:needs review

#5189 Fix #5119: Get underlying argument for synthetic local values
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/test/dotc/run-test-pickling.blacklist
  tests/run/i5119.check
  tests/run/i5119/Macro_1.scala
  tests/run/i5119/Main_2.scala
  tests/run/i5119b.check
  tests/run/i5119b/Macro_1.scala
  tests/run/i5119b/Main_2.scala
  tests/run/xml-interpolation/Test_2.scala
Labels: stat:needs review

#5105 Use `scala-lang.scala` for syntax highlighting
  project/Build.scala
  vscode-dotty/package.json
Labels: area:ide

#5181 Allow None and Some to be inline parameters
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/test/dotc/run-test-pickling.blacklist
  tests/neg/inline-option/Macro_1.scala
  tests/neg/inline-option/Main_2.scala
  tests/run/inline-option.check
  tests/run/inline-option/Macro_1.scala
  tests/run/inline-option/Main_2.scala
Labels: prio:blocker, stat:needs review

#4993 Split TASTy symbol
  compiler/src/dotty/tools/dotc/tastyreflect/FromSymbol.scala
  compiler/src/dotty/tools/dotc/tastyreflect/PrintersImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/SymbolOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyCoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/SymbolOps.scala
  library/src/scala/tasty/reflect/TastyCore.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/util/Show.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/neg/tasty-macro-assert/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-2.check
  tests/run-custom-args/Yretain-trees/tasty-definitions-2/Macro_1.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-2/Test_2.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-3.check
  tests/run-custom-args/Yretain-trees/tasty-definitions-3/Macro_1.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-3/Test_2.scala
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-1/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-2/quoted_1.scala
  tests/run/tasty-custom-show/quoted_1.scala
  tests/run/tasty-definitions-1.check
  tests/run/tasty-eval/quoted_1.scala
  tests/run/tasty-extractors-1.check
  tests/run/tasty-extractors-2.check
  tests/run/tasty-extractors-3.check
  tests/run/tasty-extractors-types.check
  tests/run/tasty-macro-assert/quoted_1.scala
Labels: stat:needs review

#5182 Implement tuple with quotes
  library/src-scala3/scala/StagedTuple.scala
  library/src-scala3/scala/Tuple.scala
Labels: stat:needs review

#5193 Create infrastructure for SemanticDB
  build.sbt
  compiler/src/dotty/tools/dotc/consumetasty/ConsumeTasty.scala
  compiler/src/dotty/tools/dotc/consumetasty/TastyConsumerPhase.scala
  compiler/src/dotty/tools/dotc/consumetasty/TastyFromClass.scala
  compiler/src/dotty/tools/dotc/quoted/QuoteDriver.scala
  library/src/scala/tasty/file/ConsumeTasty.scala
  library/src/scala/tasty/file/TastyConsumer.scala
  project/Build.scala
  semanticdb/src/dotty/semanticdb/DBConsumer.scala
  semanticdb/src/dotty/semanticdb/Main.scala
  semanticdb/test/dotty/semanticdb/Tests.scala
  semanticdb/test/tests/SimpleClass.scala
  semanticdb/test/tests/SimpleDef.scala
  tests/run-with-compiler/tasty-consumer.check
  tests/run-with-compiler/tasty-consumer/Foo.scala
  tests/run-with-compiler/tasty-consumer/Test.scala
Labels: prio:high, stat:needs review

#5213 Fix merge conflict between #5193 and #5204
  tests/run-with-compiler/tasty-consumer.check
Labels: prio:high, stat:needs review

#5211 Followup to #5203
  compiler/src/dotty/tools/dotc/config/Settings.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  compiler/src/dotty/tools/dotc/printing/Highlighting.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
  compiler/src/dotty/tools/dotc/transform/FunctionalInterfaces.scala
  compiler/src/dotty/tools/dotc/transform/LazyVals.scala
  compiler/src/dotty/tools/dotc/transform/TreeChecker.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
Labels: stat:needs review

#5102 Worksheet mode in Dotty IDE
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/reporting/diagnostic/ErrorMessageID.java
  compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/src/dotty/tools/repl/JLineTerminal.scala
  compiler/src/dotty/tools/repl/Main.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test-resources/repl/errmsgs
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/src/dotty/tools/languageserver/Main.scala
  language-server/src/dotty/tools/languageserver/worksheet/CancellationThread.scala
  language-server/src/dotty/tools/languageserver/worksheet/Evaluator.scala
  language-server/src/dotty/tools/languageserver/worksheet/ReplReader.scala
  language-server/src/dotty/tools/languageserver/worksheet/Worksheet.scala
  language-server/src/dotty/tools/languageserver/worksheet/WorksheetClient.scala
  language-server/src/dotty/tools/languageserver/worksheet/WorksheetMessages.scala
  language-server/src/dotty/tools/languageserver/worksheet/WorksheetService.scala
  language-server/test/dotty/tools/languageserver/DefinitionTest.scala
  language-server/test/dotty/tools/languageserver/HighlightTest.scala
  language-server/test/dotty/tools/languageserver/WorksheetTest.scala
  language-server/test/dotty/tools/languageserver/util/Code.scala
  language-server/test/dotty/tools/languageserver/util/CodeTester.scala
  language-server/test/dotty/tools/languageserver/util/actions/Action.scala
  language-server/test/dotty/tools/languageserver/util/actions/WorksheetAction.scala
  language-server/test/dotty/tools/languageserver/util/actions/WorksheetCancel.scala
  language-server/test/dotty/tools/languageserver/util/actions/WorksheetEvaluate.scala
  language-server/test/dotty/tools/languageserver/util/embedded/CodeMarker.scala
  language-server/test/dotty/tools/languageserver/util/server/TestClient.scala
  language-server/test/dotty/tools/languageserver/util/server/TestServer.scala
  sbt-bridge/src/xsbt/ConsoleInterface.scala
  sbt-dotty/src/dotty/tools/sbtplugin/DottyIDEPlugin.scala
  vscode-dotty/package.json
  vscode-dotty/src/extension.ts
  vscode-dotty/src/worksheet.ts
Labels: area:ide, stat:needs review

#5222 Don't check positions in `findTreesMatching`
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
Labels: area:ide

#5215 Fix #5188: See through annotations and typevars when computing argume…
  compiler/src/dotty/tools/dotc/core/TypeApplications.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/test/dotc/run-test-pickling.blacklist
  tests/pos/i5188.scala
  tests/run/i5188a.check
  tests/run/i5188a/Macro_1.scala
  tests/run/i5188a/Test_2.scala
Labels: stat:needs review

#5208 Fix `go to definition` with overridden methods
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/DefinitionTest.scala
  language-server/test/dotty/tools/languageserver/util/Code.scala
Labels: area:ide

#5235 Add TASTy reflect settings
  compiler/src/dotty/tools/dotc/tastyreflect/SettingsOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyCoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/reflect/SettingsOps.scala
  library/src/scala/tasty/reflect/TastyCore.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
Labels: stat:needs review

#5244 Fix #5242: Don't run all Scala files as worksheets
  vscode-dotty/src/features.ts
Labels: area:ide

#5246 Enable more tests from tests/untried
  tests/pos/abstract.scala
  tests/pos/annot-inner.scala
  tests/pos/attributes.scala
  tests/pos/cycle.flags
  tests/pos/cycle/J_1.java
  tests/pos/cycle/X_2.scala
  tests/pos/existentials.scala
  tests/pos/override.scala
  tests/pos/protected-static/J.java
  tests/pos/protected-static/JavaClass.java
  tests/pos/protected-static/S.scala
  tests/pos/protected-static/ScalaClass.scala
  tests/pos/strings.scala
  tests/pos/t4457_1.scala
  tests/pos/t4831.scala
  tests/pos/t5120.scala
  tests/pos/t5892.scala
  tests/pos/t6040.scala
  tests/pos/t7232/Foo.java
  tests/pos/t7232/List.java
  tests/pos/t7232/Test.scala
  tests/pos/t7475e.scala
  tests/pos/t8376/BindingsX.java
  tests/pos/t8376/Test.scala
  tests/untried/pos/A.scala
  tests/untried/pos/t7232.flags
Labels: stat:needs review

#5240 Fix go to definition on constructor calls
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  compiler/src/dotty/tools/dotc/interactive/SourceTree.scala
  language-server/test/dotty/tools/languageserver/DefinitionTest.scala
Labels: area:ide

#5263 Normalize blocks with no statements in quotes
  compiler/src/dotty/tools/dotc/quoted/TreeCleaner.scala
  tests/run-with-compiler/i3847-b.check
  tests/run-with-compiler/i4350.check
  tests/run-with-compiler/shonan-hmm.check
Labels: stat:needs review

#5262 Add link to by name implicit SIP to the doc
  docs/docs/reference/implicit-by-name-parameters.md
Labels: stat:needs review

#5265 Fix #5260: Type TupleXXL.apply as TupleXXL
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/run/i5260.check
  tests/run/i5260.scala
Labels: stat:needs review

#5160 Configure IDE with sbt server
  project/Build.scala
  vscode-dotty/package-lock.json
  vscode-dotty/package.json
  vscode-dotty/src/extension.ts
  vscode-dotty/src/sbt-server.ts
  vscode-dotty/src/types.d.ts
Labels: area:ide

#5255 Add spec for auto-tupling of n-ary functions
  docs/docs/reference/auto-parameter-tupling-spec.md
  docs/docs/reference/auto-parameter-tupling.md
  tests/neg/automatic-tupling-of-function-parameters.scala
  tests/pos/automatic-tupling-of-function-parameters.scala
  tests/run/automatic-tupling-of-function-parameters-implicit-conversion.scala
  tests/run/automatic-tupling-of-function-parameters-spec.check
  tests/run/automatic-tupling-of-function-parameters-spec.scala
Labels: stat:needs review

#5285 IDE: Find and add workspace root if there are none
  vscode-dotty/src/extension.ts
Labels: area:ide

#5289 Fix #5284: Restore worksheet decorations
  vscode-dotty/src/worksheet.ts
Labels: area:ide

#5291 Add regression tests for #1593
  tests/neg/isRef.scala
  tests/pos/isRef.scala
Labels: stat:needs review

#5058 Support multi-project setups in the IDE tests
  language-server/test/dotty/tools/languageserver/DefinitionTest.scala
  language-server/test/dotty/tools/languageserver/util/Code.scala
  language-server/test/dotty/tools/languageserver/util/CodeTester.scala
  language-server/test/dotty/tools/languageserver/util/server/TestServer.scala
  project/Build.scala
Labels: area:ide, area:testing, stat:needs review

#5292 Add recompilation regression tests
  compiler/test/dotc/pos-recompilation.whitelist
Labels: stat:needs review

#5261 Fix #5247: Support type blocks and fix generic tuples
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/config/Printers.scala
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src-scala3/scala/StagedTuple.scala
  library/src-scala3/scala/Tuple.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/run-with-compiler/i5247.check
  tests/run-with-compiler/i5247.scala
  tests/run-with-compiler/quote-owners-2.check
Labels: stat:needs review

#5216 Move inline β-reduction out of typer
  compiler/src/dotty/tools/dotc/CompilationUnit.scala
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/decompiler/TASTYDecompiler.scala
  compiler/src/dotty/tools/dotc/transform/InlineCalls.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotc/pos-from-tasty.blacklist
  tests/pos/depfuntype.scala
  tests/run/tuples1a.scala
Labels: stat:needs review

#5272 Enable test on generic tuples
  tests/run/tuple-for-comprehension.scala
Labels: stat:needs review

#5164 Tasty reflect underlying tree
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/test/dotc/run-test-pickling.blacklist
  library/src/scala/tasty/reflect/TreeOps.scala
  tests/run/tasty-argument-tree-1.check
  tests/run/tasty-argument-tree-1/quoted_1.scala
  tests/run/tasty-argument-tree-1/quoted_2.scala
  tests/run/xml-interpolation-1/Test_2.scala
  tests/run/xml-interpolation-1/XmlQuote_1.scala
  tests/run/xml-interpolation-2/Test_2.scala
  tests/run/xml-interpolation-2/XmlQuote_1.scala
Labels: stat:needs review

#5299 Allow macros to call method returning implicit functions
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/test/dotc/run-test-pickling.blacklist
  tests/run/tasty-getfile-implicit-fun-context.check
  tests/run/tasty-getfile-implicit-fun-context/App_2.scala
  tests/run/tasty-getfile-implicit-fun-context/Macro_1.scala
  tests/run/tasty-implicit-fun-context-2.check
  tests/run/tasty-implicit-fun-context-2/App_2.scala
  tests/run/tasty-implicit-fun-context-2/Macro_1.scala
Labels: stat:needs review

#5307 Improve compression of TastyString
  compiler/src/dotty/tools/dotc/core/tasty/TastyString.scala
Labels: stat:needs review

#5314 Make the output a list to be able to consume it twice
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
Labels: stat:needs review

#5317 Handle Toolbox showRawTree the same way we handle color
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/quoted/QuoteDriver.scala
Labels: stat:needs review

#5316 Remove dead code
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
Labels: stat:needs review

#5315 Implement Liftable explicitly
  library/src/scala/quoted/Liftable.scala
  tests/run-with-compiler/i3847-b.scala
  tests/run-with-compiler/i3847.scala
  tests/run-with-compiler/quote-lib.scala
Labels: stat:needs review

#5330 Remove filter for gh-pages from drone.yml
  .drone.yml
Labels: stat:needs review

#5127 Add LSP tracing
  vscode-dotty/package-lock.json
  vscode-dotty/package.json
  vscode-dotty/src/compat.ts
  vscode-dotty/src/extension.ts
  vscode-dotty/src/features.ts
  vscode-dotty/src/passthrough-server.ts
  vscode-dotty/src/sbt-server.ts
  vscode-dotty/src/tracer.ts
  vscode-dotty/src/tracing-consent.ts
Labels: area:ide

#5348 Small clarification for Multiversal Equality documentation
  docs/docs/reference/multiversal-equality.md
Labels: stat:needs review

#5347 More details on implicit conversions
  docs/docs/reference/changed/implicit-conversions-spec.md
  docs/docs/reference/changed/implicit-conversions.md
Labels: stat:needs review

#5339 More details on Vararg Patterns
  docs/docs/reference/changed/vararg-patterns.md
Labels: stat:needs review

#5353 Fix #5324: Ask before switching workspaces
  vscode-dotty/src/extension.ts
Labels: area:ide
