Repository scala/scala3, pull requests merged in 2018-04, with the labels that each got.

#4211 Optimize splices without captures
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
Labels: stat:needs review

#4239 Fix #4143: Ignore lines "Picked up _JAVA_OPTIONS" in tests
  compiler/test/dotty/tools/vulpix/ChildJVMMain.java
  compiler/test/dotty/tools/vulpix/RunnerOrchestration.scala
Labels: stat:needs review

#4249 Fix #4248: intersection dominator of Arrays
  compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala
  tests/generic-java-signatures/i4248.check
  tests/generic-java-signatures/i4248.scala
Labels: area:backend, stat:needs review

#4235 Cache classloaders in Splicer
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
Labels: stat:needs review

#4255 Simplify decompiler printer for lambda
  compiler/src/dotty/tools/dotc/printing/DecompilerPrinter.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  tests/pos/lambda.decompiled
  tests/pos/lambda.scala
  tests/run-with-compiler/i3876-c.check
  tests/run-with-compiler/quote-run-staged-interpreter.check
Labels: stat:needs review

#4267 Small performance enhancements
  compiler/src/dotty/tools/dotc/transform/InterceptedMethods.scala
  compiler/src/dotty/tools/dotc/transform/localopt/Simplify.scala
Labels: stat:needs review

#4271 Clean FromTastyTests blacklist
  compiler/test/dotty/tools/dotc/FromTastyTests.scala
Labels: stat:needs review

#4213 Pretty print quotes
  compiler/src/dotty/tools/dotc/printing/DecompilerPrinter.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  tests/run-with-compiler/quote-nested-1.check
  tests/run-with-compiler/quote-nested-2.check
  tests/run-with-compiler/quote-nested-4.check
  tests/run-with-compiler/quote-nested-5.check
Labels: stat:needs rebase

#4287 Fix #3653: generic Java signature of FunctionXXL
  compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala
  tests/generic-java-signatures/i3653.check
  tests/generic-java-signatures/i3653.scala
Labels: stat:needs review

#3503 Fix #3476: Add `Artifact` flag to closures
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala
  compiler/src/dotty/tools/dotc/transform/LambdaLift.scala
  tests/generic-java-signatures/i3476.check
  tests/generic-java-signatures/i3476.scala
Labels: stat:wip

#4204 Fix quoted type tags and use them instead of pickling
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  tests/run-with-compiler/quote-type-tags.check
  tests/run-with-compiler/quote-type-tags.scala
  tests/run/i4205.check
  tests/run/i4205.scala
Labels: stat:needs review

#4310 Fix #4301: Show `null` as "null"
  compiler/test-resources/repl/i4301
  library/src/dotty/Show.scala
  library/test/dotty/ShowTests.scala
Labels: stat:needs review

#4254 Drop MethodOrHKCommon, ensure HigherKinded is properly labeled
  compiler/src/dotty/tools/dotc/core/Flags.scala
Labels: stat:needs review

#4348 Fix typo in neg test
  tests/neg/i3736b.scala
Labels: stat:needs review

#4384 Fix #4380: Revert optimization that breaks owners
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/pos/i4380a.scala
  tests/pos/i4380b.scala
Labels: stat:needs review

#4363 Fix #4350: Do not check prefix of class type parameters
  compiler/src/dotty/tools/dotc/quoted/TreeCleaner.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  tests/neg/i4350.scala
  tests/pos/i4350.scala
  tests/run-with-compiler/i4350.check
  tests/run-with-compiler/i4350.scala
Labels: stat:needs review

#4245 Fix #4177: Generate optimised applyOrElse implementation for partial function literals
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala
  tests/neg/i4241.scala
  tests/pos/i4177.scala
  tests/run/i4177.scala
  tests/run/partialFunctions.scala
Labels: stat:needs review
