Repository scala/scala3, pull requests merged in 2018-07, with the labels that each got.

#4432 Prevent position errors on Ident(nme.ERROR)
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  tests/neg/parser-stability-23.scala
Labels: area:parser, area:positions, stat:needs review

#4610 Add an implementation example of fully abstract interface
  tests/run/fully-abstract-interface.check
  tests/run/fully-abstract-interface.scala
  tests/run/fully-abstract-nat-1.check
  tests/run/fully-abstract-nat-1.scala
  tests/run/fully-abstract-nat-2.check
  tests/run/fully-abstract-nat-2.scala
  tests/run/fully-abstract-nat-3.check
  tests/run/fully-abstract-nat-3.scala
  tests/run/fully-abstract-nat-4.check
  tests/run/fully-abstract-nat-4.scala
  tests/run/fully-abstract-nat-5.check
  tests/run/fully-abstract-nat-5.scala
  tests/run/fully-abstract-nat-6.check
  tests/run/fully-abstract-nat-6.scala
  tests/run/fully-abstract-nat-7.check
  tests/run/fully-abstract-nat-7.scala
  tests/run/fully-abstract-nat.check
  tests/run/fully-abstract-nat.scala
Labels: stat:needs review

#4746 Synchronise quoted.Toolbox
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
Labels: stat:needs review

#4751 Cook comment on empty classes
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  doc-tool/test/SimpleComments.scala
Labels: area:doctool

#4775 Fix #4774: Skip TypeVars and skip if level is equal
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/neg/i4774b.scala
  tests/pos/i4774.scala
Labels: stat:needs review

#4777 Fix inline parameters lifted for 0 to 1
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  library/src/scala/quoted/Liftable.scala
  tests/pos/quote-lift-inline-params-b.scala
  tests/pos/quote-lift-inline-params/App_2.scala
  tests/pos/quote-lift-inline-params/Macro_1.scala
Labels: stat:needs review

#4669 Add `:doc` command in REPL to show documentation
  compiler/src/dotty/tools/repl/ParseResult.scala
  compiler/src/dotty/tools/repl/ReplCompiler.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test/dotty/tools/repl/DocTests.scala
Labels: area:docs, area:repl, itype:enhancement, stat:on hold

#4573 Dottydoc: Keep documentation on package objects
  doc-tool/src/dotty/tools/dottydoc/DocCompiler.scala
  doc-tool/test/SimpleComments.scala
Labels: area:doctool, stat:wip

#4780 Disallow inferred splices and set the correct position
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/neg/i4774a.scala
  tests/pos/i4774c.scala
  tests/pos/i4774d.scala
Labels: stat:needs review

#4717 Refresh names inExpr.show
  compiler/src/dotty/tools/dotc/quoted/QuoteDecompiler.scala
  compiler/src/dotty/tools/dotc/quoted/RefreshNames.scala
  tests/run-with-compiler/quote-run-2.check
  tests/run-with-compiler/quote-run-2.scala
Labels: stat:needs review

#4736 Add tests example of a partially unrolled loop
  tests/run-with-compiler/quote-unrolled-foreach.check
  tests/run-with-compiler/quote-unrolled-foreach.scala
  tests/run/quote-unrolled-foreach.check
  tests/run/quote-unrolled-foreach/quoted_1.scala
  tests/run/quote-unrolled-foreach/quoted_2.scala
Labels: stat:needs review

#4726 Implement Shonan HMM
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/run-with-compiler/shonan-hmm-simple.check
  tests/run-with-compiler/shonan-hmm-simple.scala
  tests/run-with-compiler/shonan-hmm.check
  tests/run-with-compiler/shonan-hmm/Blas.scala
  tests/run-with-compiler/shonan-hmm/Complex.scala
  tests/run-with-compiler/shonan-hmm/Lifters.scala
  tests/run-with-compiler/shonan-hmm/MVmult.scala
  tests/run-with-compiler/shonan-hmm/PV.scala
  tests/run-with-compiler/shonan-hmm/Ring.scala
  tests/run-with-compiler/shonan-hmm/Test.scala
  tests/run-with-compiler/shonan-hmm/UnrolledExpr.scala
  tests/run-with-compiler/shonan-hmm/Vec.scala
  tests/run-with-compiler/shonan-hmm/VecOp.scala
  tests/run-with-compiler/shonan-hmm/VecROp.scala
  tests/run-with-compiler/shonan-hmm/Vmults.scala
Labels: stat:needs review

#4546 Join logic for unpickling top level and term tasty
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/core/quoted/QuoteUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/DottyUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/transform/Pickler.scala
Labels: stat:needs review

#4809 Check tasty file hash
  compiler/src/dotty/tools/backend/jvm/GenBCode.scala
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyHeaderUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyUnpickler.scala
Labels: stat:needs review

#4824 Add missing SuperType in pattern match
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
Labels: stat:needs review

#4645 Add FromTastyDecompilation decompilation blacklist
  compiler/test/dotc/pos-decompilation.blacklist
  compiler/test/dotc/pos-from-tasty.blacklist
  compiler/test/dotc/pos-recompilation.whitelist
  compiler/test/dotc/run-decompilation.blacklist
  compiler/test/dotc/run-from-tasty.blacklist
  compiler/test/dotc/run-recompilation.whitelist
  compiler/test/dotty/tools/StdLibSources.scala
  compiler/test/dotty/tools/TestSources.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  compiler/test/dotty/tools/dotc/FromTastyTests.scala
  compiler/test/dotty/tools/vulpix/FileFilter.scala
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
  doc-tool/test/WhitelistedStdLib.scala
Labels: stat:needs review

#4845 Add new test to the blacklist
  compiler/test/dotc/pos-recompilation.whitelist
  compiler/test/dotc/run-decompilation.blacklist
Labels: prio:high, stat:needs review

#4847 Reduce recompilation whitelist to tests having a .decompiled
  compiler/test/dotc/pos-recompilation.whitelist
  compiler/test/dotc/run-recompilation.whitelist
Labels: stat:needs review

#4832 Fix the reproduction script for testFromTasty tests
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
Labels: stat:needs review

#4822 Change top-level ~ evaluation scheme
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  docs/docs/reference/principled-meta-programming.md
  library/src/scala/tasty/Tasty.scala
  tests/neg-with-compiler/quote-run-in-macro-1/quoted_1.scala
  tests/neg-with-compiler/quote-run-in-macro-2/quoted_1.scala
  tests/neg/i4433.scala
  tests/neg/i4493-b.scala
  tests/neg/i4493.scala
  tests/neg/quote-complex-top-splice.scala
  tests/neg/quote-macro-complex-arg-0.scala
  tests/neg/quote-splice-interpret-1.scala
  tests/neg/tasty-macro-assert/quoted_1.scala
  tests/pending/run/tasty-linenumber/quoted_1.scala
  tests/pending/run/tasty-linenumber/quoted_2.scala
  tests/pos-with-compiler/tasty/definitions.scala
  tests/pos/i4773.scala
  tests/pos/quote-lift-inline-params-b.scala
  tests/pos/quote-lift-inline-params/Macro_1.scala
  tests/run-with-compiler/quote-impure-by-name.check
  tests/run-with-compiler/quote-splice-interpret-1/Macro_1.scala
  tests/run-with-compiler/quote-splice-interpret-1/Test_2.scala
  tests/run-with-compiler/tasty-positioned.check
  tests/run-with-compiler/tasty-positioned/quoted_1.scala
  tests/run-with-compiler/tasty-positioned/quoted_2.scala
  tests/run/i4735.check
  tests/run/i4735/App_2.scala
  tests/run/i4735/Macro_1.scala
  tests/run/quote-and-splice/Macros_1.scala
  tests/run/quote-sep-comp-2/Macro_1.scala
  tests/run/quote-sep-comp-2/Test_2.scala
  tests/run/quote-simple-macro.check
  tests/run/quote-simple-macro/quoted_1.scala
  tests/run/tasty-extractors-1.check
  tests/run/tasty-extractors-2.check
  tests/run/tasty-extractors-2/quoted_2.scala
  tests/run/tasty-extractors-types.check
  tests/run/tasty-macro-assert/quoted_1.scala
  tests/run/tasty-positioned.check
  tests/run/tasty-positioned/quoted_1.scala
Labels: stat:needs review

#4864 Print classfile when failing a UUID Tasty check
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala
Labels: stat:needs review

#4859 Add rootPosition to Tasty reflect
  compiler/src/dotty/tools/dotc/quoted/QuoteDriver.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  library/src/scala/tasty/Tasty.scala
  tests/run-with-compiler/tasty-positioned.check
  tests/run-with-compiler/tasty-positioned/quoted_1.scala
  tests/run/tasty-linenumber-2.check
  tests/run/tasty-linenumber-2/quoted_1.scala
  tests/run/tasty-linenumber-2/quoted_2.scala
  tests/run/tasty-linenumber/quoted_1.scala
  tests/run/tasty-linenumber/quoted_2.scala
  tests/run/tasty-positioned.check
  tests/run/tasty-positioned/quoted_1.scala
  tests/run/tasty-positioned/quoted_2.scala
Labels: stat:needs review

#4823 Enable macros in any transparent def
  bench/tests/power-macro/PowerMacro.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/pos/quote-non-static-macro.scala
  tests/run/i4803.check
  tests/run/i4803/App_2.scala
  tests/run/i4803/Macro_1.scala
  tests/run/i4803b.check
  tests/run/i4803b/App_2.scala
  tests/run/i4803b/Macro_1.scala
  tests/run/i4803c.check
  tests/run/i4803c/App_2.scala
  tests/run/i4803c/Macro_1.scala
  tests/run/i4803d.check
  tests/run/i4803d/App_2.scala
  tests/run/i4803d/Macro_1.scala
  tests/run/i4803e/App_2.scala
  tests/run/i4803e/Macro_1.scala
  tests/run/i4803f/App_2.scala
  tests/run/i4803f/Macro_1.scala
Labels: stat:needs review

#4875 Add regression tests
  compiler/test/dotc/pos-decompilation.blacklist
  compiler/test/dotc/run-decompilation.blacklist
Labels: stat:needs review

#4874 Add scala.Symbol constants to Tasty reflect
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/test/dotc/pos-decompilation.blacklist
  compiler/test/dotc/run-decompilation.blacklist
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
Labels: stat:needs review

#4870 Add some post conditions to ReifyQuotes
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
Labels: stat:needs review

#4878 Add regression tests
  compiler/test/dotc/pos-decompilation.blacklist
  compiler/test/dotc/run-decompilation.blacklist
Labels: stat:needs review

#4856 Fix #4846: Allow transparent parameters at any stage
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/pos/i4846.scala
Labels: stat:needs review

#4877 Fix Tasty reflect with varargs in unapply
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/test/dotc/run-decompilation.blacklist
Labels: stat:needs review

#4882 Fix tasty reflect ParamRef extractor on TermParamRef
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/test/dotc/pos-decompilation.blacklist
Labels: stat:needs review
