Repository scala/scala3, pull requests merged in 2018-02, with the labels that each got.

#4020 Drop navigation arrows from homepage
  docs/_includes/getting-started.html
  docs/_includes/logo-page.html
  docs/css/default.css
Labels: area:docs

#3883 Seal quoted.Expr and quoted.Type
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/interpreter/Interpreter.scala
  compiler/src/dotty/tools/dotc/interpreter/RawQuoted.scala
  compiler/src/dotty/tools/dotc/quoted/ExprCompiler.scala
  compiler/src/dotty/tools/dotc/quoted/Runners.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala
  docs/docs/reference/principled-meta-programming.md
  library/src/scala/quoted/Expr.scala
  library/src/scala/quoted/Liftable.scala
  library/src/scala/quoted/Quoted.scala
  library/src/scala/quoted/TastyExpr.scala
  library/src/scala/quoted/TastyQuoted.scala
  library/src/scala/quoted/TastyType.scala
  library/src/scala/quoted/Type.scala
  library/src/scala/runtime/quoted/Unpickler.scala
  tests/neg/i3187.scala
Labels: stat:needs review

#4019 Fix #3898: Do not interpret bindings for inlined parameters
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  tests/pos/i3898/quoted_1.scala
  tests/pos/i3898/quoted_2.scala
  tests/pos/i3898b/quoted_1.scala
  tests/pos/i3898b/quoted_2.scala
  tests/pos/i3898c/quoted_1.scala
  tests/pos/i3898c/quoted_2.scala
  tests/pos/quote-interpolator-core/quoted_1.scala
  tests/pos/quote-interpolator-core/quoted_2.scala
Labels: stat:needs review

#4001 Fix trees not being loaded from tasty when class symbol has NoCompleter
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  project/scripts/cmdTests
Labels: stat:needs review

#4017 Fix #4006: Avoid ambiguity between SHAREDterm cases and finally
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  tests/pickling/i4006.scala
  tests/pickling/i4006b.scala
  tests/pickling/i4006c.scala
Labels: stat:needs review

#4039 Rename isDependent
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
Labels: area:typer

#4034 Fix #4030: avoid adding duplicate binders
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  tests/patmat/i4030.check
  tests/patmat/i4030.scala
Labels: area:typer

#4040 Rename quoted.Runner to quoted.Toolbox
  compiler/src/dotty/tools/dotc/quoted/QuoteDriver.scala
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
  library/src/scala/quoted/Constant.scala
  library/src/scala/quoted/Expr.scala
  library/src/scala/runtime/quoted/Toolbox.scala
  tests/pending/run-with-compiler/quote-run-constants-extract.scala
  tests/pending/run-with-compiler/quote-run-large.scala
  tests/pos/quote-0.scala
  tests/pos/quote-assert/quoted_2.scala
  tests/run-with-compiler/i3823-b.scala
  tests/run-with-compiler/i3823-c.scala
  tests/run-with-compiler/i3823.scala
  tests/run-with-compiler/i3876-b.scala
  tests/run-with-compiler/i3876-c.scala
  tests/run-with-compiler/i3876-d.scala
  tests/run-with-compiler/i3876.scala
  tests/run-with-compiler/i3946.scala
  tests/run-with-compiler/quote-lib.scala
  tests/run-with-compiler/quote-run-2.scala
  tests/run-with-compiler/quote-run-b.scala
  tests/run-with-compiler/quote-run-c.scala
  tests/run-with-compiler/quote-run-constants.scala
  tests/run-with-compiler/quote-run-staged-interpreter.scala
  tests/run-with-compiler/quote-run-with-settings.scala
  tests/run-with-compiler/quote-run.scala
Labels: stat:needs review

#4041 Move settings to toolbox
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
  tests/run-with-compiler/quote-run-with-settings.scala
Labels: stat:wip

#4049 Fix path to `dotty/out`
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  compiler/test/dotty/tools/dotc/InterfaceEntryPointTest.scala
  compiler/test/dotty/tools/dotc/SettingsTests.scala
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
  tests/idempotency/BootstrapChecker.scala
  tests/idempotency/CheckOrderIdempotency.scala
  tests/idempotency/CheckPosIdempotency.scala
  tests/idempotency/CheckStrawmanIdempotency.scala
  tests/pos/lambda.decompiled
  tests/pos/methodTypes.decompiled
  tests/pos/simpleCaseObject.decompiled
  tests/pos/simpleClass.decompiled
  tests/run-with-compiler/quote-run-with-settings.scala
  tests/run/puzzle.decompiled
  tests/vulpix-tests/meta/sbt-output.check
Labels: stat:needs review
