Repository scala/scala3, pull requests merged in 2018-11, with the labels that each got.

#5259 Fix #5257: Support auto generic-tupling of parameters
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotc/run-test-pickling.blacklist
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tests/run-custom-args/i5256.check
  tests/run-custom-args/i5256.scala
  tests/run/i5257.check
  tests/run/i5257.scala
Labels: stat:needs review

#5385 Port of gestalt Optional as a test
  tests/run-separate-compilation/gestalt-optional-inline/Macro_1.scala
  tests/run-separate-compilation/gestalt-optional-inline/Test_2.scala
  tests/run-separate-compilation/gestalt-optional-staging/Macro_1.scala
  tests/run-separate-compilation/gestalt-optional-staging/Test_2.scala
Labels: stat:needs review

#5342 More details on Lazy Vals
  docs/docs/reference/changed/lazy-vals-spec.md
  docs/docs/reference/changed/lazy-vals.md
  tests/run/i1856.check
  tests/run/i1856.scala
Labels: stat:needs review

#5383 Add specializing inline
  compiler/src/dotty/tools/dotc/CompilationUnit.scala
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/core/NameOps.scala
  compiler/src/dotty/tools/dotc/core/Names.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyFormat.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/decompiler/TASTYDecompiler.scala
  compiler/src/dotty/tools/dotc/parsing/CharArrayReader.scala
  compiler/src/dotty/tools/dotc/parsing/JavaScanners.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  compiler/src/dotty/tools/dotc/parsing/package.scala
  compiler/src/dotty/tools/dotc/parsing/xml/MarkupParserCommon.scala
  compiler/src/dotty/tools/dotc/parsing/xml/MarkupParsers.scala
  compiler/src/dotty/tools/dotc/parsing/xml/Utility.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/Staging.scala
  compiler/src/dotty/tools/dotc/transform/TreeChecker.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/src/dotty/tools/dotc/util/CommentParsing.scala
  compiler/src/dotty/tools/dotc/util/NameTransformer.scala
  compiler/src/dotty/tools/dotc/util/SourceFile.scala
  compiler/test/dotc/pos-decompilation.blacklist
  compiler/test/dotc/pos-from-tasty.blacklist
  compiler/test/dotc/pos-recompilation.whitelist
  compiler/test/dotc/run-test-pickling.blacklist
  compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala
  docs/docs/internals/syntax.md
  library/src/scala/tasty/util/Chars.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/disabled/pos/inline-named-typeargs.scala
  tests/neg-with-compiler/quote-run-in-macro-2/quoted_2.scala
  tests/neg-with-compiler/quote-run-in-macro-3/quoted_1.scala
  tests/neg-with-compiler/quote-run-in-macro-3/quoted_2.scala
  tests/neg-with-compiler/quote-run-in-macro-4/quoted_1.scala
  tests/neg-with-compiler/quote-run-in-macro-4/quoted_2.scala
  tests/neg/specializing-inline.scala
  tests/neg/tasty-macro-assert-2/quoted_1.scala
  tests/neg/tasty-macro-assert-2/quoted_2.scala
  tests/neg/tasty-macro-assert/quoted_2.scala
  tests/pos/i4006.scala
  tests/pos/inline-named-typeargs.scala
  tests/pos/simpleInline.decompiled
  tests/pos/test.sc
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners.check
  tests/run-separate-compilation/i5119.check
  tests/run-separate-compilation/xml-interpolation-2/XmlQuote_1.scala
  tests/run-with-compiler/i3876-d.check
  tests/run-with-compiler/i3876-d.scala
Labels: stat:needs review

#5391 Handle structural types with curried methods
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/typer/Dynamic.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/docs/reference/changed/structural-types-spec.md
  library/src/scala/reflect/Selectable.scala
  tests/neg/structural.scala
  tests/run/structural.scala
Labels: stat:needs review

#5393 Store documentation on auxiliary constructors
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
Labels: area:parser

#5415 Fix #5414: Always emit / for path in decompilation comment
  compiler/src/dotty/tools/dotc/decompiler/DecompilationPrinter.scala
Labels: stat:needs review

#5388 Port gestalt TypeToolbox
  compiler/src/dotty/tools/dotc/tastyreflect/SymbolOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/SymbolOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  tests/run-separate-compilation/gestalt-type-toolbox-reflect/Macro_1.scala
  tests/run-separate-compilation/gestalt-type-toolbox-reflect/Test_2.scala
Labels: stat:needs review

#5209 Support for multi-project `find all references`
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/src/dotty/tools/languageserver/config/ProjectConfig.java
  language-server/test/dotty/tools/languageserver/ReferencesTest.scala
  language-server/test/dotty/tools/languageserver/util/actions/CodeReferences.scala
  language-server/test/dotty/tools/languageserver/util/server/TestServer.scala
  sbt-dotty/src/dotty/tools/sbtplugin/DottyIDEPlugin.scala
Labels: area:ide, stat:needs review

#5401 IDE: Support `textDocument/implementation`
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/ImplementationTest.scala
  language-server/test/dotty/tools/languageserver/util/CodeTester.scala
  language-server/test/dotty/tools/languageserver/util/actions/Implementation.scala
Labels: area:ide

#5395 IDE: Support `textDocument/signatureHelp`
  compiler/src/dotty/tools/dotc/reporting/diagnostic/ErrorMessageID.java
  compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/src/dotty/tools/dotc/util/Signatures.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/SignatureHelpTest.scala
  language-server/test/dotty/tools/languageserver/util/CodeTester.scala
  language-server/test/dotty/tools/languageserver/util/actions/SignatureHelp.scala
Labels: area:ide

#5437 Add documentation to TASTy reflect
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/FlagSet.scala
  library/src/scala/tasty/reflect/IdOps.scala
  library/src/scala/tasty/reflect/PatternOps.scala
  library/src/scala/tasty/reflect/PositionOps.scala
  library/src/scala/tasty/reflect/SettingsOps.scala
  library/src/scala/tasty/reflect/SignatureOps.scala
  library/src/scala/tasty/reflect/SymbolOps.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
Labels: stat:needs review

#5442 Add AnyRef bound to TASTy reflect types
  library/src/scala/tasty/reflect/Core.scala
Labels: stat:needs review

#5456 Fix crash when `showMessageRequest` is discarded
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
Labels: area:ide

#5428 Add test case for #5418
  tests/neg/i5418.scala
Labels: stat:needs review

#5465 Fix #5380: Add documentation for worksheet mode
  docs/docs/usage/ide-support.md
  docs/docs/usage/worksheet-mode-implementation-details.md
  docs/docs/usage/worksheet-mode.md
  docs/images/worksheets/config-autorun.png
  docs/images/worksheets/worksheet-help.png
  docs/images/worksheets/worksheet-run.png
  docs/sidebar.yml
Labels: area:documentation, area:ide

#5483 Add missing types to TASTy reflect
  compiler/src/dotty/tools/dotc/tastyreflect/CoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
Labels: stat:needs review

#5392 Inline and implicit matches
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyFormat.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/parsing/Tokens.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotc/pos-test-pickling.blacklist
  compiler/test/dotc/run-from-tasty.blacklist
  compiler/test/dotc/run-test-pickling.blacklist
  docs/docs/internals/syntax.md
  library/src-scala3/scala/StagedTuple.scala
  library/src-scala3/scala/Tuple.scala
  tests/invalid/neg/typelevel.scala
  tests/invalid/pos/transparent-overload.scala
  tests/invalid/pos/typelevel-vector1.scala
  tests/invalid/run/Tuple.scala
  tests/invalid/run/typelevel-patmat.scala
  tests/invalid/run/typelevel1.scala
  tests/invalid/run/typelevel3.scala
  tests/neg/implicitMatch-syntax.scala
  tests/neg/inline-overload.scala
  tests/neg/inline-unapply.scala
  tests/neg/nested-rewrites.scala
  tests/neg/transparent-override/B_2.scala
  tests/neg/tuple-oob1.scala
  tests/neg/typelevel-noeta.scala
  tests/pos-deep-subtype/tuples23.check
  tests/pos-deep-subtype/tuples23.scala
  tests/pos/i2166.scala
  tests/pos/inline-caseclass.scala
  tests/pos/inline-i1773.scala
  tests/pos/inline-rewrite.scala
  tests/pos/test.sc
  tests/pos/typelevel0.scala
  tests/run/implicitMatch.check
  tests/run/implicitMatch.scala
  tests/run/tuples1.check
  tests/run/tuples1.scala
  tests/run/typelevel-defaultValue.scala
  tests/run/typelevel-overrides.scala
  tests/run/typelevel-peano.check
  tests/run/typelevel-peano.scala
Labels: stat:needs rebase, stat:needs review

#5472 Restrict visibility of copy and apply
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  tests/neg/private-case-class-constr.scala
  tests/pos/i4564.scala
Labels: stat:needs spec

#5435 Addition to TASTy reflect to semantic DB
  build.sbt
  compiler/src/dotty/tools/dotc/tastyreflect/PositionOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/SymbolOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/PositionOps.scala
  library/src/scala/tasty/reflect/SymbolOps.scala
  library/src/scala/tasty/reflect/TreeUtils.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  project/Build.scala
  semanticdb/input/src/main/scala/example/Access.scala
  semanticdb/input/src/main/scala/example/Advanced.scala
  semanticdb/input/src/main/scala/example/Anonymous.scala
  semanticdb/input/src/main/scala/example/Classes.scala
  semanticdb/input/src/main/scala/example/Empty.scala
  semanticdb/input/src/main/scala/example/EmptyObject.scala
  semanticdb/input/src/main/scala/example/Example.scala
  semanticdb/input/src/main/scala/example/Example2.scala
  semanticdb/input/src/main/scala/example/Exclude.scala
  semanticdb/input/src/main/scala/example/Flags.scala
  semanticdb/input/src/main/scala/example/Imports.scala
  semanticdb/input/src/main/scala/example/Issue1749.scala
  semanticdb/input/src/main/scala/example/Locals.scala
  semanticdb/input/src/main/scala/example/MacroAnnotations.scala
  semanticdb/input/src/main/scala/example/MethodUsages.scala
  semanticdb/input/src/main/scala/example/Methods.scala
  semanticdb/input/src/main/scala/example/Objects.scala
  semanticdb/input/src/main/scala/example/Overrides.scala
  semanticdb/input/src/main/scala/example/Prefixes.scala
  semanticdb/input/src/main/scala/example/Selfs.scala
  semanticdb/input/src/main/scala/example/Synthetic.scala
  semanticdb/input/src/main/scala/example/Traits.scala
  semanticdb/input/src/main/scala/example/Types.scala
  semanticdb/input/src/main/scala/example/Vals.scala
  semanticdb/input/src/main/scala/example/local-file.scala
  semanticdb/src/dotty/semanticdb/Scala.scala
  semanticdb/src/dotty/semanticdb/SemanticdbConsumer.scala
  semanticdb/test/dotty/semanticdb/Semanticdbs.scala
  semanticdb/test/dotty/semanticdb/Tests.scala
Labels: stat:needs review

#5325 Allow tasty files to be the input of -from-tasty
  compiler/src/dotty/tools/dotc/Driver.scala
  compiler/src/dotty/tools/dotc/core/tasty/DottyUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyClassName.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyPrinter.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/fromtasty/TastyFileUtil.scala
Labels: stat:needs review

#5501 Rename TASTy reflect TypeTree.Synthetic to TypeTree.Inferred
  compiler/src/dotty/tools/dotc/tastyreflect/CoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/TreeUtils.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners.check
  tests/run-separate-compilation/i5119.check
  tests/run-separate-compilation/tasty-argument-tree-1.check
  tests/run-separate-compilation/tasty-extractors-1.check
  tests/run-separate-compilation/tasty-extractors-2.check
  tests/run-separate-compilation/tasty-extractors-types.check
  tests/run-with-compiler/tasty-consumer.check
Labels: stat:needs review

#5476 Fix #5460: Improve completion of import nodes
  compiler/src/dotty/tools/dotc/interactive/Completion.scala
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
  language-server/test/dotty/tools/languageserver/util/CodeTester.scala
  language-server/test/dotty/tools/languageserver/util/actions/CodeCompletion.scala
Labels: area:ide

#5504 Add missing TASTy reflect instance checks
  compiler/src/dotty/tools/dotc/tastyreflect/TreeOpsImpl.scala
  library/src/scala/tasty/reflect/TreeOps.scala
Labels: stat:needs review

#5519 Fix link to IDE instructions
  docs/docs/usage/worksheet-mode.md
Labels: area:documentation

#5474 Rename reflect/reify and make them plain methods
  compiler/src/dotty/tools/dotc/tastyreflect/QuotedOpsImpl.scala
  docs/docs/reference/tasty-reflect.md
  library/src/scala/tasty/reflect/QuotedOps.scala
  library/src/scala/tasty/util/ConstantExtractor.scala
  tests/neg/tasty-macro-assert/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-2/Macro_1.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-3/Macro_1.scala
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-1/quoted_1.scala
  tests/run-custom-args/Yretain-trees/tasty-load-tree-2/quoted_1.scala
  tests/run-separate-compilation/gestalt-type-toolbox-reflect/Macro_1.scala
  tests/run-separate-compilation/i5119/Macro_1.scala
  tests/run-separate-compilation/i5119b/Macro_1.scala
  tests/run-separate-compilation/tasty-argument-tree-1/quoted_1.scala
  tests/run-separate-compilation/tasty-custom-show/quoted_1.scala
  tests/run-separate-compilation/tasty-eval/quoted_1.scala
  tests/run-separate-compilation/tasty-extractors-1/quoted_1.scala
  tests/run-separate-compilation/tasty-extractors-2/quoted_1.scala
  tests/run-separate-compilation/tasty-extractors-3/quoted_1.scala
  tests/run-separate-compilation/tasty-extractors-types/quoted_1.scala
  tests/run-separate-compilation/tasty-indexed-map/quoted_1.scala
  tests/run-separate-compilation/tasty-macro-assert/quoted_1.scala
  tests/run-separate-compilation/tasty-macro-const/quoted_1.scala
  tests/run-separate-compilation/tasty-subtyping/quoted_1.scala
  tests/run-separate-compilation/xml-interpolation-1/XmlQuote_1.scala
  tests/run-separate-compilation/xml-interpolation-2/XmlQuote_1.scala
Labels: stat:needs review

#5529 Add missing TASTy Reflect type API
  compiler/src/dotty/tools/dotc/tastyreflect/CoreImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsOpsImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TypeOrBoundsTreesOpsImpl.scala
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/TreeUtils.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
Labels: stat:needs review

#5539 Fix #5533: Check conformance of subtype directly
  compiler/src/dotty/tools/dotc/tastyreflect/QuotedOpsImpl.scala
  library/src/scala/tasty/TastyTypecheckError.scala
  tests/run-separate-compilation/i5533.check
  tests/run-separate-compilation/i5533/Macro_1.scala
  tests/run-separate-compilation/i5533/Test_2.scala
  tests/run-separate-compilation/i5533b.check
  tests/run-separate-compilation/i5533b/Macro_1.scala
  tests/run-separate-compilation/i5533b/Test_2.scala
  tests/run-separate-compilation/i5536/Macro_1.scala
  tests/run-separate-compilation/i5536/Test_2.scala
Labels: stat:needs review

#5443 Small improvements to `workspace/symbol`
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/DocumentSymbolTest.scala
  language-server/test/dotty/tools/languageserver/ReferencesTest.scala
  language-server/test/dotty/tools/languageserver/SymbolTest.scala
Labels: area:ide
