Repository scala/scala3, pull requests merged in 2018-03, with the labels that each got.

#4038 Fix #4023: Ignore healed implicit tag at level 0
  compiler/src/dotty/tools/dotc/interpreter/Interpreter.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  tests/pos/i4023/Macro_1.scala
  tests/pos/i4023/Test_2.scala
  tests/pos/i4023b/Macro_1.scala
  tests/pos/i4023b/Test_2.scala
  tests/pos/i4023c/Macro_1.scala
  tests/pos/i4023c/Test_2.scala
  tests/pos/macro-with-type/Macro_1.scala
  tests/pos/macro-with-type/Test_2.scala
Labels: stat:needs review

#4050 Re-enable from tasty tests
  compiler/test/dotty/tools/dotc/FromTastyTests.scala
Labels: stat:needs review

#4052 Add quote.show tree cleaner
  compiler/src/dotty/tools/dotc/quoted/QuoteDriver.scala
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
  compiler/src/dotty/tools/dotc/quoted/TreeCleaner.scala
  tests/run-with-compiler/i3823-c.check
  tests/run-with-compiler/i3876-b.check
  tests/run-with-compiler/i3876-c.check
  tests/run-with-compiler/i3876.check
  tests/run-with-compiler/quote-run-2.check
  tests/run-with-compiler/quote-run-constants-extract-1.check
  tests/run-with-compiler/quote-run-constants-extract-1.scala
  tests/run-with-compiler/quote-run-constants-extract-2.check
  tests/run-with-compiler/quote-run-constants-extract-2.scala
  tests/run-with-compiler/quote-run-constants-extract-3.check
  tests/run-with-compiler/quote-run-constants-extract-3.scala
  tests/run-with-compiler/quote-run-constants-extract-4.check
  tests/run-with-compiler/quote-run-constants-extract-4.scala
  tests/run-with-compiler/quote-run-constants-extract-5.check
  tests/run-with-compiler/quote-run-constants-extract-5.scala
  tests/run-with-compiler/quote-run-constants-extract-6.check
  tests/run-with-compiler/quote-run-constants-extract-6.scala
  tests/run-with-compiler/quote-run-constants-extract.check
  tests/run-with-compiler/quote-run-staged-interpreter.check
  tests/run-with-compiler/quote-show-blocks-raw.check
  tests/run-with-compiler/quote-show-blocks-raw.scala
  tests/run-with-compiler/quote-show-blocks.check
  tests/run-with-compiler/quote-show-blocks.scala
Labels: stat:needs review

#4053 Blog Post: Announcing Dotty 0.6.0 and 0.7.0-RC1
  docs/blog/_posts/2018-03-05-seventh-dotty-milestone-release.md
Labels: stat:wip

#4087 Remove debug System.out.print
  compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala
Labels: stat:needs review

#4089 Cleanup InterceptedMethods
  compiler/src/dotty/tools/dotc/transform/InterceptedMethods.scala
Labels: stat:needs review

#4090 Remove dead code in FirstTransform
  compiler/src/dotty/tools/dotc/transform/FirstTransform.scala
Labels: stat:needs review

#4094 Mark IsInstanceOfEvaluator as disabled
  compiler/src/dotty/tools/dotc/transform/IsInstanceOfEvaluator.scala.disabled
Labels: stat:needs review

#4095 Mark PatternMatcherOld as disabled
  compiler/src/dotty/tools/dotc/transform/PatternMatcherOld.scala.disabled
Labels: stat:needs review

#4091 Remove dead code in Bridges
  compiler/src/dotty/tools/dotc/transform/Bridges.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
Labels: stat:needs review

#4092 Remove dead code in CapturedVars
  compiler/src/dotty/tools/dotc/transform/CapturedVars.scala
  tests/pos/capturedVars2.scala
Labels: stat:needs review

#4097 Remove unused private method
  compiler/src/dotty/tools/dotc/core/Definitions.scala
Labels: stat:needs review

#4096 Cleanup SymUtils
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
Labels: stat:needs review

#4086 Fix #4073: erase <repeted> type from lifted val for a vararg
  compiler/src/dotty/tools/dotc/core/TypeErasure.scala
  compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala
  tests/Foo.scala
  tests/run/i4073.check
  tests/run/i4073.scala
  tests/run/i4073b.check
  tests/run/i4073b.scala
  tests/run/i4073c.check
  tests/run/i4073c.scala
Labels: stat:needs review

#4093 Add test for #2456
  tests/run/i2456.check
  tests/run/i2456.scala
Labels: stat:needs review

#3967 Restart presentation compilers if memory is low
  compiler/src/dotty/tools/dotc/Run.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/src/dotty/tools/languageserver/Memory.scala
Labels: stat:needs rebase

#4101 Add error reporter for inlined quotes
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  library/src/scala/quoted/QuoteError.scala
  tests/neg/quote-error/Macro_1.scala
  tests/neg/quote-error/Test_2.scala
  tests/neg/quote-exception/Macro_1.scala
  tests/neg/quote-exception/Test_2.scala
Labels: stat:needs review

#4081 Fix #4044: Change quote pickled representation
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/neg/i4044a.scala
  tests/neg/i4044b.scala
  tests/run-with-compiler/i4044a.check
  tests/run-with-compiler/i4044a.scala
  tests/run-with-compiler/i4044b.check
  tests/run-with-compiler/i4044b.scala
  tests/run-with-compiler/i4044c.check
  tests/run-with-compiler/i4044c.scala
  tests/run-with-compiler/i4044d.check
  tests/run-with-compiler/i4044d.scala
  tests/run-with-compiler/i4044e.check
  tests/run-with-compiler/i4044e.scala
  tests/run-with-compiler/i4044f.check
  tests/run-with-compiler/i4044f.scala
  tests/run-with-compiler/quote-lambda.scala
  tests/run-with-compiler/quote-nested-1.check
  tests/run-with-compiler/quote-nested-1.scala
  tests/run-with-compiler/quote-nested-2.check
  tests/run-with-compiler/quote-nested-2.scala
  tests/run-with-compiler/quote-nested-3.check
  tests/run-with-compiler/quote-nested-3.scala
  tests/run-with-compiler/quote-nested-4.check
  tests/run-with-compiler/quote-nested-4.scala
  tests/run-with-compiler/quote-nested-5.check
  tests/run-with-compiler/quote-nested-5.scala
Labels: stat:needs review

#4123 Remove quoted.Liftable for Unit
  library/src/scala/quoted/Liftable.scala
  tests/pos/macro-with-type/Macro_1.scala
  tests/pos/quote-liftable.scala
  tests/run-with-compiler/i3946.scala
  tests/run-with-compiler/quote-show-blocks-raw.scala
  tests/run-with-compiler/quote-show-blocks.scala
Labels: stat:needs review

#4013 Fix #3989: Fix several unsoundness problems related to variant refinement
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Inferencing.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala
  compiler/src/dotty/tools/dotc/util/HashSet.scala
  compiler/test/dotty/tools/dotc/IdempotencyTests.scala
  compiler/test/dotty/tools/dotc/LinkTests.scala
  tests/neg/i1240b.scala
  tests/neg/i3989.scala
  tests/neg/i3989a.scala
  tests/neg/i3989b.scala
  tests/neg/i3989c.scala
  tests/neg/i3989d.scala
  tests/neg/i3989e.scala
  tests/neg/i3989f.scala
  tests/neg/i3989g.scala
  tests/neg/t3272.scala
  tests/neg/t4731.scala
  tests/neg/t7093.scala
  tests/pos-special/strawman-collections/CollectionStrawMan5.scala
  tests/pos-special/strawman-collections/CollectionStrawMan6.scala
  tests/pos/GenericTraversableTemplate.scala
  tests/pos/t3272.scala
  tests/pos/t3880.scala
  tests/pos/t4345.scala
  tests/pos/t6084.scala
  tests/pos/variances-local.scala
  tests/run/CollectionTests.scala
  tests/run/colltest5/CollectionStrawMan5_1.scala
  tests/run/colltest6/CollectionStrawMan6_1.scala
Labels: area:typer

#4116 Fix #3847: Handle correctly splicing of (possibly) nested type parameters
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/run-with-compiler/i3847-b.check
  tests/run-with-compiler/i3847-b.scala
  tests/run-with-compiler/i3847.check
  tests/run-with-compiler/i3847.scala
  tests/run-with-compiler/quote-lib.scala
Labels: stat:needs rebase

#4103 Encode quoted values
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  library/src/scala/quoted/Expr.scala
  library/src/scala/quoted/Liftable.scala
  library/src/scala/runtime/quoted/Unpickler.scala
  tests/run/quote-compile-constants.check
  tests/run/quote-compile-constants.scala
Labels: stat:needs review

#4145 Improve performance of ErasedDecls phase
  bench/scripts/collection-vector.sh
  bench/tests/Vector.scala
  compiler/src/dotty/tools/dotc/transform/ElimByName.scala
  compiler/src/dotty/tools/dotc/transform/ExplicitOuter.scala
  compiler/src/dotty/tools/dotc/transform/FirstTransform.scala
  compiler/src/dotty/tools/dotc/transform/UnusedDecls.scala
Labels: stat:needs review

#4148 Create single argument for each capture
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  tests/run-with-compiler/quote-two-captured-ref.check
  tests/run-with-compiler/quote-two-captured-ref.scala
Labels: stat:needs review

#4149 Avoid pickling '(x) when x is a captured parameter
  Foo.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
Labels: stat:needs review

#4168 Remove empty Foo.scala
  Foo.scala
Labels: stat:needs review

#4120 Fix tests on case-insensitive filesystems
  compiler/src/dotty/tools/backend/jvm/GenBCode.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tests/neg-custom-args/fatal-warnings/i2673b.scala
  tests/neg-custom-args/fatal-warnings/i2673c.scala
  tests/pos-special/i4166.scala
  tests/pos/test4a.scala
  tests/pos/test4refine.scala
Labels: stat:needs review

#4208 Fix #4207: Read whole zipfile before closing
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
Labels: area:ide

#4155 Fix #3853 and #4151: Compile code in the macro definition and remove interpreter
  compiler/src/dotty/tools/dotc/interpreter/Interpreter.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  tests/neg/quote-MacroOverride.scala
  tests/neg/quote-interpolator-core-old.scala
  tests/neg/quote-macro-splice.scala
  tests/neg/quote-non-static-macro.scala
  tests/pos/i3916/Macro_1.scala
  tests/pos/i3916/Test_2.scala
  tests/pos/i4023/Macro_1.scala
  tests/pos/quote-0.scala
  tests/pos/quote-assert/quoted_2.scala
  tests/pos/quote-interpolator-core/quoted_2.scala
  tests/pos/quote-nested-object/Macro_1.scala
  tests/pos/quote-nested-object/Test_2.scala
  tests/run/quote-simple-macro.check
  tests/run/quote-simple-macro/quoted_1.scala
  tests/run/quote-simple-macro/quoted_2.scala
Labels: stat:needs review

#4209 Fix #4127: Fix mods string of FunctionTypeNeedsNonEmptyParameterList
  compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala
Labels: stat:needs review
