Repository scala/scala3, pull requests merged in 2018-06, with the labels that each got.

#4607 Add a way filter FromTasty tests
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
  project/Build.scala
Labels: stat:needs review

#4603 More changes to protected accessors
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/core/NameKinds.scala
  compiler/src/dotty/tools/dotc/core/NameTags.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyFormat.scala
  compiler/src/dotty/tools/dotc/transform/AccessProxies.scala
  compiler/src/dotty/tools/dotc/transform/ProtectedAccessors.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
Labels: stat:needs review

#4547 Add regression test
  tests/run/quote-force.check
  tests/run/quote-force/quoted_1.scala
  tests/run/quote-force/quoted_2.scala
Labels: stat:needs review

#4578 Do not compute PackageDef members in extractor
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  tests/pos/tasty/definitions.scala
Labels: stat:needs review

#4609 Add .show to Tasty.CaseDef
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/Show.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/run/tasty-custom-show/quoted_1.scala
Labels: stat:needs review

#4608 Print top level packages
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/run/simpleClass.decompiled
Labels: stat:needs review

#4605 Fix printing extractors
  compiler/src/dotty/tools/dotc/decompiler/DecompilationPrinter.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/Show.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleExractors.decompiled
  tests/pos/simpleExractors.scala
  tests/run/tasty-custom-show/quoted_1.scala
Labels: stat:needs review

#4584 Fix decompilation of while loops
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/run/quote-inline-function.check
  tests/run/quote-inline-function/quoted_1.scala
  tests/run/quote-inline-function/quoted_2.scala
Labels: stat:needs review

#4637 Fix #4586: Add regression test
  tests/pos/i4586.scala
Labels: stat:needs review

#4633 Fix case class decompilation
  compiler/src/dotty/tools/dotc/tastyreflect/FlagSet.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleCaseClass-1.decompiled
  tests/pos/simpleCaseClass-1.scala
  tests/pos/simpleCaseClass-2.decompiled
  tests/pos/simpleCaseClass-2.scala
  tests/pos/simpleCaseClass-3.decompiled
  tests/pos/simpleCaseClass-3.scala
Labels: stat:needs review

#4644 Escape chars when printing strings in decompiler
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/quoted/Toolbox.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
Labels: stat:needs review

#4642 Fix tasty reflect singletons
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleSingleton.decompiled
  tests/pos/simpleSingleton.scala
Labels: stat:needs review

#4640 Fix tasty reflect pattern binds when typed
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleExtractors-1.decompiled
  tests/pos/simpleExtractors-1.scala
  tests/pos/simpleExtractors-2.decompiled
  tests/pos/simpleExtractors-2.scala
Labels: stat:needs review

#4652 Add missing line break
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleMatchCase.decompiled
  tests/pos/simpleMatchCase.scala
Labels: stat:needs review

#4601 Fix synthetic type bounds in Tasty reflect
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i2104b.decompiled
  tests/pos/i2104b.scala
  tests/pos/tasty/definitions.scala
  tests/run/tasty-extractors-owners.check
Labels: stat:needs review

#4677 Add TypeTree.TypeLambda to Tasty reflect
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i1181.decompiled
  tests/pos/tasty/definitions.scala
Labels: stat:needs review

#4675 Fix Tasty reflect patterns with select trees
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  tests/pos/simpleMatchRef.decompiled
  tests/pos/simpleMatchRef.scala
Labels: stat:needs review

#4676 Print annotation in decompiler
  compiler/test/dotty/tools/dotc/FromTastyTests.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i2104b.decompiled
  tests/pos/simpleAnnot.decompiled
  tests/pos/simpleAnnot.scala
  tests/pos/simpleCaseClass-1.decompiled
  tests/pos/simpleCaseClass-2.decompiled
  tests/pos/simpleCaseClass-3.decompiled
  tests/pos/simpleCaseObject.decompiled
Labels: stat:needs review

#4679 Fix tasty applied type tree on bounds
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/test/dotty/tools/dotc/FromTastyTests.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i1181.decompiled
  tests/pos/i2104b.decompiled
  tests/pos/t0905.decompiled
  tests/pos/tasty/definitions.scala
Labels: stat:needs review

#4681 Add missing annotation shapes
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i1570.decompiled
Labels: stat:needs review

#4656 Add some documentation for tasty reflect
  library/src/scala/tasty/Tasty.scala
Labels: stat:needs review

#4682 Fix type of Tasty.Type.TypeSelect.prefix
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  library/src/scala/tasty/util/TreeAccumulator.scala
  tests/pos/simpleTypeSelect.decompiled
  tests/pos/simpleTypeSelect.scala
  tests/pos/tasty/definitions.scala
  tests/run/tasty-extractors-2.check
Labels: stat:needs review

#4685 Disable tests that timeout easily
  tests/run-with-compiler-custom-args/staged-streams_1.check
  tests/run-with-compiler-custom-args/staged-streams_1.scala
Labels: stat:needs review

#4687 Add Tasty.Constant.ClassTag
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i566.decompiled
Labels: stat:needs review

#4683 Add type bindings in Tasty reflect
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i0306.decompiled
  tests/pos/tasty/definitions.scala
Labels: stat:needs review

#4686 Fix printing parents in decompiler
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i1444.decompiled
  tests/pos/i2104b.decompiled
  tests/pos/simpleAnnot.decompiled
  tests/pos/simpleCaseClass-3.decompiled
  tests/pos/simpleClass-2.decompiled
  tests/pos/simpleClass-3.decompiled
  tests/pos/simpleClass-3.scala
  tests/pos/simpleClass.decompiled
  tests/run/simpleClass.decompiled
Labels: stat:needs review

#4690 Do not print type parameter twice in constructors
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/run-with-compiler/i3847-b.check
Labels: stat:needs review

#4691 Do not print @inline as keyword `inline` is already printed
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleInline.decompiled
  tests/pos/simpleInline.scala
Labels: stat:needs review

#4692 Fix printing `return`
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/t3869.decompiled
Labels: stat:needs review

#4673 Remove tasty.Universe and use tasty.Tasty directly
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/decompiler/DecompilationPrinter.scala
  compiler/src/dotty/tools/dotc/quoted/QuoteDriver.scala
  compiler/src/dotty/tools/dotc/tastyreflect/CompilationUniverse.scala
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/TopLevelSplice.scala
  library/src/scala/tasty/Universe.scala
  library/src/scala/tasty/util/ConstantExtractor.scala
  library/src/scala/tasty/util/ShowExtractors.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  library/src/scala/tasty/util/TreeAccumulator.scala
  library/src/scala/tasty/util/TreeTraverser.scala
  tests/neg/tasty-macro-assert/quoted_1.scala
  tests/run/tasty-custom-show/quoted_1.scala
  tests/run/tasty-eval/quoted_1.scala
  tests/run/tasty-extractors-1/quoted_1.scala
  tests/run/tasty-extractors-2/quoted_1.scala
  tests/run/tasty-extractors-3/quoted_1.scala
  tests/run/tasty-extractors-constants-1/quoted_1.scala
  tests/run/tasty-extractors-constants-2/quoted_1.scala
  tests/run/tasty-extractors-owners/quoted_1.scala
  tests/run/tasty-extractors-types/quoted_1.scala
  tests/run/tasty-indexed-map/quoted_1.scala
  tests/run/tasty-linenumber/quoted_1.scala
  tests/run/tasty-location/quoted_1.scala
  tests/run/tasty-macro-assert/quoted_1.scala
  tests/run/tasty-positioned/quoted_1.scala
Labels: stat:needs review

#4694 Fix printing `catch` clause
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleTry.decompiled
  tests/pos/simpleTry.scala
Labels: stat:needs review

#4695 Fix printing of secondary constructors
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/t116.decompiled
Labels: stat:needs review

#4696 Print self types
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/selftypes.decompiled
Labels: stat:needs review

#4698 Print decompiled refinements
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i2104b.decompiled
  tests/pos/simpleCaseClass-3.decompiled
  tests/pos/simpleRefinement.decompiled
  tests/pos/simpleRefinement.scala
  tests/run-with-compiler/i3876-c.check
Labels: stat:needs review

#4697 Print this id and filter object lazy val
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/i2104b.decompiled
  tests/pos/simpleCaseClass-1.decompiled
  tests/pos/simpleCaseClass-2.decompiled
  tests/pos/simpleCaseClass-3.decompiled
  tests/pos/simpleMatchRef.decompiled
  tests/pos/t704.decompiled
Labels: stat:needs review

#4703 Do not print trailing comma for empty var args
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simple-repeated-args.decompiled
  tests/pos/simple-repeated-args.scala
Labels: stat:needs review

#4699 Fix printing super
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleSuper.decompiled
  tests/pos/simpleSuper.scala
  tests/run/t4300.decompiled
Labels: stat:needs review

#4700 Do not print setters
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/simpleSetter.decompiled
  tests/pos/simpleSetter.scala
Labels: stat:needs review

#4630 Add While and DoWhile extractors Tasty reflect
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/tasty/definitions.scala
Labels: stat:needs review

#4704 Fix printing binded alternatives
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/run/virtpatmat_alts.decompiled
Labels: stat:needs review

#4706 Fix printing package objects and nested packages
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/t6225b.decompiled
  tests/pos/t6225b.scala
Labels: stat:needs review

#4707 Add inParens, inSquareParens and inBlock
  library/src/scala/tasty/util/ShowSourceCode.scala
Labels: stat:needs review

#4627 Add Tasty compilation unit source file
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  library/src/scala/tasty/Tasty.scala
  tests/run/tasty-getfile.check
  tests/run/tasty-getfile/App_2.scala
  tests/run/tasty-getfile/Macro_1.scala
Labels: stat:needs review

#4708 Use new Tasty context format
  tests/run/tasty-getfile/Macro_1.scala
Labels: stat:needs review

#4714 Add tasty reflect members for definitions
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
  compiler/src/dotty/tools/dotc/tastyreflect/package.scala
  library/src/scala/tasty/Tasty.scala
  library/src/scala/tasty/util/ShowSourceCode.scala
  tests/pos/tasty/definitions.scala
Labels: stat:needs review

#4461 Add `Comments` section in TASTY
  compiler/src/dotty/tools/dotc/Driver.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Comments.scala
  compiler/src/dotty/tools/dotc/core/Mode.scala
  compiler/src/dotty/tools/dotc/core/quoted/TastyUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/CommentPickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/CommentUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/DottyUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyFormat.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyPrinter.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  compiler/src/dotty/tools/dotc/transform/Pickler.scala
  compiler/test/dotty/tools/DottyTest.scala
  compiler/test/dotty/tools/dotc/core/tasty/CommentPicklingTest.scala
  compiler/test/dotty/tools/dotc/parsing/DocstringTest.scala
  doc-tool/src/dotty/tools/dottydoc/DocDriver.scala
  doc-tool/test/DottyDocTest.scala
  doc-tool/test/MarkdownTests.scala
Labels: area:docs, area:pickling

#4728 Fix Tasty reflect extractor for flatten closure blocks
  compiler/src/dotty/tools/dotc/tastyreflect/TastyImpl.scala
Labels: stat:needs review

#4648 Show docs in the IDE
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/HoverTest.scala
  language-server/test/dotty/tools/languageserver/util/CodeTester.scala
  language-server/test/dotty/tools/languageserver/util/actions/CodeHover.scala
Labels: area:docs, area:ide, itype:enhancement, itype:question, stat:needs review
