Repository scala/scala3, pull requests merged in 2019-08, with the labels that each got.

#7004 Add constructor for AppliedType
  compiler/src/dotty/tools/dotc/tastyreflect/ReflectionInternal.scala
  library/src/scala/tasty/reflect/CompilerInterface.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
Labels: area:meta-programming

#7039 Adjust example and fix showExtractors note on tasty-reflect doc
  docs/docs/reference/metaprogramming/tasty-reflect.md
Labels: area:documentation

#7035 Add a Var abstraction in QuoteUtils
  compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala
  library/src-bootstrapped/scala/quoted/util/Var.scala
  tests/run-with-compiler/staged-streams_1.check
  tests/run-with-compiler/staged-streams_1.scala
Labels: area:meta-programming

#7063 Add documentation for type class derivation
  docs/docs/reference/contextual/derivation.md
  tests/pos/no-mirror-derives.scala
  tests/run/typeclass-derivation-doc-example.scala
Labels: area:documentation, area:typeclass-derivation

#7091 Fix quoted-example-project sbt test
  sbt-dotty/sbt-test/sbt-dotty/quoted-example-project/src/main/scala/hello/Hello.scala
Labels: prio:high

#7105 Expose Type#simplified via tasty reflect API
  compiler/src/dotty/tools/dotc/tastyreflect/ReflectionCompilerInterface.scala
  library/src/scala/tasty/reflect/CompilerInterface.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  tests/run-macros/tasty-simplified.check
  tests/run-macros/tasty-simplified/quoted_1.scala
  tests/run-macros/tasty-simplified/quoted_2.scala
Labels: area:meta-programming, area:tasty-reflect
