Repository scala/scala3, pull requests merged in 2019-05, with the labels that each got.

#6329 Fix inductive implicits performance regression
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tests/neg-custom-args/i6300.scala
Labels: itype:performance

#6423 Fix negAll tests
  compiler/test/dotty/tools/dotc/CompilationTests.scala
Labels: prio:high

#6511 Add support for negative numeric literal types
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  tests/pos/sip23-negative-literals.scala
Labels: area:parser
