Repository scala/scala3, pull requests merged in 2019-03, with the labels that each got.

#5964 Fix #5962: Add regression test
  tests/pos/i5962.scala
Labels: stat:needs review

#5992 Add blogpost for 0.13.0-RC1 and 0.12.0
  .mailmap
  CHANGELOG.md
  docs/blog/_posts/2019-03-05-13th-dotty-milestone-release.md
  docs/docs/reference/contextual/derivation.md
  docs/docs/reference/contextual/relationship-implicits.md
Labels: itype:meta

#5600 Cleanup tests
  compiler/test/dotc/scala-collections.blacklist
  compiler/test/dotty/tools/TestSources.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  compiler/test/dotty/tools/dotc/IdempotencyTests.scala
  doc-tool/test/dotty/tools/dottydoc/WhitelistedStdLib.scala
Labels: stat:needs review

#5846 Move Staging to Typer
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/Driver.scala
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/core/Flags.scala
  compiler/src/dotty/tools/dotc/core/MacroClassLoader.scala
  compiler/src/dotty/tools/dotc/core/StagingContext.scala
  compiler/src/dotty/tools/dotc/core/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/src/dotty/tools/dotc/transform/Staging.scala
  compiler/src/dotty/tools/dotc/transform/TreeMapWithStages.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/PrepareInlineable.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/src/dotty/tools/repl/ReplCompiler.scala
  tests/neg/quote-this-b.scala
  tests/neg/quote-this.scala
  tests/neg/quote-whitebox/Macro_1.scala
  tests/neg/quote-whitebox/Test_2.scala
  tests/neg/splice-in-top-level-splice-1.scala
  tests/neg/tasty-macro-assert-1/quoted_1.scala
  tests/neg/tasty-macro-assert-1/quoted_2.scala
  tests/neg/tasty-macro-assert-2/quoted_1.scala
  tests/neg/tasty-macro-assert-2/quoted_2.scala
  tests/pending/run/tasty-comments/quoted_1.scala
  tests/pending/run/tasty-comments/quoted_2.scala
  tests/pos/quote-whitebox/Macro_1.scala
  tests/pos/quote-whitebox/Test_2.scala
  tests/pos/quoted-inline-quote.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-3.check
  tests/run-custom-args/Yretain-trees/tasty-extractors-owners.check
  tests/run-custom-args/Yretain-trees/tasty-load-tree-2.check
  tests/run-with-compiler/quote-macro-in-splice.check
  tests/run-with-compiler/quote-macro-in-splice/quoted_1.scala
  tests/run-with-compiler/quote-macro-in-splice/quoted_2.scala
  tests/run/quote-whitebox.check
  tests/run/quote-whitebox/Macro_1.scala
  tests/run/quote-whitebox/Test_2.scala
  tests/run/tasty-argument-tree-1.check
  tests/run/tasty-extractors-1.check
  tests/run/tasty-extractors-2.check
  tests/run/tasty-macro-const/quoted_1.scala
  tests/run/tasty-positioned.check
  tests/run/tasty-positioned/quoted_2.scala
Labels: stat:needs review

#6024 Add macro error reporting
  compiler/src/dotty/tools/dotc/tastyreflect/KernelImpl.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  library/src/scala/tasty/Reflection.scala
  library/src/scala/tasty/reflect/Kernel.scala
  library/src/scala/tasty/reflect/ReportingOps.scala
  tests/neg/tasty-macro-error.check
  tests/neg/tasty-macro-error/quoted_1.scala
  tests/neg/tasty-macro-error/quoted_2.scala
Labels: stat:needs review

#6044 Fix the test for error messages
  tests/neg/tasty-macro-error.check
  tests/neg/tasty-macro-error/quoted_1.scala
  tests/neg/tasty-macro-error/quoted_2.scala
  tests/run/tasty-macro-positions.check
  tests/run/tasty-macro-positions/quoted_1.scala
  tests/run/tasty-macro-positions/quoted_2.scala
Labels: fasttrack, prio:blocker, stat:needs review

#5988 Fix #5965: Make scala.quoted.Type poly-kinded
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  docs/docs/reference/other-new-features/kind-polymorphism.md
  library/src-bootstrapped/scala/quoted/Type.scala
  library/src-bootstrapped/scala/tasty/reflect/QuotedOps.scala
  library/src-non-bootstrapped/scala/quoted/Type.scala
  library/src-non-bootstrapped/scala/tasty/reflect/QuotedOps.scala
  tests/neg-no-kind-polymorphism/anykind.scala
  tests/neg/anykind.scala
  tests/neg/anykind1.scala
  tests/neg/anykind2.scala
  tests/neg/anykind3.scala
  tests/neg/anykind4.scala
  tests/pos/anykind.scala
  tests/pos/kindPolySemiGroup.scala
  tests/run-with-compiler/i5965.check
  tests/run-with-compiler/i5965.scala
  tests/run-with-compiler/i5965b.check
  tests/run-with-compiler/i5965b.scala
Labels: stat:needs review

#6065 Fix #5629: Add regression test
  tests/run/i5629/Macro_1.scala
  tests/run/i5629/Test_2.scala
Labels: stat:needs review

#6053 TASTy reflect join Tree, TypeTree, CaseDef and TypeCaseDef
  compiler/src/dotty/tools/dotc/tastyreflect/KernelImpl.scala
  docs/docs/reference/other-new-features/tasty-reflect.md
  library/src/scala/tasty/Reflection.scala
  library/src/scala/tasty/reflect/CaseDefOps.scala
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/Kernel.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TreeUtils.scala
  library/src/scala/tasty/reflect/TypeOrBoundsTreeOps.scala
  semanticdb/src/dotty/semanticdb/SemanticdbConsumer.scala
  tests/pos-special/fatal-warnings/tasty-parent-unapply.scala
  tests/run/tasty-custom-show/quoted_1.scala
  tests/run/tasty-extractors-3/quoted_1.scala
Labels: stat:needs review

#6046 Move quoted.{Expr|Type}.apply to scala.internal
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/printing/DecompilerPrinter.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  library/src-bootstrapped/scala/internal/Quoted.scala
  library/src-bootstrapped/scala/quoted/Type.scala
  library/src-non-bootstrapped/scala/internal/Quoted.scala
  library/src-non-bootstrapped/scala/quoted/Type.scala
  library/src/scala/quoted/Expr.scala
  library/src/scala/tasty/reflect/Printers.scala
  tests/run-with-compiler/quote-nested-1.check
  tests/run-with-compiler/quote-nested-2.check
  tests/run-with-compiler/quote-nested-4.check
  tests/run-with-compiler/quote-nested-5.check
Labels: stat:needs review

#6093 Cancel quotes/splice early
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg-custom-args/fatal-warnings/quote-simple-hole.scala
  tests/run-with-compiler/quote-nested-2.check
  tests/run-with-compiler/quote-nested-5.check
Labels: stat:needs review

#6086 Avoid leaking ReflectImpl/KenelImpl in the compiler
  compiler/src/dotty/tools/dotc/consumetasty/TastyConsumerPhase.scala
  compiler/src/dotty/tools/dotc/decompiler/DecompilationPrinter.scala
  compiler/src/dotty/tools/dotc/decompiler/IDEDecompilerDriver.scala
  compiler/src/dotty/tools/dotc/quoted/QuoteDriver.scala
  compiler/src/dotty/tools/dotc/tastyreflect/ReflectionImpl.scala
Labels: stat:needs review

#6066 Use argument span for inlined singleton an type arguments
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  tests/disabled/run/i4947a.scala
  tests/run/i4947a2.check
  tests/run/i4947a2.scala
  tests/run/tasty-macro-positions.check
  tests/run/tasty-macro-positions/quoted_2.scala
Labels: stat:needs review

#6112 Add TASYTy Reflect type dealias
  compiler/src/dotty/tools/dotc/tastyreflect/KernelImpl.scala
  library/src/scala/tasty/reflect/Kernel.scala
  library/src/scala/tasty/reflect/TypeOrBoundsOps.scala
  tests/run/tasty-dealias.check
  tests/run/tasty-dealias/quoted_1.scala
  tests/run/tasty-dealias/quoted_2.scala
Labels: stat:needs review

#6113 Print missing package prefixes
  library/src/scala/tasty/reflect/Printers.scala
  tests/pos/simpleExtractors-1.decompiled
  tests/pos/varargs-position.decompiled
  tests/run-with-compiler/i3947.check
  tests/run-with-compiler/i3947c.check
  tests/run-with-compiler/i3947e.check
  tests/run-with-compiler/i3947f.check
  tests/run-with-compiler/i5965.check
  tests/run-with-compiler/i5965b.check
  tests/run-with-compiler/quote-owners-2.check
  tests/run/t4300.decompiled
  tests/run/t8100.decompiled
  tests/run/t889.decompiled
  tests/run/tasty-dealias.check
  tests/run/tasty-typeof.check
Labels: stat:needs review

#6121 Fix #6015: Transform inner missing trees
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  tests/pos/i6015.scala
Labels: stat:needs review

#6123 Fix #5110: Add regression tests
  tests/run/i5110/quoted_1.scala
  tests/run/i5110/quoted_2.scala
  tests/run/quote-elide-prefix/quoted_1.scala
  tests/run/quote-elide-prefix/quoted_2.scala
Labels: stat:needs review

#6073 Remove splice internal representation from public API
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Staging.scala
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/src/dotty/tools/dotc/transform/TreeMapWithStages.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/PrepareInlineable.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  library/src-bootstrapped/scala/StagedTuple.scala
  library/src-bootstrapped/scala/internal/Quoted.scala
  library/src-non-bootstrapped/scala/internal/Quoted.scala
  library/src/scala/quoted/Expr.scala
  tests/disabled/pos/quote-whitebox/Macro_1.scala
  tests/disabled/pos/quote-whitebox/Test_2.scala
  tests/pos/i4774f.scala
  tests/pos/quote-nested.scala
  tests/pos/quote-whitebox-2/Macro_1.scala
  tests/pos/quote-whitebox-2/Test_2.scala
  tests/run/quote-unrolled-foreach/quoted_1.scala
Labels: stat:needs review

#6122 Add inlined invariant assertions and fixes
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/core/Contexts.scala
  compiler/src/dotty/tools/dotc/core/Phases.scala
  compiler/src/dotty/tools/dotc/transform/PCPCheckAndHeal.scala
  compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Staging.scala
  compiler/src/dotty/tools/dotc/transform/TreeMapWithStages.scala
  compiler/src/dotty/tools/dotc/transform/YCheckPositions.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  tests/run/i4803/App_2.scala
Labels: stat:needs review

#6165 Add missing TASTy reflect ImplicitMatch
  compiler/src/dotty/tools/dotc/tastyreflect/KernelImpl.scala
  compiler/test/dotc/pos-from-tasty.blacklist
  compiler/test/dotc/run-from-tasty.blacklist
  docs/docs/reference/other-new-features/tasty-reflect.md
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/Kernel.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/TreeOps.scala
Labels: stat:needs review

#6139 Fix #6009: Emit error when erased is inside the parameter list
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  docs/docs/reference/other-new-features/erased-terms.md
  tests/neg/i6009.scala
  tests/pos/i6009a.scala
  tests/pos/i6009b.scala
  tests/pos/i6009c.scala
Labels: stat:needs review

#6174 Add String interpolation position regression test
  tests/neg/tasty-string-interpolator-position-a.check
  tests/neg/tasty-string-interpolator-position-a/Macro_1.scala
  tests/neg/tasty-string-interpolator-position-a/Test_2.scala
  tests/neg/tasty-string-interpolator-position-b.check
  tests/neg/tasty-string-interpolator-position-b/Macro_1.scala
  tests/neg/tasty-string-interpolator-position-b/Test_2.scala
Labels: stat:needs review

#6175 Add typeChecks to the library
  library/src-bootstrapped/scala/testing/typeChecks.scala
  tests/run-with-compiler/scala-tests-typeChecks.scala
Labels: stat:needs review

#6177 Fix #5715: Make sure the val has a RHS
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  tests/run-with-compiler/i5715/Macro_1.scala
  tests/run-with-compiler/i5715/Test_2.scala
Labels: stat:needs review

#6180 Refactor MapUnderlying and add docs
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  tests/run/tasty-argument-tree-1.check
  tests/run/tasty-argument-tree-1/quoted_2.scala
Labels: stat:needs review

#6184 Fix #5906: Add testCompilation --help
  docs/docs/contributing/testing.md
  project/Build.scala
Labels: stat:needs review

#6084 Implement creator applications
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/core/Constraint.scala
  compiler/src/dotty/tools/dotc/core/NameOps.scala
  compiler/src/dotty/tools/dotc/core/OrderingConstraint.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/core/TyperState.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/reporting/Reporter.scala
  compiler/src/dotty/tools/dotc/reporting/StoreReporter.scala
  compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala
  compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala
  compiler/src/dotty/tools/dotc/transform/MacroTransform.scala
  compiler/src/dotty/tools/dotc/transform/MegaPhase.scala
  compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  compiler/src/dotty/tools/dotc/typer/ReTyper.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/docs/reference/features-classification.md
  docs/docs/reference/other-new-features/creator-applications.md
  docs/sidebar.yml
  tests/neg/creator-applys.scala
  tests/neg/i1648.scala
  tests/pos/concats.scala
  tests/run/creator-applys.scala
Labels: stat:needs review

#6182 Fix #5997: Add missing parentheses
  compiler/test/dotc/pos-recompilation.whitelist
  library/src/scala/tasty/reflect/Printers.scala
  tests/pos/i5997.decompiled
  tests/pos/i5997.scala
  tests/run-with-compiler/i5997.check
  tests/run-with-compiler/i5997.scala
Labels: stat:needs review

#6191 Remove ambiguities from TASTy reflect interface
  compiler/src/dotty/tools/dotc/tastyreflect/KernelImpl.scala
  docs/docs/reference/other-new-features/tasty-reflect.md
  library/src/scala/tasty/reflect/Core.scala
  library/src/scala/tasty/reflect/Kernel.scala
  library/src/scala/tasty/reflect/Printers.scala
  library/src/scala/tasty/reflect/TreeOps.scala
  library/src/scala/tasty/reflect/TreeUtils.scala
  semanticdb/src/dotty/semanticdb/SemanticdbConsumer.scala
  tests/run-custom-args/Yretain-trees/tasty-definitions-2.check
  tests/run-custom-args/Yretain-trees/tasty-load-tree-1.check
  tests/run-with-compiler/tasty-consumer.check
  tests/run/i5119.check
  tests/run/tasty-argument-tree-1.check
  tests/run/tasty-extractors-1.check
  tests/run/tasty-extractors-2.check
Labels: stat:needs review
