Repository scala/scala3, pull requests merged in 2019-02, with the labels that each got.

#5830 Fix #5827: Don't copy protected flag to apply method of case class
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  tests/pos/i5827.scala
Labels: fasttrack

#5849 Fix #4453: Avoid adding type bindings in getVariables
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  tests/neg/i4453.scala
Labels: stat:needs review

#5861 Disable test
  tests/pending/neg/i4371b.scala
Labels: fasttrack, stat:needs review

#5845 Fix #5036: Add missing implementation for setters of Unit
  compiler/src/dotty/tools/dotc/transform/Memoize.scala
  tests/pos/AE-23b20eba14de058f02b69cb1093063fe12b639fb.scala
  tests/pos/i5036.scala
Labels: fasttrack, stat:needs review

#5864 Fix #5855: Print `given` for contextual function types
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/test-resources/repl/defs
Labels: fasttrack, stat:needs review

#5884 Sharpen a type in Inliner
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
Labels: fasttrack

#5870 Add sourceCode to TASTy reflect Position
  compiler/src/dotty/tools/dotc/tastyreflect/PositionOpsImpl.scala
  library/src/scala/tasty/reflect/PositionOps.scala
  tests/run/tasty-original-source.check
  tests/run/tasty-original-source/Macros_1.scala
  tests/run/tasty-original-source/Test_2.scala
Labels: stat:needs review

#5911 Fix --update-checkfiles
  compiler/test/dotty/Properties.scala
  project/Build.scala
Labels: fasttrack, prio:high, stat:needs review

#5788 Add a more complex macro to test more APIs
  tests/run-with-compiler/reflect-select-copy/assert_1.scala
  tests/run-with-compiler/reflect-select-copy/test_2.scala
Labels: area:meta-programming

#5883 Fix the source of inlined trees after Erasure
  compiler/src/dotty/tools/dotc/Driver.scala
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
Labels: stat:needs review

#5921 Fix cache invalidation of compiler instance
  project/Build.scala
Labels: itype:bug, prio:blocker

#5892 Make sure the span of EmptyTree and EmptyValDef are never set
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/transform/Staging.scala
Labels: stat:needs review

#5926 Fix #5823: better erasure of bottom types
  compiler/src/dotty/tools/dotc/core/TypeErasure.scala
  tests/neg/i5823.scala
  tests/run/i5823.check
  tests/run/i5823.scala
Labels: stat:needs review

#5927 IDE: fix signature help for Java and Scala 2 methods
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/util/Signatures.scala
  language-server/test/dotty/tools/languageserver/SignatureHelpTest.scala
Labels: prio:blocker

#5075 Fix #5067: handle scrutinee of bottom type in pattern matcher
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala
  tests/run/i5067.check
  tests/run/i5067.scala
  tests/run/i5067b.check
  tests/run/i5067b.scala
Labels: stat:needs review

#5917 Fix #5916: Fix broken SemanticDB and add it to yml file for CI
  .drone.yml
  compiler/src/dotty/tools/backend/jvm/AsmUtils.scala
  compiler/src/dotty/tools/backend/jvm/BCodeHelpers.scala
  compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala
  compiler/src/dotty/tools/backend/jvm/BytecodeWriters.scala
  compiler/src/dotty/tools/backend/jvm/ClassNode1.java
  compiler/src/dotty/tools/backend/jvm/GenBCode.scala
  compiler/src/dotty/tools/backend/jvm/LabelNode1.java
  compiler/src/dotty/tools/backend/jvm/MethodNode1.java
  project/Build.scala
  semanticdb/src/dotty/semanticdb/SemanticdbConsumer.scala
Labels: stat:needs info, stat:wip

#5887 Change Implicit Resolution Rules
  compiler/src/dotty/tools/dotc/core/Mode.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/package-implicit/ActorRef.scala
  tests/neg/package-implicit/DataFlow.scala
  tests/neg/package-implicit/package.scala
  tests/new/package-implicit/DataFlow.scala
  tests/pos/implicit-shadowing.scala
  tests/run/i5224.check
  tests/run/i5224.scala
  tests/run/implicit-disambiguation.check
  tests/run/implicit-disambiguation.scala
Labels: stat:needs review

#5953 Add missing position to pattern constructors
  compiler/src/dotty/tools/dotc/tastyreflect/PatternOpsImpl.scala
Labels: stat:needs review

#5961 Fix #5954: Do not check prefix for non locally defined types
  compiler/src/dotty/tools/dotc/transform/Staging.scala
  tests/neg/i5954.scala
  tests/pos/i5954.scala
Labels: stat:needs review
