Repository scala/scala3, pull requests merged in 2020-02, with the labels that each got.

#8164 Fix nightly build for TASTy Inspector
  sbt-dotty/sbt-test/sbt-dotty/tasty-inspector-example-project/app/Main.scala
Labels: prio:high

#8225 Fix #8218: Add missing TASTy Inspector dependency in dist/pack
  dist/bin/common
  dist/bin/dotc
  dist/bin/dotd
  dist/bin/dotr
  project/Build.scala
Labels: stat:do not merge

#8279 Fix issue #8124
  compiler/src/dotty/tools/dotc/config/Settings.scala
  compiler/test/dotty/tools/dotc/SettingsTests.scala
  doc-tool/test/dotty/tools/dottydoc/SettingsTests.scala
Labels: area:doctool, area:testing, area:tooling

#8274 Fix FileSystemException in AbstractFileTest.scala
  compiler/test/dotty/tools/io/AbstractFileTest.scala
Labels: area:testing

#8341 Fix #8333: Check for duplicate symbols in exports
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  tests/neg/i8333.scala
Labels: fasttrack
