Repository scala/scala3, pull requests merged in 2020-12, with the labels that each got.

#10572 Improve documentation of Unliftable
  library/src-bootstrapped/scala/quoted/Unliftable.scala
  library/src/scala/quoted/Const.scala
  library/src/scala/quoted/Consts.scala
  library/src/scala/quoted/Unlifted.scala
Labels: prio:blocker

#10675 Remove `Expr.StringContext.unapply`
  library/src-bootstrapped/scala/quoted/Expr.scala
Labels: release-notes

#10708 Remove `scalaShadowing` from the compiler
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/Denotations.scala
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala
  compiler/test/dotty/tools/dotc/MissingCoreLibTests.scala
  library/src-non-bootstrapped/scalaShadowing/D_u_m_m_y.scala
Labels: M3:high-prio

#10720 Rename Not to NotGiven to make its purpose clearer
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  docs/docs/reference/contextual/givens.md
  library/src/scala/util/NotGiven.scala
  tests/neg-macros/i9972/Macro_1.scala
  tests/neg-macros/i9972b/Macro_1.scala
  tests/neg/i5234a.scala
  tests/neg/i5234b.scala
  tests/neg/i5234c.scala
  tests/run/i3396.scala
Labels: release-notes

#10655 Clean up settings
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Contexts.scala
  compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  compiler/test/dotty/tools/dotc/semanticdb/SemanticdbTests.scala
  compiler/test/dotty/tools/vulpix/TestConfiguration.scala
  docs/docs/contributing/testing.md
  staging/src/scala/quoted/staging/QuoteDriver.scala
  staging/src/scala/quoted/staging/Toolbox.scala
Labels: release-notes

#10706 Remove DottyPredef
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/typer/ImportInfo.scala
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
  library/src-non-bootstrapped/dotty/DottyPredef.scala
  tests/neg/implicitDefs.scala
  tests/neg/nopredef.scala
  tests/neg/rootImplicits.scala
  tests/pos/depfuntype.scala
  tests/pos/i6384.scala
  tests/run-custom-args/tuple-cons.scala
  tests/run-staging/i7897.scala
  tests/run-staging/i8178.scala
  tests/run/tuple-accessors.scala
  tests/run/tuple-underscore-syntax.scala
Labels: M3:high-prio

#10735 Add reflect `MatchCase` `TypeRepr`
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  library/src/scala/quoted/Quotes.scala
  scala3doc/src/dotty/dokka/tasty/SyntheticSupport.scala
  scala3doc/src/dotty/dokka/tasty/TypesSupport.scala
  tests/run-macros/tasty-construct-types/Macro_1.scala
Labels: M3:high-prio, release-notes

#10607 [sbt-bridge] Bump Zinc to 1.4.3 and upgrade to CompilerInterface2
  bench/src/main/scala/Benchmarks.scala
  compiler/src/dotty/tools/dotc/Bench.scala
  compiler/src/dotty/tools/dotc/Driver.scala
  compiler/src/dotty/tools/dotc/Resident.scala
  compiler/src/dotty/tools/dotc/Run.scala
  compiler/src/dotty/tools/dotc/config/CompilerCommand.scala
  compiler/src/dotty/tools/dotc/core/Contexts.scala
  compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala
  compiler/src/dotty/tools/dotc/decompiler/IDEDecompilerDriver.scala
  compiler/src/dotty/tools/dotc/decompiler/Main.scala
  compiler/src/dotty/tools/dotc/fromtasty/TASTYRun.scala
  compiler/src/dotty/tools/dotc/fromtasty/TastyFileUtil.scala
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
  doc-tool/src/dotty/tools/dottydoc/DocDriver.scala
  doc-tool/test/dotty/tools/dottydoc/ConstructorTest.scala
  doc-tool/test/dotty/tools/dottydoc/DottyDocTest.scala
  doc-tool/test/dotty/tools/dottydoc/PackageStructure.scala
  doc-tool/test/dotty/tools/dottydoc/SimpleComments.scala
  doc-tool/test/dotty/tools/dottydoc/UsecaseTest.scala
  language-server/src/dotty/tools/languageserver/decompiler/TastyDecompilerService.scala
  project/Build.scala
  project/Dependencies.scala
  project/build.sbt
  sbt-bridge/resources/META-INF/services/xsbti.compile.CompilerInterface2
  sbt-bridge/src/dotty/tools/xsbt/CompilerBridge.java
  sbt-bridge/src/dotty/tools/xsbt/CompilerBridgeDriver.java
  sbt-bridge/src/dotty/tools/xsbt/DelegatingReporter.java
  sbt-bridge/src/dotty/tools/xsbt/InterfaceCompileFailed.java
  sbt-bridge/src/dotty/tools/xsbt/PositionBridge.java
  sbt-bridge/src/dotty/tools/xsbt/Problem.java
  sbt-bridge/src/dotty/tools/xsbt/ZincPlainFile.java
  sbt-bridge/src/dotty/tools/xsbt/ZincVirtualFile.java
  sbt-bridge/src/xsbt/CachedCompilerImpl.java
  sbt-bridge/src/xsbt/CompilerInterface.java
  sbt-bridge/src/xsbt/DelegatingReporter.java
  sbt-bridge/src/xsbt/DottydocRunner.java
  sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala
Labels: M3:high-prio

#10767 [docs/reference] fixed many issues in MarkDown files
  docs/docs/reference/changed-features/compiler-plugins.md
  docs/docs/reference/changed-features/implicit-resolution.md
  docs/docs/reference/changed-features/interpolation-escapes.md
  docs/docs/reference/changed-features/match-syntax.md
  docs/docs/reference/changed-features/numeric-literals.md
  docs/docs/reference/changed-features/operators.md
  docs/docs/reference/changed-features/overload-resolution.md
  docs/docs/reference/changed-features/pattern-bindings.md
  docs/docs/reference/changed-features/pattern-matching.md
  docs/docs/reference/changed-features/structural-types.md
  docs/docs/reference/contextual/extension-methods.md
  docs/docs/reference/contextual/given-imports.md
  docs/docs/reference/contextual/givens.md
  docs/docs/reference/contextual/motivation.md
  docs/docs/reference/contextual/type-classes.md
  docs/docs/reference/contextual/using-clauses.md
  docs/docs/reference/dropped-features/class-shadowing.md
  docs/docs/reference/dropped-features/delayed-init.md
  docs/docs/reference/dropped-features/do-while.md
  docs/docs/reference/dropped-features/early-initializers.md
  docs/docs/reference/dropped-features/existential-types.md
  docs/docs/reference/dropped-features/limit22.md
  docs/docs/reference/dropped-features/macros.md
  docs/docs/reference/dropped-features/nonlocal-returns.md
  docs/docs/reference/dropped-features/procedure-syntax.md
  docs/docs/reference/dropped-features/symlits.md
  docs/docs/reference/dropped-features/this-qualifier.md
  docs/docs/reference/dropped-features/type-projection.md
  docs/docs/reference/dropped-features/weak-conformance.md
  docs/docs/reference/dropped-features/xml.md
  docs/docs/reference/enums/adts.md
  docs/docs/reference/enums/desugarEnums.md
  docs/docs/reference/features-classification.md
  docs/docs/reference/metaprogramming/erased-terms.md
  docs/docs/reference/metaprogramming/inline.md
  docs/docs/reference/metaprogramming/macros-spec.md
  docs/docs/reference/metaprogramming/macros.md
  docs/docs/reference/metaprogramming/toc.md
  docs/docs/reference/other-new-features/explicit-nulls.md
  docs/docs/reference/other-new-features/indentation.md
  docs/docs/reference/overview.md
  docs/docs/reference/soft-modifier.md
  docs/docs/reference/syntax.md
Labels: area:documentation

#10670 Add Matchable trait
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/Mode.scala
  compiler/src/dotty/tools/dotc/core/OrderingConstraint.scala
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  docs/docs/reference/other-new-features/matchable.md
  docs/sidebar.yml
  library/src/scala/quoted/Quotes.scala
  scala3doc/test/dotty/dokka/diagram/HierarchyTest.scala
  tests/neg-custom-args/i7314.scala
  tests/neg-custom-args/matchable.scala
  tests/neg/extend-matchable.scala
  tests/new/test.scala
  tests/pos-special/fatal-warnings/matchable-same-type.scala
  tests/pos-special/fatal-warnings/type-test-matchable.scala
  tests/pos/i1044.scala
  tests/run-macros/i8514.check
  tests/run-macros/i8514b.check
  tests/run/matchable.check
  tests/run/matchable.scala
Labels: M3:high-prio

#10801 Fix JSR-45 repositioning
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  tests/run/assert-stack.check
  tests/run/assert-stack.scala
Labels: M3:high-prio

#10860 [docs/reference] more fixes in Markdown files
  docs/docs/reference/contextual/by-name-context-parameters.md
  docs/docs/reference/contextual/conversions.md
  docs/docs/reference/contextual/relationship-implicits.md
  docs/docs/reference/dropped-features/package-objects.md
  docs/docs/reference/features-classification.md
  docs/docs/reference/metaprogramming/inline.md
  docs/docs/reference/metaprogramming/macros-spec.md
  docs/docs/reference/new-types/dependent-function-types-spec.md
  docs/docs/reference/new-types/type-lambdas-spec.md
  docs/docs/reference/other-new-features/export.md
  docs/docs/reference/other-new-features/indentation.md
  docs/docs/reference/other-new-features/matchable.md
  docs/docs/reference/other-new-features/opaques-details.md
  docs/docs/reference/other-new-features/transparent-traits.md
  docs/docs/reference/overview.md
Labels: area:documentation

#10875 [docs/reference] more fixes in Markdown files
  docs/docs/reference/changed-features/implicit-conversions-spec.md
  docs/docs/reference/changed-features/operators.md
  docs/docs/reference/changed-features/structural-types-spec.md
  docs/docs/reference/changed-features/structural-types.md
  docs/docs/reference/changed-features/vararg-patterns.md
  docs/docs/reference/contextual/derivation-macro.md
  docs/docs/reference/contextual/derivation.md
  docs/docs/reference/contextual/given-imports.md
  docs/docs/reference/contextual/motivation.md
  docs/docs/reference/contextual/multiversal-equality.md
  docs/docs/reference/contextual/relationship-implicits.md
  docs/docs/reference/enums/desugarEnums.md
  docs/docs/reference/enums/enums.md
  docs/docs/reference/features-classification.md
  docs/docs/reference/metaprogramming/erased-terms-spec.md
  docs/docs/reference/metaprogramming/inline.md
  docs/docs/reference/metaprogramming/macros-spec.md
  docs/docs/reference/metaprogramming/macros.md
  docs/docs/reference/metaprogramming/simple-smp.md
  docs/docs/reference/metaprogramming/staging.md
  docs/docs/reference/new-types/dependent-function-types.md
  docs/docs/reference/new-types/match-types.md
  docs/docs/reference/new-types/polymorphic-function-types.md
  docs/docs/reference/new-types/union-types-spec.md
  docs/docs/reference/new-types/union-types.md
  docs/docs/reference/other-new-features/creator-applications.md
  docs/docs/reference/other-new-features/export.md
  docs/docs/reference/other-new-features/open-classes.md
  docs/docs/reference/other-new-features/safe-initialization.md
  docs/docs/reference/other-new-features/targetName.md
  docs/docs/reference/other-new-features/trait-parameters.md
  docs/docs/reference/other-new-features/transparent-traits.md
  docs/docs/reference/overview.md
  docs/docs/reference/syntax.md
Labels: area:documentation
