Repository scala/scala3, pull requests merged in 2020-03, with the labels that each got.

#8414 Give reasonable error messages when classfiles are not found
  compiler/src/dotty/tools/dotc/core/Denotations.scala
  compiler/src/dotty/tools/dotc/core/TypeErrors.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/reporting/diagnostic/Message.scala
  tests/neg/i6501.scala
  tests/neg/i8405.scala
Labels: fasttrack

#8318 Add extension instances
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/core/Flags.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/src/dotty/tools/dotc/typer/ImportSuggestions.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/Nullables.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotty/tools/dotc/reporting/ErrorMessagesTests.scala
  docs/docs/internals/syntax.md
  docs/docs/reference/contextual/extension-methods.md
  tests/neg/extension-cannot-have-type.check
  tests/neg/extension-method-not-allowed.check
  tests/neg/extensions-can-only-have-defs.check
  tests/neg/i6900.scala
  tests/pos/reference/extension-methods.scala
  tests/run/collective-extensions.scala
  tests/run/extmethod-overload.scala
  tests/run/instances.scala
Labels: fasttrack

#8445 Fix #6601: Check that an enum case extends its enum class
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  docs/docs/internals/syntax.md
  docs/docs/reference/enums/desugarEnums.md
  tests/neg/i6601.scala
Labels: fasttrack

#8456 Fix #5309: Fix subtyping tests on constant types
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  tests/pos/i5309.scala
Labels: fasttrack

#8453 Fix #6336: Error on implicit conversions to AnyVal or AnyRef
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i6336.scala
  tests/pos/implicit-anyval-2.10.scala
Labels: fasttrack

#8459 Fix #5492: Inline accesses to private package members
  compiler/src/dotty/tools/dotc/transform/AccessProxies.scala
  tests/pos/i5492.scala
Labels: fasttrack

#8586 Update reference compiler
  library/src-non-bootstrapped/scala/internal/quoted/CompileTime.scala
  library/src/scala/internal/quoted/CompileTime.scala
  project/Build.scala
Labels: stat:do not merge

#8614 Fix #8598: Refinements cannot have default arguments
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  tests/neg/default-arg-in-refinement.scala
Labels: fasttrack

#8616 Fix #8606: Tweak newline insertion criterion
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  tests/pos/i8606.scala
Labels: fasttrack

#8624 Remove variants of METHODtype tasty tag
  compiler/src/dotty/tools/dotc/core/tasty/TastyPrinter.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  tasty/src/dotty/tools/tasty/TastyFormat.scala
Labels: area:tasty-format
