Repository scala/scala3, pull requests merged in 2021-01, with the labels that each got.

#10953 [docs/reference] more fixes in Markdown files
  docs/docs/reference/changed-features/eta-expansion-spec.md
  docs/docs/reference/changed-features/implicit-conversions-spec.md
  docs/docs/reference/changed-features/main-functions.md
  docs/docs/reference/changed-features/match-syntax.md
  docs/docs/reference/changed-features/numeric-literals.md
  docs/docs/reference/changed-features/operators.md
  docs/docs/reference/changed-features/structural-types-spec.md
  docs/docs/reference/changed-features/structural-types.md
  docs/docs/reference/changed-features/type-checking.md
  docs/docs/reference/changed-features/type-inference.md
  docs/docs/reference/changed-features/wildcards.md
  docs/docs/reference/contextual/by-name-context-parameters.md
  docs/docs/reference/contextual/context-functions-spec.md
  docs/docs/reference/contextual/context-functions.md
  docs/docs/reference/contextual/derivation.md
  docs/docs/reference/contextual/extension-methods.md
  docs/docs/reference/contextual/givens.md
  docs/docs/reference/contextual/relationship-implicits.md
  docs/docs/reference/contextual/using-clauses.md
  docs/docs/reference/dropped-features/auto-apply.md
  docs/docs/reference/dropped-features/class-shadowing.md
  docs/docs/reference/dropped-features/delayed-init.md
  docs/docs/reference/dropped-features/macros.md
  docs/docs/reference/dropped-features/nonlocal-returns.md
  docs/docs/reference/enums/adts.md
  docs/docs/reference/enums/enums.md
  docs/docs/reference/features-classification.md
  docs/docs/reference/metaprogramming/inline.md
  docs/docs/reference/metaprogramming/macros.md
  docs/docs/reference/metaprogramming/tasty-inspect.md
  docs/docs/reference/new-types/dependent-function-types-spec.md
  docs/docs/reference/new-types/dependent-function-types.md
  docs/docs/reference/new-types/intersection-types-spec.md
  docs/docs/reference/new-types/polymorphic-function-types.md
  docs/docs/reference/new-types/union-types-spec.md
  docs/docs/reference/other-new-features/explicit-nulls.md
  docs/docs/reference/other-new-features/export.md
  docs/docs/reference/other-new-features/indentation.md
  docs/docs/reference/other-new-features/opaques-details.md
  docs/docs/reference/other-new-features/parameter-untupling-spec.md
  docs/docs/reference/other-new-features/parameter-untupling.md
  docs/docs/reference/other-new-features/trait-parameters.md
  docs/docs/reference/overview.md
  docs/docs/reference/syntax.md
Labels: area:documentation

#11010 Avoid stackoverflow in associatedFile computation
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  tests/neg/i9327.scala
Labels: fasttrack

#11007 Check for unimplemented abstract override members
  compiler/src/dotty/tools/dotc/core/Flags.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  tests/neg/i9329.check
  tests/neg/i9329.scala
Labels: fasttrack

#11011 Avoid more crashes in the presence of cyclic definitions
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i9299.scala
  tests/neg/i9299a.scala
Labels: fasttrack

#11013 Disallow type lambdas as F-bounds
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  tests/neg/i8752.check
  tests/neg/i8752.scala
Labels: fasttrack

#11016 [docs/reference] more fixes in Markdown files
  docs/docs/reference/changed-features/eta-expansion-spec.md
  docs/docs/reference/changed-features/implicit-conversions-spec.md
  docs/docs/reference/changed-features/operators.md
  docs/docs/reference/changed-features/structural-types-spec.md
  docs/docs/reference/contextual/context-functions-spec.md
  docs/docs/reference/contextual/extension-methods.md
  docs/docs/reference/contextual/implicit-by-name-parameters.md
  docs/docs/reference/contextual/import-delegate.md
  docs/docs/reference/contextual/import-implied.md
  docs/docs/reference/contextual/inferable-by-name-parameters.md
  docs/docs/reference/contextual/inferable-params.md
  docs/docs/reference/contextual/instance-defs.md
  docs/docs/reference/contextual/multiversal-equality.md
  docs/docs/reference/contextual/query-types-spec.md
  docs/docs/reference/contextual/query-types.md
  docs/docs/reference/contextual/right-associative-extension-methods.md
  docs/docs/reference/dropped-features/weak-conformance-spec.md
  docs/docs/reference/features-classification.md
  docs/docs/reference/new-types/dependent-function-types-spec.md
  docs/docs/reference/other-new-features/implicit-by-name-parameters.md
  docs/docs/reference/other-new-features/matchable.md
  docs/docs/reference/other-new-features/targetName.md
  docs/docs/reference/other-new-features/threadUnsafe-annotation.md
  docs/docs/reference/syntax.md
Labels: area:documentation

#10932 Fix a code example in tasty-reflect.md
  docs/docs/reference/metaprogramming/tasty-inspect.md
  docs/docs/reference/metaprogramming/tasty-reflect.md
  docs/docs/reference/other-new-features/indentation.md
Labels: area:documentation

#11032 Update dotty landing page
  scala3doc/scala3-docs/css/frontpage.css
  scala3doc/scala3-docs/index.html
Labels: area:documentation

#11062 [docs/reference] more fixes in Markdown files
  docs/docs/reference/changed-features/implicit-conversions-spec.md
  docs/docs/reference/changed-features/numeric-literals.md
  docs/docs/reference/changed-features/overload-resolution.md
  docs/docs/reference/changed-features/pattern-bindings.md
  docs/docs/reference/changed-features/pattern-matching.md
  docs/docs/reference/contextual/context-functions-spec.md
  docs/docs/reference/contextual/derivation.md
  docs/docs/reference/contextual/givens.md
  docs/docs/reference/contextual/multiversal-equality.md
  docs/docs/reference/contextual/relationship-implicits.md
  docs/docs/reference/contextual/using-clauses.md
  docs/docs/reference/features-classification.md
  docs/docs/reference/metaprogramming/erased-terms-spec.md
  docs/docs/reference/new-types/dependent-function-types.md
  docs/docs/reference/new-types/match-types.md
  docs/docs/reference/new-types/type-lambdas-spec.md
  docs/docs/reference/new-types/union-types-spec.md
  docs/docs/reference/other-new-features/export.md
  docs/docs/reference/other-new-features/opaques-details.md
  docs/docs/reference/other-new-features/transparent-traits.md
  docs/docs/reference/other-new-features/type-test.md
  docs/docs/reference/overview.md
Labels: area:documentation

#11065 Fix hoisting supercall arguments from primary constructor
  compiler/src/dotty/tools/dotc/transform/HoistSuperArgs.scala
  tests/pos/i11045.scala
Labels: fasttrack

#11063 Generalize isArgPrefixOf
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/pos/i11057.scala
Labels: fasttrack

#11069 Special case comparisons between LazyRefs and bottom/top types
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  tests/neg-custom-args/allow-deep-subtypes/i11064.scala
  tests/neg/i6225.scala
  tests/pos/i11064.scala
Labels: fasttrack

#11104 Allow literals as given types
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  tests/pos/i11102.scala
Labels: fasttrack

#11151 fix #11128: skip ctor proxy in named export
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  tests/pos/i11128-wildcard.scala
  tests/pos/i11128.scala
Labels: fasttrack

#11160 Fix conflict with Toolbox to Compiler renaming
  tests/run-staging/i11152.scala
Labels: prio:high

#11158 more fixes in Markdown files
  docs/docs/reference/changed-features/compiler-plugins.md
  docs/docs/reference/changed-features/interpolation-escapes.md
  docs/docs/reference/changed-features/main-functions.md
  docs/docs/reference/contextual/derivation-macro.md
  docs/docs/reference/dropped-features/early-initializers.md
  docs/docs/reference/metaprogramming/macros.md
  docs/docs/reference/metaprogramming/tasty-inspect.md
  docs/docs/reference/other-new-features/safe-initialization.md
  docs/docs/reference/other-new-features/type-test.md
  docs/docs/reference/overview.md
Labels: area:documentation

#11169 Document deprecation of enum cases
  docs/docs/reference/enums/enums.md
Labels: area:documentation

#11167 allow tasty version to be inspected
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tasty/src-bootstrapped/dotty/tools/tasty/TastyHeaderUnpickler.scala
  tasty/src-non-bootstrapped/dotty/tools/tasty/TastyHeaderUnpickler.scala
Labels: area:tasty-format

#11228 Fix syntax of failing test in master
  tests/pos/i11078b.scala
Labels: fasttrack, prio:high

#11235 3 fixes in Markdown files
  docs/docs/reference/other-new-features/indentation.md
  docs/docs/reference/syntax.md
Labels: area:documentation
