Repository scala/scala3, pull requests merged in 2021-02, with the labels that each got.

#11280 Fix Java 8 CI
  scala3doc-testcases/src/tests/deprecated.scala
Labels: prio:high

#11329 Alternative definition layout of IArray
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/ArrayApply.scala
  compiler/src/dotty/tools/dotc/transform/ArrayConstructors.scala
  compiler/test/dotty/tools/backend/jvm/ArrayApplyOptTest.scala
  library/src/scala/IArray.scala
Labels: RC1:high-prio, release-notes

#11354 Add missing IArray operations
  library/src/scala/IArray.scala
  tests/run/IArrayOps.check
  tests/run/IArrayOps.scala
Labels: RC1:high-prio

#11343 new TASTy header format - add experimental version and tooling version fields
  compiler/src/dotty/tools/dotc/config/Properties.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyPickler.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tasty/src-bootstrapped/dotty/tools/tasty/TastyHeaderUnpickler.scala
  tasty/src-non-bootstrapped/dotty/tools/tasty/TastyHeaderUnpickler.scala
  tasty/src/dotty/tools/tasty/TastyFormat.scala
  tasty/src/dotty/tools/tasty/TastyHeaderUnpickler.scala
  tasty/test/dotty/tools/tasty/TastyHeaderUnpicklerTest.scala
  tasty/test/dotty/tools/tasty/TastyVersionFormatTest.scala
Labels: RC1:high-prio

#11418 Fix #11415: always expand bounds in type approximation
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/pos/i11415.scala
Labels: RC1:high-prio

#11422 Handle creator applications in nested companion objects
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/pos/i11420.scala
Labels: RC1:high-prio

#11425 fix for #11424
  dist/bin/scala
Labels: RC1:high-prio

#11480 more fixes in Markdown files
  docs/docs/internals/syntax.md
  docs/docs/reference/changed-features/eta-expansion-spec.md
  docs/docs/reference/contextual/extension-methods.md
  docs/docs/reference/dropped-features/do-while.md
  docs/docs/reference/dropped-features/package-objects.md
  docs/docs/reference/dropped-features/procedure-syntax.md
  docs/docs/reference/dropped-features/weak-conformance-spec.md
  docs/docs/reference/syntax.md
Labels: area:documentation
