Repository scala/scala3, pull requests merged in 2021-06, with the labels that each got.

#12774 scaladoc/fix-escaping-tags
  scaladoc/src/dotty/tools/scaladoc/tasty/comments/markdown/SnippetRenderer.scala
  scaladoc/src/dotty/tools/scaladoc/util/html.scala
Labels: area:doctool

#12827 Fix TyperState assertion failures
  compiler/src/dotty/tools/dotc/core/Contexts.scala
  compiler/src/dotty/tools/dotc/core/TyperState.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  tests/neg/i12736a.scala
  tests/neg/i12736b.scala
Labels: backport:nominated

#12838 [Bridge] Position - implement methods for accesing range
  sbt-bridge/src/dotty/tools/xsbt/PositionBridge.java
Labels: backport:nominated

#12863 Drop implementation restriction for polymorphic functions
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/core/TypeErasure.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  tests/neg/i2887b.scala
  tests/pos/polymorphic-functions.scala
Labels: cc-experiment

#12844 TreeUnpickler: fix cycle involving param accessor
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  tests/pos/i12834.scala
Labels: backport:nominated

#12859 Add IO test
  tests/neg-custom-args/captures/io.scala
Labels: cc-experiment

#12842 Don't forget side effects in prefixes of inlined function calls
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  tests/run/i12829.check
  tests/run/i12829.scala
Labels: backport:nominated

#12891 Improve docs styles
  docs/logo.svg
  scaladoc-js/resources/scaladoc-searchbar.css
  scaladoc/resources/dotty_res/styles/colors.css
  scaladoc/resources/dotty_res/styles/diagram.css
  scaladoc/resources/dotty_res/styles/filter-bar.css
  scaladoc/resources/dotty_res/styles/scalastyle.css
  scaladoc/src/dotty/tools/scaladoc/renderers/HtmlRenderer.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/Resources.scala
Labels: area:doctool
