Repository scala/scala3, pull requests merged in 2021-03, with the labels that each got.

#10304 improved readability of help messages
  compiler/src/dotty/tools/dotc/config/CliCommand.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  dist/bin/common
Labels: area:tooling

#11569 Try to remove compiletime.Widen
  library/src/scala/compiletime/package.scala
Labels: release-notes

#11655 Add -Xcheck-macros scalac option
  community-build/src/scala/dotty/communitybuild/projects.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  compiler/src/scala/quoted/runtime/impl/ScopeException.scala
  compiler/test/dotty/tools/dotc/BootstrappedOnlyCompilationTests.scala
  docs/docs/internals/debug-macros.md
  docs/docs/reference/metaprogramming/macros.md
Labels: release-notes

#11670 Rename -Ycheck-init to -Ysafe-init
  community-build/src/scala/dotty/communitybuild/projects.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  docs/blog/_posts/2020-03-18-23rd-dotty-milestone-release.md
  docs/docs/reference/other-new-features/explicit-nulls.md
  docs/docs/reference/other-new-features/safe-initialization.md
Labels: release-notes

#11726 more fixes in Markdown files
  docs/docs/reference/changed-features/eta-expansion.md
  docs/docs/reference/dropped-features/limit22.md
  docs/docs/reference/dropped-features/xml.md
  docs/docs/reference/metaprogramming/inline.md
  docs/docs/reference/overview.md
Labels: area:documentation

#11679 Add TypeTest doc to sidebar on website
  docs/sidebar.yml
Labels: area:documentation, fasttrack

#11715 Add quotes.Type.valueOfConstant
  library/src-bootstrapped/scala/quoted/Type.scala
  tests/run-macros/from-type.check
  tests/run-macros/from-type/Macro_1.scala
  tests/run-macros/from-type/Test_2.scala
Labels: release-notes

#11671 Treat Scala.js pseudo-unions as real unions
  compiler/src/dotty/tools/backend/sjs/JSDefinitions.scala
  compiler/src/dotty/tools/dotc/core/TypeErasure.scala
  compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/ImportSuggestions.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  library-js/src/scala/scalajs/js/internal/UnitOps.scala
  project/Build.scala
  sbt-dotty/sbt-test/scala2-compat/erasure-scalajs/build.sbt
  sbt-dotty/sbt-test/scala2-compat/erasure-scalajs/dottyApp/Main.scala
  sbt-dotty/sbt-test/scala2-compat/erasure-scalajs/project/plugins.sbt
  sbt-dotty/sbt-test/scala2-compat/erasure-scalajs/scala2Lib/Api.scala
  sbt-dotty/sbt-test/scala2-compat/erasure-scalajs/test
  sbt-dotty/sbt-test/scala2-compat/erasure/build.sbt
  sbt-dotty/sbt-test/scala2-compat/i8001/build.sbt
  sbt-dotty/sbt-test/scala2-compat/i8847/build.sbt
  sbt-dotty/sbt-test/scala2-compat/i9916a/build.sbt
  sbt-dotty/sbt-test/scala2-compat/i9916b/build.sbt
  tests/neg-scalajs/js-trait-members-wrong-kind.check
  tests/neg-scalajs/type-mismatch.check
  tests/neg-scalajs/type-mismatch.scala
  tests/sjs-junit/test/org/scalajs/testsuite/jsinterop/PromiseMock.scala
Labels: release-notes

#11691 fix param desugar in right-associative extensions
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  tests/pos/i11583.scala
  tests/run/i11583.scala
Labels: area:desugar, area:extension-methods
