Repository scala/scala3, pull requests merged in 2021-11, with the labels that each got.

#13797 Add `scala.language.{3.1, 3.1-migration}`
  library/src/scala/runtime/stdLibPatches/language.scala
  project/MiMaFilters.scala
  tests/pos/source-import-3-0-migration.scala
  tests/pos/source-import-3-0.scala
  tests/pos/source-import-3-1-migration.scala
  tests/pos/source-import-3-1.scala
Labels: backport:nominated

#13795 Allow dual Scala 2/3 in non-experimental scopes
  compiler/src/dotty/tools/dotc/transform/PruneErasedDefs.scala
  tests/pos-custom-args/no-experimental/i8945.scala
Labels: backport:accepted

#13791 Handle IOException when calling deleteIfExists
  compiler/test/dotty/tools/dotc/classpath/MultiReleaseJarTest.scala
Labels: area:testing

#13657 Special rule for `{this}` in capture sets of class members
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/transform/Recheck.scala
  compiler/src/dotty/tools/dotc/typer/CheckCaptures.scala
  tests/neg-custom-args/captures/lazylists1.check
  tests/neg-custom-args/captures/lazylists1.scala
  tests/neg-custom-args/captures/lazylists2.check
  tests/neg-custom-args/captures/lazylists2.scala
  tests/pos-custom-args/captures/lazylists-mono.scala
  tests/pos-custom-args/captures/lazylists.scala
  tests/pos-custom-args/captures/lazylists1.scala
Labels: cc-experiment

#13952 move implementation of ordinal in enums to posttyper
  compiler/src/dotty/tools/dotc/ast/DesugarEnums.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  tests/neg/enumsLabel-singleimpl.scala
  tests/pos/i13554.scala
  tests/pos/i13554a.scala
Labels: area:desugar

#13481 [SemanticDB] Support TypeApply Synthetic
  compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala
  compiler/src/dotty/tools/dotc/semanticdb/SyntheticsExtractor.scala
  tests/semanticdb/metac.expect
Labels: area:semanticdb
