Repository scala/scala3, pull requests merged in 2021-09, with the labels that each got.

#13474 Remove anomalies and gaps in handling annotations
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/core/Annotations.scala
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/printing/Printer.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  tests/neg/annot-printing.check
  tests/neg/annot-printing.scala
  tests/pos/dependent-annot.scala
Labels: cc-experiment

#12768 Fix #10747: Raise type error on unreducible match type
  compiler/src/dotty/tools/dotc/core/MatchTypeTrace.scala
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  compiler/src/dotty/tools/dotc/typer/VarianceChecker.scala
  tests/neg-macros/toexproftuple.scala
  tests/neg/10747.scala
  tests/neg/12974.scala
  tests/neg/6697.check
  tests/neg/i12049.check
  tests/neg/matchtype-seq.check
  tests/pos/10747-onnxmin.scala
  tests/pos/10747-shapeless-min.scala
  tests/run-macros/tasty-simplified.check
Labels: backport:accepted

#13530 Set typer phase after InteractiveDriver.run
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
Labels: backport:accepted

#13577 bach files support installation path containing spaces
  dist/bin/common.bat
  dist/bin/scalac.bat
Labels: area:tooling

#13617 Allow -source 3.1 as a version
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/config/SourceVersion.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
Labels: backport:accepted
