Repository scala/scala3, pull requests merged in 2022-05, with the labels that each got.

#14497 Allow exports in extension clauses
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/ReTyper.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/_docs/internals/syntax.md
  docs/_docs/reference/other-new-features/export.md
  docs/_docs/reference/syntax.md
  tests/neg/export-extension-in-extension.scala
  tests/neg/export-in-extension.check
  tests/neg/export-in-extension.scala
  tests/neg/exports.check
  tests/neg/exports.scala
  tests/pos/export-in-extension-rename.scala
  tests/pos/forwardCompat-exportInExtension/Lib_1_r3.0.scala
  tests/pos/forwardCompat-exportInExtension/Test_2_c3.0.2.scala
  tests/pos/reference/exports.scala
  tests/run/export-in-extension.scala
Labels: needs-minor-release

#15070 Three capture checking fixes
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/cc/Setup.scala
  compiler/src/dotty/tools/dotc/config/Config.scala
  compiler/src/dotty/tools/dotc/core/Substituters.scala
  compiler/src/dotty/tools/dotc/core/TypeApplications.scala
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/CheckCaptures.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/ImportSuggestions.scala
  docs/_docs/reference/experimental/cc.md
  tests/neg-custom-args/captures/i15049.scala
  tests/neg-custom-args/captures/unbox.scala
  tests/neg-custom-args/captures/usingLogFile.check
  tests/neg-custom-args/captures/usingLogFile.scala
  tests/pos-custom-args/captures/compare-refined.scala
  tests/pos-custom-args/captures/pairs.scala
  tests/semanticdb/metac.expect
Labels: cc-experiment

#14971 Erase `Int | Nothing` signatures types into `Int`
  compiler/src/dotty/tools/dotc/core/TypeErasure.scala
  compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala
  tests/neg/i5823.scala
  tests/run/i14964.scala
  tests/run/i14964b.check
  tests/run/i14964b.scala
  tests/run/i14970.scala
Labels: release-notes, needs-minor-release

#14986 Fix 12919 - summon anonymous mirror when companion is a case object
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/run/i12919.scala
  tests/run/i12919a.scala
  tests/run/i12919b.scala
  tests/run/i15101.scala
Labels: area:typeclass-derivation

#15006 Fix 14025: restrict curried type lambdas in mirror generation
  compiler/src/dotty/tools/dotc/transform/TypeUtils.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/neg/i14025.check
  tests/neg/i14025.scala
  tests/neg/i14823.check
  tests/neg/i14823.scala
  tests/pos/i14823.scala
Labels: area:typeclass-derivation

#15008 fix #14432: check if scala 2 case class is accessible
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  sbt-test/scala2-compat/i14432/app1fail/Test.scala
  sbt-test/scala2-compat/i14432/app1ok/Test.scala
  sbt-test/scala2-compat/i14432/app2fail/Test.scala
  sbt-test/scala2-compat/i14432/build.sbt
  sbt-test/scala2-compat/i14432/lib1/Foo.scala
  sbt-test/scala2-compat/i14432/lib2/Foo.scala
  sbt-test/scala2-compat/i14432/test
  tests/neg/i14432.check
  tests/neg/i14432.scala
  tests/neg/i14432a.check
  tests/neg/i14432a.scala
  tests/neg/i14432b.check
  tests/neg/i14432b.scala
  tests/neg/i14432c.check
  tests/neg/i14432c.scala
  tests/neg/i14432d.check
  tests/neg/i14432d.scala
  tests/run/i14432.scala
  tests/run/i14432a.scala
  tests/run/i14432b.scala
  tests/run/i14432c.scala
Labels: area:typeclass-derivation

#15136 Fix locality condition for checking inferred types
  compiler/src/dotty/tools/dotc/typer/CheckCaptures.scala
  tests/neg-custom-args/captures/i15116.check
  tests/neg-custom-args/captures/i15116.scala
  tests/neg-custom-args/captures/lazylists-exceptions.check
  tests/neg-custom-args/captures/lazylists-exceptions.scala
  tests/neg-custom-args/captures/lazyref.scala
  tests/neg-custom-args/captures/usingLogFile.scala
  tests/pos-custom-args/captures/capt-capability.scala
  tests/pos-custom-args/captures/capt1.scala
  tests/pos-custom-args/captures/capt2.scala
  tests/pos-custom-args/captures/cc-this.scala
  tests/pos-custom-args/captures/curried-shorthands.scala
  tests/pos-custom-args/captures/lazylists-exceptions.scala
  tests/pos-custom-args/captures/lazyref.scala
  tests/pos-custom-args/captures/logger.scala
Labels: cc-experiment

#14895 Add safe-init test to prevent adding cold elements to hot arrays
  tests/init/neg/cold-insert-hot-array.scala
Labels: area:initialization

#14972 Make `EmptyTuple` a `case object`
  library/src/scala/Tuple.scala
Labels: needs-minor-release

#14632 add eq/ne extension for AnyRef|Null to Scala3RunTime
  library/src/scala/runtime/stdLibPatches/Predef.scala
  tests/coverage/pos/Inlined.scoverage.check
  tests/explicit-nulls/pos/eq-ne.scala
  tests/explicit-nulls/unsafe-common/unsafe-eq.scala
  tests/run-custom-args/tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: needs-minor-release

#15164 Add error reporting for mirror synthesis
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  docs/_docs/reference/contextual/derivation.md
  tests/neg-custom-args/i13838.check
  tests/neg-macros/i6436.check
  tests/neg-macros/i9014b.check
  tests/neg-scalajs/jsconstructortag-error-in-typer.check
  tests/neg/i10603a.check
  tests/neg/i10901.check
  tests/neg/i11066.check
  tests/neg/i11897.check
  tests/neg/i12049.check
  tests/neg/i12232.check
  tests/neg/i12591.check
  tests/neg/i13991.check
  tests/neg/i14025.check
  tests/neg/i14432.check
  tests/neg/i14432a.check
  tests/neg/i14432b.check
  tests/neg/i14432c.check
  tests/neg/i14432d.check
  tests/neg/i14823.check
  tests/neg/i5498-postfixOps.check
  tests/neg/i7613.check
  tests/neg/i9185.check
  tests/neg/i9568.check
  tests/neg/i9958.check
  tests/neg/implicitSearch.check
  tests/neg/mirror-synthesis-errors.check
  tests/neg/mirror-synthesis-errors.scala
  tests/neg/missing-implicit1.check
  tests/neg/missing-implicit2.check
  tests/neg/missing-implicit3.check
  tests/neg/missing-implicit4.check
  tests/neg/summon-function.check
Labels: release-notes

#15169 Remove usage section from docs
  docs/_docs/usage/cbt-projects.md
  docs/_docs/usage/dottydoc.md
  docs/_docs/usage/ide-support.md
  docs/_docs/usage/index.md
  docs/_docs/usage/sbt-projects.md
  docs/_docs/usage/scaladoc/blog.md
  docs/_docs/usage/scaladoc/docstrings.md
  docs/_docs/usage/scaladoc/index.md
  docs/_docs/usage/scaladoc/linking.md
  docs/_docs/usage/scaladoc/search-engine.md
  docs/_docs/usage/scaladoc/settings.md
  docs/_docs/usage/scaladoc/site-versioning.md
  docs/_docs/usage/scaladoc/static-site.md
  docs/_docs/usage/version-numbers.md
  docs/_docs/usage/worksheet-mode-implementation-details.md
  docs/sidebar.yml
Labels: area:documentation

#14780 Make lazy vals and object native image friendly
  compiler/src/dotty/tools/dotc/transform/LazyVals.scala
  library/src/scala/runtime/LazyVals.scala
Labels: needs-minor-release

#14916 Check method arguments with parametricity when static
  compiler/src/dotty/tools/dotc/transform/init/Semantic.scala
  tests/init/neg/early-promote.scala
  tests/init/neg/enum-desugared.check
  tests/init/neg/enum.check
  tests/init/neg/inner-case.scala
  tests/init/neg/inner-new.scala
  tests/init/neg/insert-cold-subtype-to-array.scala
  tests/init/neg/leak-warm.check
  tests/init/neg/leak-warm.scala
  tests/init/neg/some-this.scala
  tests/init/pos/enum-desugared.scala
  tests/init/pos/enum-ordinal.scala
  tests/init/pos/inner-enum-multi-variant.scala
  tests/init/pos/inner-enum.scala
Labels: area:initialization

#15170 Fix documentation regressions
  docs/_docs/internals/syntax-3.1.md
  docs/_docs/reference/experimental/explicit-nulls.md
  docs/_docs/reference/experimental/fewer-braces.md
  docs/_docs/release-notes-0.1.2.md
  docs/sidebar.yml
  project/resources/referenceReplacements/sidebar.yml
  project/scripts/expected-links/reference-expected-links.txt
Labels: area:documentation

#15211 Revert "requests-scala fails due to expired ssh cert"
  community-build/test/scala/dotty/communitybuild/CommunityBuildTest.scala
Labels: area:testing, fasttrack

#15212 implement scalac script in Scala
  compiler/src/dotty/tools/MainGenericCompiler.scala
  compiler/src/dotty/tools/MainGenericRunner.scala
  dist/bin/scala
  dist/bin/scalac
  project/scripts/bootstrappedOnlyCmdTests
Labels: needs-minor-release, area:scripting

#15246 Add dotty bisection tool
  project/scripts/dottyCompileBisect.scala
  project/scripts/dottyCompileBisect.sh
Labels: itype:enhancement, area:tooling, area:testing

#14431 Add compiletime.ops.string.CharAt
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  library/src/scala/compiletime/ops/any.scala
  library/src/scala/compiletime/ops/double.scala
  library/src/scala/compiletime/ops/float.scala
  library/src/scala/compiletime/ops/int.scala
  library/src/scala/compiletime/ops/long.scala
  library/src/scala/compiletime/ops/string.scala
  tests/neg/singleton-ops-string.scala
  tests/run-custom-args/tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: needs-minor-release

#15259 Revert "BashScriptTests: shebang lines work on macos"
  compiler/test-resources/scripting/classpathReport.sc
  compiler/test-resources/scripting/scriptPath.sc
  compiler/test-resources/scripting/sqlDateError.sc
  compiler/test-resources/scripting/unglobClasspath.sc
Labels: fasttrack

#15185 Avoid overeager completion of Java annotations in classfile parser
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala
  library/src/scala/annotation/internal/TASTYLongSignature.java
  library/src/scala/annotation/internal/TASTYSignature.java
  tests/pos/i15166/InterfaceAudience_JAVA_ONLY_1.java
  tests/pos/i15166/InterfaceStability_JAVA_ONLY_1.java
  tests/pos/i15166/Test_2.scala
Labels: backport:nominated

#15012 Disallow old uses of quoted and spliced types
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/_docs/internals/syntax.md
  tests/neg-macros/type-splice-in-val-pattern.check
  tests/neg-macros/type-splice-in-val-pattern.scala
  tests/neg/i15009a.check
  tests/neg/i15009a.scala
Labels: needs-minor-release

#15281 Fix hash code of ExprImpl and TypeImpl
  compiler/src/scala/quoted/runtime/impl/ExprImpl.scala
  compiler/src/scala/quoted/runtime/impl/TypeImpl.scala
  tests/pos-macros/i15227a/Macro_1.scala
  tests/pos-macros/i15227a/Test_2.scala
  tests/pos-macros/i15227b/Macro_1.scala
  tests/pos-macros/i15227b/Test_2.scala
Labels: fasttrack

#15271 Remove ErrorMessageID.LazyErrorId and improve doc
  compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala
  compiler/src/dotty/tools/dotc/reporting/Message.scala
  compiler/test/dotty/tools/dotc/reporting/TestMessageLaziness.scala
Labels: fasttrack

#15231 fix #15222 recursively check for product ctor accessibility
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/neg/i14025.check
  tests/neg/i14823.check
  tests/neg/prod-mirror-inacessible-ctor.scala
  tests/run/i15234.scala
  tests/run/prod-mirror-inacessible-ctor/Lib_1.scala
  tests/run/prod-mirror-inacessible-ctor/Test_2.scala
Labels: area:typeclass-derivation

#15305 using `as` for renaming in export doc
  docs/_docs/reference/other-new-features/export.md
Labels: area:documentation

#15309 Use intersection to type selections
  compiler/src/dotty/tools/dotc/transform/Recheck.scala
  compiler/src/dotty/tools/dotc/typer/CheckCaptures.scala
  tests/neg-custom-args/captures/caseclass/Test_2.scala
  tests/neg-custom-args/captures/ctest.scala
  tests/neg-custom-args/captures/i15116.check
  tests/neg-custom-args/captures/i15116.scala
  tests/pos-custom-args/captures/caseclass.scala
  tests/semanticdb/metac.expect
Labels: cc-experiment

#15279 restrict mirrors of any union type
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/neg/i14025.check
  tests/neg/i14823.check
  tests/neg/i14823a.check
  tests/neg/i14823a.scala
  tests/pos/i14823.scala
Labels: needs-minor-release

#15072 Properly look for inline methods
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  tests/neg-macros/i14679.scala
Labels: fasttrack

#15247 Transform RHS of captured assignment reference
  compiler/src/dotty/tools/dotc/transform/Splicing.scala
  tests/pos-macros/i15213.scala
Labels: fasttrack

#15192 support intersection types in mirrorCompanionRef
  compiler/src/dotty/tools/dotc/transform/TypeUtils.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/neg/i15190.scala
  tests/neg/mirror-synthesis-errors-b.check
  tests/neg/mirror-synthesis-errors-b.scala
  tests/run/i15190.scala
Labels: area:typeclass-derivation

#15328 close parenthesis
  docs/_docs/reference/experimental/overview.md
Labels: area:documentation, fasttrack

#15014 fix 14150 - constrain refinements to type parameters
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/neg/7380a.scala
  tests/run-macros/i7987.check
  tests/run/i14150.scala
Labels: area:typeclass-derivation

#15250 synthesize mirrors for small generic tuples
  compiler/src/dotty/tools/dotc/core/TypeErasure.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/transform/GenericSignatures.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/transform/TypeUtils.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i14127.check
  tests/neg/i14127.scala
  tests/pos/i13859.scala
  tests/run/i14127.scala
  tests/run/i7049.scala
Labels: area:typeclass-derivation, release-notes

#15341 Partial revert of #13780
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/test/dotc/pos-test-pickling.blacklist
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tests/neg/11982.scala
  tests/neg/6570-1.scala
  tests/neg/6570.scala
  tests/neg/i15155.check
  tests/pos/i15155.scala
  tests/run/typeclass-derivation1.scala
Labels: backport:nominated
