Repository scala/scala3, pull requests merged in 2022-04, with the labels that each got.

#14817 Split mvn and github publishing steps
  .github/workflows/ci.yaml
Labels: area:infrastructure

#14813 Fix universal check for inferred types
  compiler/src/dotty/tools/dotc/typer/CheckCaptures.scala
  docs/_docs/reference/experimental/cc.md
  tests/neg-custom-args/captures/usingLogFile.check
  tests/neg-custom-args/captures/usingLogFile.scala
Labels: cc-experiment

#14608 Support MatchType for SemanticDB
  compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala
  compiler/src/dotty/tools/dotc/semanticdb/PPrint.scala
  compiler/src/dotty/tools/dotc/semanticdb/Scala3.scala
  compiler/src/dotty/tools/dotc/semanticdb/TypeOps.scala
  compiler/src/dotty/tools/dotc/semanticdb/generated/Type.scala
  tests/semanticdb/expect/Advanced.expect.scala
  tests/semanticdb/expect/Advanced.scala
  tests/semanticdb/expect/MatchType.expect.scala
  tests/semanticdb/expect/MatchType.scala
  tests/semanticdb/expect/dep-match.expect.scala
  tests/semanticdb/expect/dep-match.scala
  tests/semanticdb/expect/i5854.expect.scala
  tests/semanticdb/expect/i5854.scala
  tests/semanticdb/metac.expect
Labels: stat:do not merge, area:semanticdb

#14837 Set reference version to 3.1.2
  project/Build.scala
  project/MiMaFilters.scala
Labels: area:infrastructure

#14815 Add tests checking whether the links haven't changed
  .github/workflows/scaladoc.yaml
  project/scripts/docsLinksStability
  project/scripts/expected-links/reference-expected-links.txt
  project/scripts/expected-links/scala3-expected-links.txt
  project/scripts/regenerateExpectedLinks
Labels: area:documentation, area:doctool

#14839 Fix snippets hiding and buttons animation
  scaladoc-js/common/css/code-snippets.css
  scaladoc/resources/dotty_res/scripts/ux.js
  scaladoc/resources/dotty_res/styles/scalastyle.css
Labels: area:doctool

#13880 Add in initial support for code coverage
  NOTICE.md
  compiler/src/dotty/tools/dotc/Compiler.scala
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/MainProxies.scala
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/coverage/Coverage.scala
  compiler/src/dotty/tools/dotc/coverage/Location.scala
  compiler/src/dotty/tools/dotc/coverage/Serializer.scala
  compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala
  compiler/src/dotty/tools/dotc/transform/Mixin.scala
  compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala
  compiler/test/dotty/tools/dotc/coverage/CoverageTests.scala
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
  docs/_docs/usage/coverage.md
  library/src/scala/runtime/coverage/Invoker.scala
  project/Build.scala
  tests/coverage/pos/Constructor.scala
  tests/coverage/pos/Constructor.scoverage.check
  tests/coverage/pos/ContextFunctions.scala
  tests/coverage/pos/ContextFunctions.scoverage.check
  tests/coverage/pos/Enum.scala
  tests/coverage/pos/Enum.scoverage.check
  tests/coverage/pos/Givens.scala
  tests/coverage/pos/Givens.scoverage.check
  tests/coverage/pos/Inlined.scala
  tests/coverage/pos/Inlined.scoverage.check
  tests/coverage/pos/Literals.scala
  tests/coverage/pos/Literals.scoverage.check
  tests/coverage/pos/MatchCaseClasses.scala
  tests/coverage/pos/MatchCaseClasses.scoverage.check
  tests/coverage/pos/MatchNumbers.scala
  tests/coverage/pos/MatchNumbers.scoverage.check
  tests/coverage/pos/Select.scala
  tests/coverage/pos/Select.scoverage.check
  tests/coverage/pos/SimpleMethods.scala
  tests/coverage/pos/SimpleMethods.scoverage.check
  tests/coverage/pos/StructuralTypes.scala
  tests/coverage/pos/StructuralTypes.scoverage.check
  tests/coverage/pos/TypeLambdas.scala
  tests/coverage/pos/TypeLambdas.scoverage.check
  tests/coverage/run/currying/test.check
  tests/coverage/run/currying/test.scala
  tests/coverage/run/currying/test.scoverage.check
  tests/coverage/run/inheritance/test.check
  tests/coverage/run/inheritance/test.scala
  tests/coverage/run/inheritance/test.scoverage.check
  tests/coverage/run/interpolation/test.check
  tests/coverage/run/interpolation/test.scala
  tests/coverage/run/interpolation/test.scoverage.check
  tests/coverage/run/lifting/test.check
  tests/coverage/run/lifting/test.scala
  tests/coverage/run/lifting/test.scoverage.check
  tests/coverage/run/trait/test.check
  tests/coverage/run/trait/test.scala
  tests/coverage/run/trait/test.scoverage.check
Labels: release-notes, needs-minor-release

#14558 Add `scala.annotation.MainAnnotation`
  compiler/src/dotty/tools/dotc/ast/MainProxies.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/_docs/reference/experimental/main-annotation.md
  docs/sidebar.yml
  library/src/scala/annotation/MainAnnotation.scala
  project/MiMaFilters.scala
  project/resources/referenceReplacements/sidebar.yml
  project/scripts/expected-links/reference-expected-links.txt
  tests/neg/main-annotation-mainannotation.scala
  tests/run/main-annotation-example.check
  tests/run/main-annotation-example.scala
  tests/run/main-annotation-homemade-annot-1.check
  tests/run/main-annotation-homemade-annot-1.scala
  tests/run/main-annotation-homemade-annot-2.check
  tests/run/main-annotation-homemade-annot-2.scala
  tests/run/main-annotation-homemade-annot-3.check
  tests/run/main-annotation-homemade-annot-3.scala
  tests/run/main-annotation-homemade-annot-4.check
  tests/run/main-annotation-homemade-annot-4.scala
  tests/run/main-annotation-homemade-annot-5.check
  tests/run/main-annotation-homemade-annot-5.scala
  tests/run/main-annotation-homemade-annot-6.check
  tests/run/main-annotation-homemade-annot-6.scala
  tests/run/main-annotation-newMain.scala
Labels: release-notes

#14934 Set reference version to 3.1.3-RC2
  project/Build.scala
Labels: itype:meta

#14987 More aggressive reduction of type selection (fixes parboiled2)
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/pos/13491.scala
  tests/pos/i14903a.scala
  tests/pos/i14903b.scala
Labels: backport:nominated

#14840 Fix Scala Wart about implicit () class parameters
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/config/PathResolver.scala
  compiler/src/dotty/tools/dotc/core/NamerOps.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/transform/Bridges.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i12344.scala
  tests/pos/given-constrapps.scala
  tests/pos/i2576.scala
  tests/run-macros/i12021/Macro_1.scala
  tests/run/backwardsCompat-implicitParens.check
  tests/run/backwardsCompat-implicitParens/A_1_c3.0.2.scala
  tests/run/backwardsCompat-implicitParens/Test_2.scala
  tests/run/i2567.scala
  tests/semanticdb/metac.expect
Labels: needs-minor-release

#15003 Fix typos
  tests/run-custom-args/tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: fasttrack

#14657 Scaladoc: Warn about special characters in filenames according to the default Jekyll rules
  scaladoc-testcases/src/docs/tests/Adoc.scala
  scaladoc-testcases/src/example/JekyllIncompat.scala
  scaladoc/src/dotty/tools/scaladoc/DocContext.scala
  scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/Locations.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/Renderer.scala
  scaladoc/src/dotty/tools/scaladoc/site/StaticSiteContext.scala
  scaladoc/src/dotty/tools/scaladoc/util/check.scala
  scaladoc/test/dotty/tools/scaladoc/ReportingTest.scala
  scaladoc/test/dotty/tools/scaladoc/site/NavigationTest.scala
  scaladoc/test/dotty/tools/scaladoc/site/SiteGeneratationTest.scala
Labels: area:doctool

#14996 Add some overview notes on the GADT implementation
  docs/_docs/internals/gadts.md
  docs/sidebar.yml
Labels: area:documentation
