Repository scala/scala3, pull requests merged in 2022-03, with the labels that each got.

#14543 Runner sets residual args instead of append
  compiler/src/dotty/tools/MainGenericRunner.scala
  tests/run-with-compiler/i14541.check
  tests/run-with-compiler/i14541.scala
Labels: backport:accepted

#14594 fix(completions): add backticks when needed in completions
  compiler/src/dotty/tools/dotc/interactive/Completion.scala
  compiler/src/dotty/tools/repl/JLineTerminal.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test/dotty/tools/repl/TabcompleteTests.scala
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
Labels: area:ide

#14595 Add JS DOM utils to Scaladoc-js
  project/Build.scala
  scaladoc-js/common/src/code-snippets/CodeSnippets.scala
  scaladoc-js/common/src/utils/html.scala
  scaladoc-js/contributors/src/content-contributors/ContentContributors.scala
  scaladoc-js/main/src/searchbar/SearchbarComponent.scala
  scaladoc-js/main/src/social-links/SocialLinks.scala
  scaladoc-js/main/src/versions-dropdown/DropdownHandler.scala
Labels: area:doctool

#14525 Don't generate Mirror.Sum for simple enum cases
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/neg/scala_enum_testing.scala
  tests/run/scala_enum_testing.scala
Labels: itype:bug, area:enums

#14669 Tweak Language Reference documentation
  docs/_blog/index.html
  docs/_docs/contributing/index.md
  docs/_docs/index.md
  docs/_docs/internals/index.md
  docs/_docs/reference/changed-features/changed-features.md
  docs/_docs/reference/contextual/contextual.md
  docs/_docs/reference/dropped-features/dropped-features.md
  docs/_docs/reference/enums/enums-index.md
  docs/_docs/reference/experimental/named-typeargs.md
  docs/_docs/reference/experimental/overview.md
  docs/_docs/reference/language-versions/language-versions.md
  docs/_docs/reference/metaprogramming/metaprogramming.md
  docs/_docs/reference/new-types/new-types.md
  docs/_docs/reference/other-new-features/other-new-types.md
  docs/_docs/reference/overview.md
  docs/_docs/usage/dottydoc.md
  docs/_docs/usage/index.md
  docs/_docs/usage/scaladoc/index.md
  docs/_layouts/index.html
  docs/sidebar.yml
  project/Build.scala
  project/resources/referenceReplacements/sidebar.yml
  scaladoc-js/common/src/code-snippets/CodeSnippets.scala
  scaladoc-testcases/docs/_docs/docs/f1.md
  scaladoc/src/dotty/tools/scaladoc/site/LoadedTemplate.scala
  scaladoc/src/dotty/tools/scaladoc/site/StaticSiteContext.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/comments/markdown/SnippetRenderer.scala
Labels: area:doctool

#14607 Add table of content to static sites
  docs/_layouts/doc-page.html
  docs/_layouts/static-site-main.html
  project/resources/referenceReplacements/_layouts/static-site-main.html
  scaladoc-testcases/docs/_docs/docs/f5.html
  scaladoc-testcases/docs/_layouts/static-site-main.html
  scaladoc-testcases/docs/sidebar.yml
  scaladoc/resources/dotty_res/scripts/ux.js
  scaladoc/resources/dotty_res/styles/scalastyle.css
  scaladoc/src/dotty/tools/scaladoc/api.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/HtmlRenderer.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/MarkdownRenderer.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/MemberRenderer.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/Renderer.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/SiteRenderer.scala
  scaladoc/src/dotty/tools/scaladoc/site/FlexmarkSectionWrapper.scala
  scaladoc/src/dotty/tools/scaladoc/site/common.scala
  scaladoc/src/dotty/tools/scaladoc/site/templates.scala
  scaladoc/src/dotty/tools/scaladoc/snippets/FlexmarkSnippetProcessor.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/comments/markdown/DocFlexmarkExtension.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/comments/markdown/SectionRenderingExtension.scala
  scaladoc/test/dotty/tools/scaladoc/site/TemplateFileTests.scala
Labels: area:doctool

#14546 Scaladoc: fix #14481: certain functions not being shown in searchbar
  scaladoc-testcases/src/tests/inheritedMembersFromHidden.scala
  scaladoc/src/dotty/tools/scaladoc/api.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/MemberRenderer.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/Resources.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala
  scaladoc/src/dotty/tools/scaladoc/translators/FilterAttributes.scala
  scaladoc/test/dotty/tools/scaladoc/signatures/TranslatableSignaturesTestCases.scala
Labels: area:doctool

#14650 Scaladoc: Allow to set a comment syntax based on path to source
  project/Build.scala
  project/ScaladocGeneration.scala
  project/scripts/cmdScaladocTests
  scaladoc-testcases/src/example/comment-md/CommentExample.scala
  scaladoc-testcases/src/example/comment-wiki/CommentExample.scala
  scaladoc/src/dotty/tools/scaladoc/DocContext.scala
  scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala
  scaladoc/src/dotty/tools/scaladoc/ScaladocSettings.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/ScalaDocSupport.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/comments/CommentSyntaxArgs.scala
Labels: area:doctool

#14736 Revert "Allow return in tailrec position" #14067
  compiler/src/dotty/tools/dotc/transform/TailRec.scala
  tests/run/tailrec-return.check
  tests/run/tailrec-return.scala
Labels: prio:blocker, backport:nominated

#14741 Use commaSeparated helper in more places
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
Labels: area:parser

#14559 Fix function classpathArgs()
  dist/bin/scaladoc
  dist/bin/scaladoc.bat
Labels: stat:fix available, area:doctool, area:tooling, fasttrack, backport:nominated

#14124 Add reflect `ClassDef.apply` and `Symbol.newClass`
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/neg-macros/newClassExtendsNoParents/Macro_1.scala
  tests/neg-macros/newClassExtendsNoParents/Test_2.scala
  tests/neg-macros/newClassExtendsOnlyTrait/Macro_1.scala
  tests/neg-macros/newClassExtendsOnlyTrait/Test_2.scala
  tests/run-macros/newClass.check
  tests/run-macros/newClass/Macro_1.scala
  tests/run-macros/newClass/Test_2.scala
  tests/run-macros/newClassExtends.check
  tests/run-macros/newClassExtends/Macro_1.scala
  tests/run-macros/newClassExtends/Test_2.scala
  tests/run-macros/newClassExtendsClassParams.check
  tests/run-macros/newClassExtendsClassParams/Macro_1.scala
  tests/run-macros/newClassExtendsClassParams/Test_2.scala
  tests/run-macros/newClassSelf.check
  tests/run-macros/newClassSelf/Macro_1.scala
  tests/run-macros/newClassSelf/Test_2.scala
Labels: release-notes

#14763 Set reference version to 3.1.2-RC3
  project/Build.scala
Labels: itype:meta

#14414 Add experimental TupledFunction
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  docs/_docs/reference/experimental/tupled-function.md
  docs/sidebar.yml
  library/src-bootstrapped/scala/runtime/TupledFunctions.scala
  library/src/scala/util/TupledFunction.scala
  project/MiMaFilters.scala
  tests/neg-custom-args/erased/tupled-function-instances.scala
  tests/neg/tupled-function-instances.scala
  tests/pos/i7851.scala
  tests/pos/tupled-function-instances.scala
  tests/run/tupled-function-andThen.check
  tests/run/tupled-function-andThen.scala
  tests/run/tupled-function-apply.check
  tests/run/tupled-function-apply.scala
  tests/run/tupled-function-compose.check
  tests/run/tupled-function-compose.scala
  tests/run/tupled-function-extension-method.check
  tests/run/tupled-function-extension-method.scala
  tests/run/tupled-function-tupled.check
  tests/run/tupled-function-tupled.scala
  tests/run/tupled-function-untupled.scala
Labels: release-notes

#14577 Fix groupping entries using markdown syntax
  scaladoc-testcases/src/tests/groups.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/comments/Comments.scala
  scaladoc/test/dotty/tools/scaladoc/ScaladocTest.scala
  scaladoc/test/dotty/tools/scaladoc/tasty/comments/MemberGroupingTests.scala
Labels: area:doctool

#14779 Scaladoc: Fix regression with extension methods not being shown in searchbar
  scaladoc/src/dotty/tools/scaladoc/renderers/Resources.scala
Labels: area:doctool

#14784 Make derivedAnnotation of universal the identity
  compiler/src/dotty/tools/dotc/cc/CaptureAnnotation.scala
  tests/pos/i14782.scala
Labels: cc-experiment
