Repository scala/scala3, pull requests merged in 2022-02, with the labels that each got.

#13976 Fix case null on non-nullable type in unsafe nulls
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/transform/patmat/Space.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  tests/explicit-nulls/neg-patmat/match-pat.scala
  tests/explicit-nulls/pos-patmat/unsafe-match-null-pat.scala
  tests/explicit-nulls/unsafe-common/unsafe-match-null.scala
Labels: area:nullability

#13975 Fix override containing type param in explicit nulls
  compiler/src/dotty/tools/dotc/core/Contexts.scala
  compiler/src/dotty/tools/dotc/core/Mode.scala
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/transform/OverridingPairs.scala
  compiler/src/dotty/tools/dotc/transform/ResolveSuper.scala
  tests/explicit-nulls/neg/opaque-nullable.scala
  tests/explicit-nulls/pos/opaque-nullable.scala
  tests/explicit-nulls/pos/override-type-params.scala
Labels: area:nullability

#14405 Set context when reporting summonInline errors
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
  tests/neg-macros/i13406/Qux_1.scala
  tests/neg-macros/i13406/Test_2.scala
Labels: backport:nominated

#14489 Refactor generation configuration in sbt. Generate reference documentation using Scaladoc
  library/src/scala/quoted/Exprs.scala
  project/Build.scala
  project/ScaladocGeneration.scala
  project/resources/referenceReplacements/_layouts/static-site-main.html
  project/resources/referenceReplacements/sidebar.yml
  scaladoc/src/dotty/tools/scaladoc/PathBased.scala
  scaladoc/src/dotty/tools/scaladoc/renderers/Renderer.scala
Labels: area:doctool

#14529 Follow up #14405
  compiler/src/dotty/tools/dotc/typer/Inliner.scala
Labels: backport:nominated

#14114 Add typed versions of Mirror.ProductOf#fromProduct
  library/src/scala/deriving/Mirror.scala
  project/MiMaFilters.scala
  tests/neg/deriving-from-product-typed.scala
  tests/neg/deriving.scala
  tests/run/deriving-from-product-typed.scala
  tests/run/deriving.scala
Labels: itype:enhancement, area:typeclass-derivation

#14557 check defined in src for cache in companion
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/test-resources/repl/i14540
  sbt-test/scala3-backcompat/hierarchical-mirrors/app/Main.scala
  tests/run/i14540-priorRun/Lib_1.scala
  tests/run/i14540-priorRun/Test_2.scala
  tests/run/i14540-sameRun/Lib.scala
  tests/run/i14540-sameRun/Test.scala
Labels: backport:nominated
