Repository scala/scala3, pull requests merged in 2022-09, with the labels that each got.

#15938 Box arguments in type application
  compiler/src/dotty/tools/dotc/core/TypeApplications.scala
  tests/neg-custom-args/captures/i15923-cases.scala
  tests/neg-custom-args/captures/i15923.scala
Labels: cc-experiment

#16054 Set reference version to 3.2.1-RC2
  project/Build.scala
Labels: area:infrastructure

#16070 Be even more careful when combining argument and info in computeAsSeenFrom
  compiler/src/dotty/tools/dotc/core/Denotations.scala
  tests/pos/i16049.scala
  tests/pos/i16076.scala
Labels: backport:accepted
