Repository scala/scala3, pull requests merged in 2022-06, with the labels that each got.

#15349 fix nightlyOf links in docs
  docs/_docs/reference/enums/enums-index.md
  docs/_docs/reference/language-versions/binary-compatibility.md
  docs/_docs/reference/language-versions/language-versions.md
  docs/_docs/reference/language-versions/source-compatibility.md
  docs/_docs/reference/new-types/new-types.md
Labels: area:documentation

#15355 [backport] updated batch files (15220)
  dist/bin/common.bat
  dist/bin/scala.bat
  dist/bin/scalac.bat
  dist/bin/scaladoc.bat
Labels: compat:windows

#15339 Add regression tests
  tests/run-macros/places-proto.check
  tests/run-macros/places-proto/Macros_1.scala
  tests/run-macros/places-proto/Test_2.scala
Labels: fasttrack

#15359 Add regression tests
  tests/pos-macros/i9891.scala
Labels: fasttrack

#15411 Fix TupleXXL.productPrefix
  library/src/scala/runtime/TupleXXL.scala
Labels: release-notes

#15404 Add runtime.TupleMirror to avoid anonymous classes for mirrors of tuples
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  library/src/scala/runtime/TupleMirror.scala
  tests/run/i15399.check
  tests/run/i15399.scala
Labels: area:typeclass-derivation, release-notes, needs-minor-release

#15335 Minor correction in indentation documentation
  docs/_docs/reference/other-new-features/indentation.md
Labels: itype:bug, area:documentation

#15438 Set reference version to 3.1.3
  project/Build.scala
Labels: area:infrastructure

#15418 Speed up `.nn`
  compiler/test/dotty/tools/backend/jvm/InlineBytecodeTests.scala
  library/src/scala/runtime/Scala3RunTime.scala
  library/src/scala/runtime/stdLibPatches/Predef.scala
Labels: area:nullability

#15443 Handle recursions in isFullyDefined
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/Inferencing.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i15311.check
  tests/neg/i15311.scala
Labels: how-i-fixed-it

#15457 Fix MiMa filters for base version 3.2.1-RC1
  library/src/scala/annotation/MainAnnotation.scala
  library/src/scala/annotation/newMain.scala
  project/MiMaFilters.scala
  tests/run-custom-args/tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: prio:blocker

#15350 Fix checking ctx to carry correct modes
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
  compiler/src/dotty/tools/dotc/transform/MixinOps.scala
  compiler/src/dotty/tools/dotc/transform/PruneErasedDefs.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/transform/TreeChecker.scala
  compiler/src/dotty/tools/dotc/typer/Nullables.scala
  compiler/src/dotty/tools/dotc/typer/ReTyper.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/explicit-nulls/pos/enums.scala
  tests/explicit-nulls/pos/test-not-null.scala
  tests/explicit-nulls/pos/unsafe-block.scala
  tests/explicit-nulls/pos/unsafe-chain.scala
Labels: area:nullability

#15498 Fix #15494: Handle non-specialized functions in EtaReduce.
  compiler/src/dotty/tools/dotc/transform/EtaReduce.scala
  tests/sjs-junit/test/org/scalajs/testsuite/compiler/RegressionTestScala3.scala
Labels: backport:nominated
