Repository scala/scala3, pull requests merged in 2022-01, with the labels that each got.

#14191 more updates to Markdown files
  docs/docs/reference/changed-features/implicit-conversions-spec.md
  docs/docs/reference/changed-features/implicit-conversions.md
  docs/docs/reference/changed-features/implicit-resolution.md
  docs/docs/reference/changed-features/interpolation-escapes.md
  docs/docs/reference/changed-features/main-functions.md
  docs/docs/reference/changed-features/pattern-bindings.md
  docs/docs/reference/changed-features/structural-types.md
  docs/docs/reference/contextual/context-functions-spec.md
  docs/docs/reference/contextual/givens.md
  docs/docs/reference/dropped-features/delayed-init.md
  docs/docs/reference/dropped-features/package-objects.md
  docs/docs/reference/dropped-features/symlits.md
  docs/docs/reference/experimental/canthrow.md
  docs/docs/reference/experimental/erased-defs-spec.md
  docs/docs/reference/experimental/erased-defs.md
  docs/docs/reference/experimental/named-typeargs-spec.md
  docs/docs/reference/experimental/numeric-literals.md
  docs/docs/reference/language-versions.md
  docs/docs/reference/new-types/intersection-types.md
  docs/docs/reference/new-types/type-lambdas-spec.md
  docs/docs/reference/other-new-features/experimental-defs.md
  docs/docs/reference/other-new-features/explicit-nulls.md
  docs/docs/reference/other-new-features/export.md
  docs/docs/reference/other-new-features/kind-polymorphism.md
  docs/docs/reference/other-new-features/matchable.md
  docs/docs/reference/other-new-features/opaques-details.md
  docs/docs/reference/other-new-features/open-classes.md
  docs/docs/reference/other-new-features/targetName.md
  docs/docs/reference/other-new-features/threadUnsafe-annotation.md
  docs/docs/reference/other-new-features/transparent-traits.md
  docs/docs/reference/other-new-features/type-test.md
  docs/docs/reference/soft-modifier.md
  docs/docs/reference/syntax.md
Labels: area:documentation

#14252 fix 2 problems plus add workaround for #13760
  compiler/src/dotty/tools/MainGenericRunner.scala
  compiler/test-resources/scripting/sqlDateError.sc
  compiler/test/dotty/tools/scripting/BashScriptsTests.scala
Labels: area:scripting

#14163 Shorthand for curried function types
  compiler/src/dotty/tools/dotc/cc/Setup.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/transform/Recheck.scala
  compiler/src/dotty/tools/dotc/typer/CheckCaptures.scala
  tests/disabled/pos/lazylist.scala
  tests/neg-custom-args/captures/class-contra.check
  tests/neg-custom-args/captures/class-contra.scala
  tests/neg-custom-args/captures/curried-simplified.check
  tests/neg-custom-args/captures/curried-simplified.scala
  tests/pos-custom-args/captures/capt-depfun.scala
  tests/pos-custom-args/captures/classes.scala
  tests/pos-custom-args/captures/iterators.scala
  tests/pos-custom-args/captures/lazylists.scala
  tests/pos-custom-args/captures/lazylists1.scala
Labels: cc-experiment

#14336 Fix test output
  compiler/test-resources/repl/i13208.scala
Labels: prio:blocker

#14330 Handle captures in by-name parameters
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/cc/CaptureAnnotation.scala
  compiler/src/dotty/tools/dotc/cc/CaptureOps.scala
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/cc/CapturingKind.scala
  compiler/src/dotty/tools/dotc/cc/CapturingType.scala
  compiler/src/dotty/tools/dotc/cc/Setup.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  library/src-bootstrapped/scala/retainsByName.scala
  tests/neg-custom-args/captures/byname.check
  tests/neg-custom-args/captures/byname.scala
  tests/neg-custom-args/captures/lazylist.check
  tests/neg-custom-args/captures/lazylists2.check
  tests/pos-custom-args/captures/byname.scala
Labels: cc-experiment
