Repository scala/scala3, pull requests merged in 2022-08, with the labels that each got.

#15742 Add missing dealias in isContextFunctionRef
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/pos/i15738.scala
Labels: how-i-fixed-it

#15814 Use fullyDefinedType for mirror synthesis
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/run/i13146.scala
  tests/run/i13146a.scala
  tests/run/i13146poly.scala
Labels: area:typeclass-derivation

#15768 Several fixes to boxing
  compiler/src/dotty/tools/dotc/cc/CaptureAnnotation.scala
  compiler/src/dotty/tools/dotc/cc/CaptureOps.scala
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/cc/CapturingType.scala
  compiler/src/dotty/tools/dotc/cc/Setup.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/TypeApplications.scala
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/transform/Recheck.scala
  compiler/src/dotty/tools/dotc/typer/CheckCaptures.scala
  library/src-bootstrapped/scala/Retains.scala
  library/src-bootstrapped/scala/internal/requiresCapability.scala
  library/src-bootstrapped/scala/retainsByName.scala
  library/src/scala/annotation/capability.scala
  library/src/scala/annotation/internal/CaptureChecked.scala
  tests/neg-custom-args/captures/boxmap.check
  tests/neg-custom-args/captures/boxmap.scala
  tests/neg-custom-args/captures/capt1.check
  tests/neg-custom-args/captures/capt1.scala
  tests/neg-custom-args/captures/curried-simplified.check
  tests/neg-custom-args/captures/eta.scala
  tests/neg-custom-args/captures/i15749.scala
  tests/neg-custom-args/captures/i15749a.scala
  tests/neg-custom-args/captures/i15772.check
  tests/neg-custom-args/captures/i15772.scala
  tests/neg-custom-args/captures/lazylist.check
  tests/neg-custom-args/captures/lazylists2.check
  tests/neg-custom-args/captures/real-try.check
  tests/neg-custom-args/captures/try.check
  tests/neg-custom-args/captures/try.scala
  tests/neg-custom-args/captures/usingLogFile.check
  tests/neg-custom-args/captures/vars.check
  tests/pos-custom-args/bounded1.scala
  tests/pos-custom-args/captures/boxed1.scala
  tests/pos-custom-args/captures/boxmap.scala
  tests/pos-custom-args/captures/lists.scala
  tests/run-custom-args/captures/colltest5/Test_2.scala
  tests/run-custom-args/tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: cc-experiment

#15856 Ignore prototype only for parameterized new
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  tests/pos/i15802.scala
Labels: backport:nominated

#15847 Support Mirror synthesis for local and inner classes
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  compiler/src/dotty/tools/dotc/transform/PostInlining.scala
  compiler/src/dotty/tools/dotc/transform/SymUtils.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  compiler/test/dotc/pos-test-pickling.blacklist
  docs/_docs/reference/contextual/derivation-macro.md
  docs/_docs/reference/contextual/derivation.md
  sbt-test/scala2-compat/i13332/app/App.scala
  sbt-test/scala2-compat/i13332/build.sbt
  sbt-test/scala2-compat/i13332/lib/Lib.scala
  sbt-test/scala2-compat/i13332/test
  tests/neg/anon-mirror-gen-local.scala
  tests/neg/i10997.scala
  tests/neg/i13332shapeless.scala
  tests/pos/i10997.scala
  tests/pos/i11174minimisation.scala
  tests/pos/i13332.scala
  tests/pos/i13332super.scala
  tests/pos/i13935.scala
  tests/run/anon-mirror-gen-local.scala
  tests/run/i11174.scala
  tests/run/i11174local.scala
  tests/run/i12328.scala
  tests/run/i12328a.scala
  tests/run/i12328b.scala
  tests/run/i13332.scala
  tests/run/i13332a.scala
  tests/run/i13332anonprod.scala
  tests/run/i13332intersection.scala
  tests/run/i13332shapeless-b.scala
  tests/run/i13332shapeless.scala
Labels: area:typeclass-derivation
