Repository scala/scala3, pull requests merged in 2022-07, with the labels that each got.

#15530 Fix lifting of arguments with -coverage-out
  compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala
  compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala
  compiler/src/dotty/tools/dotc/transform/localopt/StringInterpolatorOpt.scala
  compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala
  compiler/test/dotty/tools/dotc/coverage/CoverageTests.scala
  tests/coverage/pos/ContextFunctions.scoverage.check
  tests/coverage/run/erased/test.check
  tests/coverage/run/erased/test.scala
  tests/coverage/run/erased/test.scoverage.check
  tests/coverage/run/interpolation/test.check
  tests/coverage/run/interpolation/test.scala
  tests/coverage/run/interpolation/test.scoverage.check
  tests/coverage/run/lifting-bool/test.check
  tests/coverage/run/lifting-bool/test.scala
  tests/coverage/run/lifting-bool/test.scoverage.check
  tests/coverage/run/varargs/JavaVarargs_1.java
  tests/coverage/run/varargs/test_1.check
  tests/coverage/run/varargs/test_1.scala
  tests/coverage/run/varargs/test_1.scoverage.check
Labels: how-i-fixed-it

#15529 Ignore types in macro runtime dependencies
  compiler/src/dotty/tools/dotc/inlines/Inliner.scala
  tests/pos-macros/i12498/Macro_1.scala
  tests/pos-macros/i12498/Test_2.scala
  tests/pos-macros/i12498a/Macro_1.scala
  tests/pos-macros/i12498a/Test_2.scala
  tests/pos-macros/i12498b/Macro_1.scala
  tests/pos-macros/i12498b/Test_2.scala
  tests/pos-macros/i12498c/Macro_1.scala
  tests/pos-macros/i12498c/Test_2.scala
Labels: how-i-fixed-it

#15499 Fix #15199: Exclude JavaDefined Modules from bridge generation.
  compiler/src/dotty/tools/dotc/transform/Bridges.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  tests/run/i15199/Child_1.java
  tests/run/i15199/Parent_1.java
  tests/run/i15199/Test_2.scala
Labels: how-i-fixed-it

#15590 Ignore one new test with Java source files for Scala.js.
  tests/run/i15199/Test_2.scala
Labels: fasttrack

#15651 Refutable extractor may be an Apply tree
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  tests/pos/i15650.scala
Labels: backport:nominated

#15658 Harden erasure of TermRefs
  compiler/src/dotty/tools/dotc/core/TypeErasure.scala
  tests/pos/i15649.scala
Labels: backport:nominated

#15675 Survive TypeErrors in isMatchedBy
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  tests/pos/i15673.scala
Labels: how-i-fixed-it

#15739 Keep 'fun' and 'args' together when instrumenting TypeApply for coverage
  compiler/src/dotty/tools/dotc/transform/InstrumentCoverage.scala
  tests/coverage/pos/PolymorphicExtensions.scala
  tests/coverage/pos/PolymorphicExtensions.scoverage.check
  tests/coverage/pos/PolymorphicMethods.scala
  tests/coverage/pos/PolymorphicMethods.scoverage.check
Labels: backport:nominated
