Repository scala/scala3, pull requests merged in 2023-06, with the labels that each got.

#17615 Dealias types in New before matching quotes
  compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala
  tests/pos-macros/i17606/Macros_1.scala
  tests/pos-macros/i17606/Test_2.scala
Labels: backport:nominated

#17987 Categorize stdlib-bootstrapped TASTy-MiMa issues
  project/TastyMiMaFilters.scala
Labels: fasttrack

#17362 SIP-53 - Quote pattern explicit type variable syntax
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  docs/_docs/reference/metaprogramming/macros.md
  docs/_docs/reference/syntax.md
  tests/neg-custom-args/no-experimental/sip-53-exprimental-a.scala
  tests/neg-custom-args/no-experimental/sip-53-exprimental-b.scala
  tests/neg-macros/quote-pattern-type-var-bounds.scala
  tests/neg-macros/quote-type-variable-no-inference.check
  tests/neg-macros/quote-type-variable-no-inference.scala
  tests/neg-macros/quotedPatterns-5.scala
  tests/pos-macros/i10864/Macro_1.scala
  tests/pos-macros/i10864/Test_2.scala
  tests/pos-macros/i10864a/Macro_1.scala
  tests/pos-macros/i10864a/Test_2.scala
  tests/pos-macros/i11738.scala
  tests/pos-macros/i7264.scala
  tests/pos-macros/multiline-quote-patterns.scala
  tests/pos-macros/quote-pattern-type-variable-no-escape.scala
Labels: release-notes

#18033 Fix tests/pos-macros/i10864a
  tests/pos-macros/i10864a/Macro_1.scala
Labels: prio:blocker, fasttrack

#17754 Fix crash reporter, units and phases
  compiler/src/dotty/tools/dotc/Run.scala
  compiler/src/dotty/tools/dotc/core/Phases.scala
  compiler/src/dotty/tools/dotc/report.scala
  compiler/src/dotty/tools/dotc/transform/TreeChecker.scala
  compiler/src/dotty/tools/dotc/typer/ReTyper.scala
  compiler/src/dotty/tools/dotc/typer/TyperPhase.scala
Labels: backport:nominated

#18041 Value parameter inference for polymorphic lambdas
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/polymorphic-functions2.scala
  tests/run/polymorphic-functions.scala
Labels: release-notes
