Repository scala/scala3, pull requests merged in 2023-11, with the labels that each got.

#18803 Completions should prepend, not replace as it is for Scala 2
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionPos.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionProvider.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSuite.scala
Labels: backport:nominated, area:presentation-compiler

#18618 error when reading class file with unknown newer jdk version
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileTastyUUIDParser.scala
Labels: backport:nominated

#18828 Improve error message for mismatched tasty versions, allow configuration of header unpickler
  compiler/src/dotty/tools/backend/jvm/CodeGen.scala
  compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyUnpickler.scala
  compiler/test/dotty/tools/dotc/core/tasty/TastyHeaderUnpicklerTest.scala
  tasty/src/dotty/tools/tasty/TastyHeaderUnpickler.scala
  tasty/test/dotty/tools/tasty/TastyHeaderUnpicklerTest.scala
  tests/pos-with-compiler-cc/backend/jvm/GenBCode.scala
Labels: backport:nominated

#18599 Add attributes section to TASTy and use it for Stdlib TASTy
  compiler/src/dotty/tools/dotc/core/Flags.scala
  compiler/src/dotty/tools/dotc/core/tasty/AttributePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/AttributeUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/Attributes.scala
  compiler/src/dotty/tools/dotc/core/tasty/DottyUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/ScratchData.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyPrinter.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/transform/ExtensionMethods.scala
  compiler/src/dotty/tools/dotc/transform/Pickler.scala
  scala2-library-tasty-tests/src/Main.scala
  tasty/src/dotty/tools/tasty/TastyFormat.scala
Labels: release-notes, needs-minor-release

#18738 Fix `callTrace` of inlined methods
  .github/workflows/ci.yaml
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/inlines/Inlines.scala
  compiler/src/dotty/tools/dotc/transform/PickleQuotes.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/YCheckPositions.scala
Labels: needs-minor-release

#18826 Enter missing symbols generated by the MacroAnnotation expansion
  compiler/src/dotty/tools/dotc/transform/Inlining.scala
  compiler/src/dotty/tools/dotc/transform/MacroAnnotations.scala
  tests/neg-macros/i18825.check
  tests/neg-macros/i18825/Macro_1.scala
  tests/neg-macros/i18825/Test_2.scala
  tests/neg-macros/wrong-owner.check
  tests/neg-macros/wrong-owner/Macro_1.scala
  tests/neg-macros/wrong-owner/Test_2.scala
  tests/run-macros/i18806.check
  tests/run-macros/i18806/Macro_1.scala
  tests/run-macros/i18806/Test_2.scala
  tests/run/quotes-add-erased/Macro_1.scala
Labels: area:metaprogramming:macro-annotations

#18872 Deprecation warnings for old syntax: `xs: _*` varargs
  community-build/src/scala/dotty/communitybuild/projects.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  sbt-bridge/test/xsbt/ScalaCompilerForUnitTesting.scala
  tests/neg/i18862-3.4.check
  tests/neg/i18862-3.4.scala
  tests/neg/i18862-future-migration.scala
  tests/neg/i18862-future.scala
  tests/patmat/exhaustive_heuristics.scala
  tests/semanticdb/metac.expect
Labels: release-notes

#18821 Deprecation warnings for old syntax: `var x = _`
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/test/dotty/tools/languageserver/util/PositionContext.scala
  language-server/test/dotty/tools/languageserver/util/server/TestServer.scala
  library/src/scala/util/control/NonLocalReturns.scala
  presentation-compiler/src/main/dotty/tools/pc/MetalsDriver.scala
  project/Build.scala
  sbt-test/compilerReporter/i14576/Test.scala
  sbt-test/compilerReporter/i14576/build.sbt
  tests/neg/i4812.scala
  tests/neg/uninitialized-3.4.check
  tests/neg/uninitialized-3.4.scala
  tests/neg/uninitialized-future-migration.scala
  tests/neg/uninitialized-future.scala
  tests/patmat/i12805-fallout.scala
  tests/pos/uninitialized-future-migration.scala
  tests/rewrites/uninitialized-var.check
  tests/rewrites/uninitialized-var.scala
Labels: release-notes

#18893 Also add privateWithin when creating constructor proxies
  compiler/src/dotty/tools/dotc/core/NamerOps.scala
  tests/neg/i18545.check
  tests/neg/i18545.scala
Labels: how-i-fixed-it

#18571 Add `-experimental` compiler flags
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/plugins/Plugins.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  docs/_docs/reference/changed-features/compiler-plugins.md
  docs/_docs/reference/experimental/overview.md
  docs/_docs/reference/other-new-features/experimental-defs.md
  tests/neg/expeimental-flag-with-lang-feature-1.scala
  tests/neg/expeimental-flag-with-lang-feature-2.scala
  tests/neg/expeimental-flag.scala
  tests/pos/expeimental-flag-with-lang-feature.scala
  tests/pos/expeimental-flag.scala
Labels: release-notes, needs-minor-release

#18780 Improve type inference for functions like fold
  compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/transform/TypeUtils.scala
  compiler/src/dotty/tools/dotc/typer/Inferencing.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/foldinf-ill-kinded.check
  tests/neg/foldinf-ill-kinded.scala
  tests/pos/folds.scala
Labels: release-notes

#18928 Encode the name of the attribute in Selectable.selectDynamic
  compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala
  library/src/scala/reflect/Selectable.scala
  tests/run/i18612-a.scala
  tests/run/i18612-b.scala
  tests/run/i18612-c.scala
  tests/run/i18612-d.scala
Labels: area:library

#18926 Deprecation warning for trailing `_` to force eta expansion
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  tests/neg/i18867-3.4.scala
  tests/neg/i18867.check
  tests/neg/i18867.scala
  tests/patmat/dotty.scala
  tests/pos/i18867-3.3.scala
  tests/pos/i18867-3.4.scala
  tests/rewrites/rewrites3x.check
  tests/rewrites/rewrites3x.scala
Labels: release-notes

#18920 Disallow use of PolyFunction in user code
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  tests/neg/erased-15.scala
  tests/neg/i10075.check
  tests/neg/i10075.scala
  tests/neg/i10369.scala
  tests/neg/i18302a.scala
  tests/neg/i18302b.check
  tests/neg/i18302b.scala
  tests/neg/i18302c.check
  tests/neg/i18302c.scala
  tests/neg/i18302d.check
  tests/neg/i18302d.scala
  tests/neg/i18302e.check
  tests/neg/i18302e.scala
  tests/neg/i18302f.check
  tests/neg/i18302f.scala
  tests/neg/i18302j.scala
  tests/pos/i10369.scala
  tests/run/erased-15.check
Labels: release-notes

#18955 presentation compiler: Bugfix for semantic tokens and synthetic decorations
  presentation-compiler/src/main/dotty/tools/pc/PcSemanticTokensProvider.scala
  presentation-compiler/src/main/dotty/tools/pc/PcSyntheticDecorationProvider.scala
  presentation-compiler/test/dotty/tools/pc/tests/decorations/SyntheticDecorationsSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/tokens/SemanticTokensSuite.scala
Labels: backport:nominated, area:presentation-compiler
