Repository scala/scala3, pull requests merged in 2023-07, with the labels that each got.

#18134 Add clause for protected visibility from package objects
  community-build/test/scala/dotty/communitybuild/CommunityBuildTest.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  tests/pos/i18124/definition.scala
  tests/pos/i18124/usage.scala
Labels: backport:nominated

#16769 minor improvements to developer docs for Scaladoc tool
  docs/_docs/contributing/scaladoc.md
  docs/_docs/contributing/sending-in-a-pr.md
  docs/_docs/contributing/testing.md
Labels: area:documentation, area:doctool

#18208 Update link to point to correct section
  docs/_docs/reference/experimental/erased-defs.md
Labels: area:documentation

#18131 Change handling of curried function types in capture checking
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/cc/CheckCaptures.scala
  compiler/src/dotty/tools/dotc/cc/Setup.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/transform/Recheck.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg-custom-args/captures/curried-simplified.check
  tests/neg-custom-args/captures/curried-simplified.scala
  tests/neg-custom-args/captures/leaked-curried.check
  tests/neg-custom-args/captures/leaked-curried.scala
  tests/neg-custom-args/captures/singletons.scala
  tests/pos-custom-args/captures/curried-closures.scala
  tests/pos-custom-args/captures/dependent-pure.scala
  tests/pos-custom-args/captures/i13816.scala
Labels: cc-experiment

#18190 Improve parameter type inference error messaging
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i11350.check
  tests/neg/i11561.check
  tests/neg/i17183.check
Labels: Spree

#18235 Improve handling of AndTypes on the LHS of subtype comparisons
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  tests/neg-custom-args/allow-deep-subtypes/i5877.scala
  tests/pos/i12077.scala
  tests/pos/i18226.scala
  tests/pos/i18226a.scala
  tests/pos/intersection.scala
Labels: how-i-fixed-it

#18268 don't disable all scalacOptions, only Ysafe-init and Xcheck-macros
  community-build/src/scala/dotty/communitybuild/projects.scala
Labels: area:community build

#18133 Compile quote patterns directly into QuotePattern AST
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/quoted/QuotePatterns.scala
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  tests/neg-macros/i16522.check
  tests/neg-macros/i16522.scala
  tests/neg-macros/i6997b.scala
  tests/pos-macros/i14708.scala
  tests/pos-macros/i16522.scala
  tests/pos-macros/i18125.scala
  tests/pos-macros/i18125b.scala
  tests/pos-macros/i18250.scala
  tests/pos-macros/mirrorQuotePattern.scala
  tests/pos-macros/mirrorQuotePattern2.scala
Labels: backport:nominated

#18288 Do not compute `protoFormal` if `param.tpt` is empty
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/pos/i18276a.scala
  tests/pos/i18276b.scala
Labels: backport:nominated

#18141 add test for issue #17997 affecting the global object initialization checker
  compiler/src/dotty/tools/dotc/transform/init/Objects.scala
  tests/init-global/pos/i17997-2.scala
  tests/init-global/pos/i17997.scala
Labels: area:initialization

#18299 fix #18282: consider Predef.eq/ne in nullability flow typing
  compiler/src/dotty/tools/dotc/typer/Nullables.scala
  tests/explicit-nulls/pos/flow-predef-eq.scala
Labels: area:nullability

#18310 Make incremental compilation aware of synthesized mirrors
  compiler/src/dotty/tools/dotc/CompilationUnit.scala
  compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala
  compiler/src/dotty/tools/dotc/sbt/ExtractDependencies.scala
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  sbt-test/source-dependencies/mirror-product/MyProduct.scala
  sbt-test/source-dependencies/mirror-product/Test.scala
  sbt-test/source-dependencies/mirror-product/build.sbt
  sbt-test/source-dependencies/mirror-product/changes/MyProduct.scala
  sbt-test/source-dependencies/mirror-product/test
  sbt-test/source-dependencies/mirror-sum/Sum.scala
  sbt-test/source-dependencies/mirror-sum/Test.scala
  sbt-test/source-dependencies/mirror-sum/build.sbt
  sbt-test/source-dependencies/mirror-sum/changes/Sum.scala
  sbt-test/source-dependencies/mirror-sum/test
  sbt-test/source-dependencies/useOptimizedSealed/Sealed.scala
  sbt-test/source-dependencies/useOptimizedSealed/Test.scala
  sbt-test/source-dependencies/useOptimizedSealed/build.sbt
  sbt-test/source-dependencies/useOptimizedSealed/changes/Sealed1.scala
  sbt-test/source-dependencies/useOptimizedSealed/changes/Sealed2.scala
  sbt-test/source-dependencies/useOptimizedSealed/changes/Test1.scala
  sbt-test/source-dependencies/useOptimizedSealed/project/CompileState.scala
  sbt-test/source-dependencies/useOptimizedSealed/test
Labels: backport:nominated

#16974 Add reflect.ValOrDefDef
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/pos-macros/i16960/Macro_1.scala
  tests/pos-macros/i16960/Test_2.scala
Labels: needs-minor-release
