Repository scala/scala3, pull requests merged in 2023-08, with the labels that each got.

#18317 Reimplement support for type aliases in SAM types
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/transform/ExpandSAMs.scala
  tests/run/i18315.scala
Labels: backport:nominated

#18332 Fix BuildInfo scope in `scala3-presentation-compiler`, improve debugging support
  docs/_assets/images/contribution/debug-test-code-lens.jpg
  docs/_assets/images/contribution/debug-test-explorer.jpg
  docs/_docs/contributing/debugging/ide-debugging.md
  presentation-compiler/src/main/dotty/tools/pc/ScalaPresentationCompiler.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/Completions.scala
  presentation-compiler/test/dotty/tools/pc/base/BasePCSuite.scala
  project/Build.scala
Labels: backport:nominated

#17470 Fix #17467: Limit isNullable widening to stable TermRefs; remove under explicit nulls.
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  tests/explicit-nulls/neg/i17467.check
  tests/explicit-nulls/neg/i17467.scala
  tests/neg/i17467.check
  tests/neg/i17467.scala
  tests/run/t6443b.scala
Labels: area:nullability, needs-minor-release

#18347 Update presentation compiler to a829a6a
  presentation-compiler/src/main/dotty/tools/pc/HoverProvider.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/Completions.scala
  presentation-compiler/src/main/dotty/tools/pc/utils/MtagsEnrichments.scala
  presentation-compiler/test/dotty/tools/pc/tests/hover/HoverDocSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/hover/HoverTypeSuite.scala
  presentation-compiler/test/dotty/tools/pc/utils/MockEntries.scala
Labels: backport:nominated

#17298 Add new EXPLICITtpt to TASTy format
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  project/MiMaFilters.scala
  tasty/src/dotty/tools/tasty/TastyFormat.scala
  tests/pos-macros/captured-type/Macro_1.scala
  tests/pos-macros/captured-type/Test_2.scala
Labels: needs-minor-release

#18303 Fix regression in exhausitivity of HK types
  compiler/src/dotty/tools/dotc/transform/patmat/Space.scala
  tests/neg-custom-args/fatal-warnings/suppressed-type-test-warnings.scala
  tests/neg-custom-args/isInstanceOf/enum-approx2.scala
  tests/neg-custom-args/isInstanceOf/i11178.scala
  tests/neg-custom-args/isInstanceOf/i8932.scala
  tests/pending/neg/i16451.check
  tests/pending/neg/i16451.scala
  tests/pos/i17230.bootstrap.scala
  tests/pos/i17230.min1.scala
  tests/pos/i17230.orig.scala
Labels: backport:nominated

#18269 Record failures to adapt application arguments
  compiler/src/dotty/tools/dotc/core/OrderingConstraint.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/printing/Printer.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  presentation-compiler/test/dotty/tools/pc/tests/hover/HoverTypeSuite.scala
  tests/neg-macros/i16522.check
  tests/neg-macros/i16522.scala
  tests/neg-macros/i6762.scala
  tests/neg/enum-values.check
  tests/neg/enumsAccess.scala
  tests/neg/i6779.check
  tests/neg/recursive-lower-constraint.scala
  tests/neg/syntax-error-recovery.check
  tests/neg/syntax-error-recovery.scala
  tests/pos/i18163.orig.scala
  tests/pos/i18163.scala
Labels: backport:nominated

#18359 Fix owner of splices in class statements
  compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala
  tests/pos-macros/i18358/Macro_1.scala
  tests/pos-macros/i18358/Test_2.scala
Labels: backport:nominated

#18379 bugfix: suggest correct arg name completions for lambda expressions
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionValue.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/NamedArgCompletions.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionArgSuite.scala
Labels: backport:nominated, area:presentation-compiler

#18380 improvement: print better bracket suffix in completion item label
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionSuffix.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionValue.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/Completions.scala
  presentation-compiler/src/main/dotty/tools/pc/printer/ShortenedTypePrinter.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionWorkspaceSuite.scala
Labels: backport:nominated, area:presentation-compiler

#18412 Keep tree of type ascriptions of quote pattern splices
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/patmat/Space.scala
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  tests/neg-macros/quote-type-variable-no-inference-2.check
  tests/neg-macros/quote-type-variable-no-inference-3.check
  tests/neg-macros/quote-type-variable-no-inference.check
  tests/neg-macros/quote-type-variable-no-inference.scala
  tests/pos-macros/i18409.scala
Labels: backport:nominated

#18405 Improve non-static macro implementation error message
  compiler/src/dotty/tools/dotc/transform/Splicer.scala
  tests/neg-macros/i15413.check
  tests/neg-macros/i15413.scala
Labels: backport:nominated

#18430 fix: Don't collect map, flatMap, withFilter in for-comprehension
  presentation-compiler/src/main/dotty/tools/pc/PcCollector.scala
  presentation-compiler/test/dotty/tools/pc/tests/edit/PcRenameSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/highlight/DocumentHighlightSuite.scala
Labels: backport:nominated, area:presentation-compiler
