Repository scala/scala3, pull requests merged in 2023-12, with the labels that each got.

#18948 Store source file in TASTY attributes
  compiler/src/dotty/tools/dotc/core/Annotations.scala
  compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  compiler/src/dotty/tools/dotc/core/tasty/AttributePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/AttributeUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/Attributes.scala
  compiler/src/dotty/tools/dotc/core/tasty/DottyUnpickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/NameBuffer.scala
  compiler/src/dotty/tools/dotc/core/tasty/TastyPrinter.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/fromtasty/ReadTasty.scala
  compiler/src/dotty/tools/dotc/quoted/PickledQuotes.scala
  compiler/src/dotty/tools/dotc/transform/Pickler.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/test/dotty/tools/dotc/core/tasty/CommentPicklingTest.scala
  tasty/src/dotty/tools/tasty/TastyFormat.scala
Labels: release-notes, needs-minor-release

#17189 Allow Tuple.Head and Tuple.Tail to work with EmptyTuple
  compiler/test/dotc/pos-test-pickling.blacklist
  library/src/scala/Tuple.scala
  tests/pos/i11982a.scala
  tests/pos/i17186a.scala
  tests/pos/i17186b.scala
Labels: needs-minor-release

#19250 Avoid crashes on missing positions
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
Labels: backport:nominated

#19288 Fix #19286: Freeze rubygems-update at < 3.5.0.
  .github/workflows/spec.yml
Labels: area:infrastructure, fasttrack

#18402 Add `@publicInBinary` annotation and `-WunstableInlineAccessors` linting flag
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/inlines/PrepareInlineable.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/transform/AccessProxies.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/ProtectedAccessors.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala
  compiler/test-resources/repl/i15493
  compiler/test/dotty/tools/backend/jvm/PublicInBinaryTests.scala
  library/src/scala/annotation/publicInBinary.scala
  tests/neg/inline-unstable-accessors.check
  tests/neg/inline-unstable-accessors.scala
  tests/neg/publicInBinary-not-accessible.check
  tests/neg/publicInBinary-not-accessible.scala
  tests/neg/publicInBinary.check
  tests/neg/publicInBinary.scala
  tests/pos-macros/i15413/Macro_1.scala
  tests/pos-macros/i15413/Test_2.scala
  tests/pos-macros/i15413b/Macro_1.scala
  tests/pos-macros/i15413b/Test_2.scala
  tests/pos-special/fatal-warnings/i17735.scala
  tests/pos-special/fatal-warnings/i17735a.scala
  tests/pos-special/fatal-warnings/i17741.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
  tests/run/i13215.scala
  tests/run/noProtectedSuper.scala
  tests/run/publicInBinary/Lib_1.scala
  tests/run/publicInBinary/Test_2.scala
Labels: release-notes, needs-minor-release

#19082 Add support for @deprecatedInheritance
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/interactive/InteractiveDriver.scala
  compiler/src/dotty/tools/dotc/reporting/Message.scala
  compiler/src/dotty/tools/dotc/rewrites/Rewrites.scala
  compiler/src/dotty/tools/dotc/semanticdb/SemanticSymbolBuilder.scala
  compiler/src/dotty/tools/dotc/transform/CountOuterAccesses.scala
  compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/CrossVersionChecks.scala
  compiler/src/dotty/tools/dotc/util/Stats.scala
  tests/init/pos/patternMatcher.scala
  tests/warn/i19002.check
  tests/warn/i19002.scala
Labels: release-notes

#19314 improvement: Support completions for implicit classes
  presentation-compiler/src/main/dotty/tools/pc/CompilerSearchVisitor.scala
  presentation-compiler/src/main/dotty/tools/pc/SemanticdbSymbols.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionProvider.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionValue.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/Completions.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionExtensionSuite.scala
Labels: backport:nominated, area:presentation-compiler
