Repository scala/scala3, pull requests merged in 2023-02, with the labels that each got.

#16759 Fix Scaladoc crash when extending non-Scala-3 classes (short-term fix for 3.3.x)
  scaladoc-testcases/src/tests/nonScala3Parent.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala
  scaladoc/test/dotty/tools/scaladoc/signatures/TranslatableSignaturesTestCases.scala
Labels: backport:nominated

#16799 Restrict captureWildcards to only be used if needed
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/t9419.zio-http.scala
  tests/pos/t9419.specs2.scala
Labels: backport:nominated

#16800 Fix static lazy field holder for GraalVM
  bench-micro/src/main/scala/dotty/tools/benchmarks/lazyvals/InitializedAccessInt.scala
  bench-micro/src/main/scala/dotty/tools/benchmarks/lazyvals/InitializedObject.scala
  bench-micro/src/main/scala/dotty/tools/benchmarks/lazyvals/LazyVals.scala
  compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala
  compiler/src/dotty/tools/backend/jvm/DottyBackendInterface.scala
  compiler/src/dotty/tools/dotc/transform/LazyVals.scala
  tests/printing/transformed/lazy-vals-new.check
Labels: backport:nominated

#16810 Add support for disabling redirected output in the REPL driver for usage in worksheets in the Scala Plugin for IntelliJ IDEA
  compiler/src/dotty/tools/repl/ReplDriver.scala
Labels: backport:nominated

#16837 fix: ensure syntax blocks for ebnf are marked as such
  docs/_docs/reference/changed-features/imports.md
  docs/_docs/reference/changed-features/match-syntax.md
  docs/_docs/reference/changed-features/pattern-bindings.md
  docs/_docs/reference/changed-features/structural-types-spec.md
  docs/_docs/reference/changed-features/vararg-splices.md
  docs/_docs/reference/contextual/context-bounds.md
  docs/_docs/reference/contextual/context-functions-spec.md
  docs/_docs/reference/contextual/derivation.md
  docs/_docs/reference/contextual/extension-methods.md
  docs/_docs/reference/contextual/given-imports.md
  docs/_docs/reference/contextual/givens.md
  docs/_docs/reference/contextual/using-clauses.md
  docs/_docs/reference/enums/adts.md
  docs/_docs/reference/experimental/named-typeargs-spec.md
  docs/_docs/reference/metaprogramming/macros-spec.md
  docs/_docs/reference/metaprogramming/simple-smp.md
  docs/_docs/reference/new-types/dependent-function-types-spec.md
  docs/_docs/reference/new-types/intersection-types-spec.md
  docs/_docs/reference/new-types/type-lambdas-spec.md
  docs/_docs/reference/other-new-features/export.md
  docs/_docs/reference/other-new-features/indentation.md
  docs/_docs/reference/other-new-features/opaques-details.md
Labels: area:documentation

#16839 Apply `class-shadowing.md` to the Spec
  docs/_spec/05-classes-and-objects.md
  docs/_spec/APPLIEDreference/dropped-features/class-shadowing.md
  docs/_spec/TODOreference/dropped-features/class-shadowing-spec.md
Labels: area:specification

#16854 Print owner of bind symbol with -Yprint-debug-owners
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
Labels: fasttrack

#16870 Fix comment test number
  compiler/src/dotty/tools/dotc/typer/Namer.scala
Labels: area:testing

#16889 Add missing criterion to subtype check
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  tests/neg/i16850.check
  tests/neg/i16850.scala
Labels: backport:accepted

#17001 add regression test for pattern match on path-dependent type
  tests/pos/t16827.scala
Labels: area:pattern-matching

#16989 Fix caching issue caused by incorrect isProvisional check
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/pos/i16950.scala
Labels: backport:nominated

#16975 Fix race condition in new LazyVals
  library/src/scala/runtime/LazyVals.scala
  project/MiMaFilters.scala
  tests/run/i16806.check
  tests/run/i16806.scala
Labels: backport:accepted
