Repository scala/scala3, pull requests merged in 2023-01, with the labels that each got.

#16589 Reset after git bisect in script
  project/scripts/bisect.scala
Labels: fasttrack

#16140 Refine append return type
  library/src/scala/Tuple.scala
Labels: needs-minor-release

#16754 Don't generate a Select for a TermRef with NoPrefix
  compiler/src/dotty/tools/dotc/ast/TreeTypeMap.scala
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
  tests/pos/i16740.scala
Labels: how-i-fixed-it
