Repository scala/scala3, pull requests merged in 2023-09, with the labels that each got.

#18502 bugfix: Catch exception from the compiler for broken shadowed pickles
  presentation-compiler/src/main/dotty/tools/pc/CompilerSearchVisitor.scala
Labels: backport:nominated, area:presentation-compiler

#18354 Add missing span to synthesized product mirror
  compiler/src/dotty/tools/dotc/typer/Synthesizer.scala
  tests/pos-macros/i18353/Macro_1.scala
  tests/pos-macros/i18353/Test_2.scala
Labels: backport:nominated

#17341 bugfix: in semanticdb make synthetic apply disambiguator consistent w/ Scala 2 implicit
  compiler/src/dotty/tools/dotc/semanticdb/SemanticSymbolBuilder.scala
  tests/semanticdb/expect/CaseClass.expect.scala
  tests/semanticdb/expect/CaseClass.scala
  tests/semanticdb/expect/Enums.expect.scala
  tests/semanticdb/expect/Enums.scala
  tests/semanticdb/expect/Givens.expect.scala
  tests/semanticdb/expect/Givens.scala
  tests/semanticdb/metac.expect
Labels: backport:nominated

#18557 Add missing span to extension method select
  compiler/src/dotty/tools/dotc/inlines/Inliner.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/dotty/tools/dotc/typer/ImportSuggestions.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  presentation-compiler/test/dotty/tools/pc/tests/definition/PcDefinitionSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/highlight/DocumentHighlightSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/hover/HoverTypeSuite.scala
  tests/semanticdb/expect/Extension.expect.scala
  tests/semanticdb/expect/Extension.scala
  tests/semanticdb/metac.expect
Labels: backport:nominated

#18576 bugfix: Incorrect semanticdb span on Selectable
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/semanticdb/ExtractSemanticDB.scala
  tests/semanticdb/expect/Givens.expect.scala
  tests/semanticdb/expect/ImplicitConversion.expect.scala
  tests/semanticdb/expect/StructuralTypes.expect.scala
  tests/semanticdb/expect/StructuralTypes.scala
  tests/semanticdb/metac.expect
Labels: backport:nominated

#18013 Intrinsify `constValueTuple` and `summonAll`
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/inlines/Inliner.scala
  compiler/src/dotty/tools/dotc/inlines/Inlines.scala
  library/src/scala/compiletime/package.scala
  tests/neg/17211.check
  tests/neg/i14177a.scala
  tests/run/i15988a.scala
  tests/run/i15988b.scala
Labels: needs-minor-release

#18594 bugfix: No signature help for local methods
  compiler/src/dotty/tools/dotc/util/Signatures.scala
  presentation-compiler/test/dotty/tools/pc/tests/signaturehelp/SignatureHelpSuite.scala
Labels: backport:nominated, area:presentation-compiler

#18620 bugfix: add `moduleClass` imported symbols in `IndexedContext`
  presentation-compiler/src/main/dotty/tools/pc/IndexedContext.scala
Labels: backport:nominated, area:presentation-compiler
