Repository scala/scala3, pull requests merged in 2023-10, with the labels that each got.

#18206 allow nullability flow typing even in presence of pattern match
  compiler/src/dotty/tools/dotc/typer/Nullables.scala
  tests/explicit-nulls/pos/match-flow-typing.scala
Labels: area:nullability

#18212 fix #11967: flow typing nullability in pattern matches
  compiler/src/dotty/tools/dotc/typer/Nullables.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/explicit-nulls/neg/flow-match.scala
  tests/explicit-nulls/pos/flow-match.scala
Labels: area:nullability

#18331 Support completions for extension definition parameter
  compiler/src/dotty/tools/dotc/interactive/Completion.scala
  compiler/src/dotty/tools/repl/ReplCompiler.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test/dotty/tools/repl/TabcompleteTests.scala
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/Completions.scala
  presentation-compiler/src/main/dotty/tools/pc/printer/ShortenedTypePrinter.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionWorkspaceSuite.scala
Labels: backport:nominated, area:presentation-compiler

#17441 Make SIP 54 (Multi-Source Extension Overloads) a standard feature
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/_docs/reference/contextual/extension-methods.md
  library/src/scala/runtime/stdLibPatches/language.scala
  tests/neg/i13558.scala
  tests/neg/i16920.check
  tests/neg/i16920.scala
  tests/neg/sip54.check
  tests/neg/sip54.scala
  tests/pos/i13558.scala
  tests/pos/i16920.scala
Labels: stat:do not merge

#18615 Rename `stdlib-bootstrapped-tasty` to `scala2-library-tasty`
  .github/workflows/ci.yaml
  build.sbt
  compiler/src/dotty/tools/dotc/sbt/ExtractDependencies.scala
  project/Build.scala
  project/TastyMiMaFilters.scala
  project/scripts/cmdScaladocTests
  project/scripts/scala2-library-tasty-mima.sh
  scala2-library-tasty-tests/src/Main.scala
  scala2-library-tasty-tests/src/UnrolledBufferTest.scala
  scala2-library-tasty-tests/test/BootstrappedStdLibTASYyTest.scala
Labels: area:infrastructure

#18613 Use -Ystdlib to add Scala 2 lib TASTY to scalac (internal only)
  project/Build.scala
Labels: area:infrastructure

#18480 Stabilize Quotes `defn.PolyFunction`
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: release-notes

#18482 Stabilize quotes `Flags.AbsOverride`
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: release-notes

#18574 Stabilize SIP-53 (quote pattern explicit type variable syntax)
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  tests/neg/sip-53-exprimental-a.scala
  tests/neg/sip-53-exprimental-b.scala
Labels: release-notes

#18633 bugfix: Named args completions with default values
  presentation-compiler/src/main/dotty/tools/pc/completions/NamedArgCompletions.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionArgSuite.scala
Labels: backport:nominated, area:presentation-compiler

#18667 fix: match completions for type aliases
  presentation-compiler/src/main/dotty/tools/pc/completions/MatchCaseCompletions.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionCaseSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionMatchSuite.scala
Labels: backport:nominated, area:presentation-compiler

#18717 Don't emit line number for synthetic unit value
  compiler/src/dotty/tools/backend/jvm/BCodeSkelBuilder.scala
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/inlines/Inliner.scala
  compiler/src/dotty/tools/dotc/inlines/Inlines.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/transform/DropBreaks.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
  compiler/src/dotty/tools/dotc/transform/Memoize.scala
  compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala
  compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotty/tools/backend/jvm/DottyBytecodeTests.scala
Labels: backport:nominated

#18700 Improve assertion error message for `Apply` and `TypeApply`
  compiler/src/dotty/tools/dotc/ast/tpd.scala
Labels: backport:nominated

#18583 Add reflect TypeRepr.dealiasKeepOpaques
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/run-macros/tasty-dealiasKeepOpaques.check
  tests/run-macros/tasty-dealiasKeepOpaques/Macro_1.scala
  tests/run-macros/tasty-dealiasKeepOpaques/Test_2.scala
Labels: release-notes

#18665 Add better explanation to error message
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i18657.check
  tests/neg/i18657.scala
Labels: how-i-fixed-it

#18753 better explain message for 'pattern expected'
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  tests/neg/i18750-format.check
  tests/neg/i18750-format.scala
Labels: area:reporting, better-errors

#18758 Fix potential soundness hole when adding references to a mapped capture set
  compiler/src/dotty/tools/dotc/cc/CaptureOps.scala
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/config/Config.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
Labels: cc-experiment
