Repository scala/scala3, pull requests merged in 2024-01, with the labels that each got.

#19361 Update copyright year in cmdScaladocTests
  project/scripts/cmdScaladocTests
Labels: prio:blocker

#19399 Remove `ascriptionVarargsUnpacking` as we never used it
  compiler/src/dotty/tools/dotc/config/Feature.scala
  library/src/scala/runtime/stdLibPatches/language.scala
Labels: backport:nominated

#19316 Make explicit arguments for context bounds an error from 3.5
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/DesugarEnums.scala
  compiler/src/dotty/tools/dotc/config/MigrationVersion.scala
  compiler/src/dotty/tools/dotc/config/SourceVersion.scala
  compiler/src/dotty/tools/dotc/typer/Migrations.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/warn/context-bounds-migration.scala
Labels: backport:nominated

#19410 chore: Backport changes from Metals
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  presentation-compiler/src/main/dotty/tools/pc/CompilerSearchVisitor.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/CompletionPos.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/Completions.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/InterpolatorCompletions.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/NamedArgCompletions.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionArgSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionKeywordSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionPatternSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSnippetSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/highlight/DocumentHighlightSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/hover/HoverTermSuite.scala
  presentation-compiler/test/dotty/tools/pc/tests/tokens/SemanticTokensSuite.scala
  presentation-compiler/test/dotty/tools/pc/utils/MockSymbolSearch.scala
  project/Build.scala
Labels: backport:nominated, area:presentation-compiler

#19411 Fix algorithm to prevent recursive givens
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  tests/pos/i19404.scala
  tests/pos/i19407.scala
  tests/pos/i19417/defs_1.scala
  tests/pos/i19417/usage_2.scala
Labels: backport:nominated

#19471 Disable i19170b on Windows
  staging/src/scala/quoted/staging/QuoteDriver.scala
  tests/run-staging/i19170b.scala
Labels: prio:blocker

#19405 Implement SIP-42 - Support for binary integer literals
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  docs/_docs/reference/other-new-features/binary-literals.md
  docs/_spec/01-lexical-syntax.md
  docs/sidebar.yml
  project/resources/referenceReplacements/sidebar.yml
  tests/neg/binaryLiterals.scala
  tests/run/binaryLiterals.scala
Labels: needs-minor-release

#19484 Disable i19170b on JDK8
  tests/run-staging/i19170b.scala
Labels: prio:blocker

#19512 Handle default implicits to context parameters under -3.4-migration
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/typer/Migrations.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i19506.scala
Labels: backport:nominated

#19561 Workaround #19542
  tests/disabled/neg/i8984.check
  tests/disabled/neg/i8984.scala
  tests/neg/i19506.scala
Labels: prio:blocker

#19533 classfile reader: handle JDK 9+ constant types in constant pool
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileConstants.scala
  compiler/src/dotty/tools/dotc/core/classfile/ClassfileParser.scala
  compiler/test/dotty/tools/backend/jvm/ClassfileParserTest.scala
  tests/pos/t12396/A_1.java
  tests/pos/t12396/B_2.scala
Labels: backport:nominated

#19431 Prioritize TASTy files over classfiles on classpath aggregation
  compiler/src/dotty/tools/dotc/classpath/AggregateClassPath.scala
  compiler/src/dotty/tools/dotc/classpath/ClassPath.scala
  compiler/src/dotty/tools/dotc/classpath/DirectoryClassPath.scala
  compiler/src/dotty/tools/dotc/classpath/VirtualDirectoryClassPath.scala
  compiler/src/dotty/tools/dotc/classpath/ZipAndJarFileLookupFactory.scala
  compiler/src/dotty/tools/io/AbstractFile.scala
  compiler/src/dotty/tools/io/ClassPath.scala
  project/Build.scala
  sbt-test/sbt-dotty/scala2-library-tasty/build.sbt
  sbt-test/sbt-dotty/scala2-library-tasty/src/main/scala/hello/Hello.scala
  sbt-test/sbt-dotty/scala2-library-tasty/test
Labels: needs-minor-release

#19494 Fix goto-def on exported forwarders
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/core/Flags.scala
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  compiler/src/dotty/tools/dotc/interactive/SourceTree.scala
  presentation-compiler/src/main/dotty/tools/pc/MetalsInteractive.scala
  presentation-compiler/src/main/dotty/tools/pc/PcDefinitionProvider.scala
  presentation-compiler/test/dotty/tools/pc/tests/definition/PcDefinitionSuite.scala
Labels: backport:nominated, area:presentation-compiler
