Repository scala/scala3, pull requests merged in 2024-06, with the labels that each got.

#20551 Disable ClasspathTests.unglobClasspathVerifyTest
  compiler/test/dotty/tools/scripting/ClasspathTests.scala
Labels: prio:high

#20565 Adapt the release workflow to SIP-46
  .github/workflows/ci.yaml
Labels: backport:nominated

#20535 Adapt the workflow to release on SDKMAN!
  .github/workflows/publish-sdkman.yml
  .github/workflows/releases.yml
  .github/workflows/scripts/publish-sdkman.sh
Labels: backport:nominated

#20709 Fix incorrect paths to sha256 check sum files in release workflow
  .github/workflows/ci.yaml
Labels: backport:accepted

#20630 Release .zip instead of .tar.gz for windows in sdkman
  .github/workflows/publish-sdkman.yml
Labels: backport:nominated

#20631 SIP 46 - read classpath from file, remove lib directory in distribution
  dist/bin-native-overrides/cli-common-platform.bat
  dist/bin/common
  dist/bin/common.bat
  dist/bin/scalac
  dist/bin/scalac.bat
  dist/bin/scaladoc
  dist/bin/scaladoc.bat
  project/Build.scala
  project/RepublishPlugin.scala
Labels: backport:nominated, area:runner
