Repository scala/scala3, pull requests merged in 2024-05, with the labels that each got.

#20222 Add fromNullable to Predef for explicit nulls
  library/src-bootstrapped/scala/annotation/experimental.scala
  library/src-non-bootstrapped/scala/annotation/experimental.scala
  library/src/scala/runtime/stdLibPatches/Predef.scala
  project/MiMaFilters.scala
  tests/explicit-nulls/neg/from-nullable.scala
  tests/explicit-nulls/run/from-nullable.check
  tests/explicit-nulls/run/from-nullable.scala
  tests/neg/experimentalExperimental.scala
  tests/pos/experimentalExperimental.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: area:library, area:nullability, needs-minor-release

#20319 remove non-deterministic cancellation of async TASTy in sbt-test
  sbt-test/pipelining/Yearly-tasty-output-inline/build.sbt
  sbt-test/pipelining/Yearly-tasty-output/build.sbt
Labels: area:testing, how-i-fixed-it

#20293 Fix #20287: Add flexible types to Quotes library
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  compiler/src/scala/quoted/runtime/impl/printers/Extractors.scala
  compiler/src/scala/quoted/runtime/impl/printers/SourceCode.scala
  docs/_docs/internals/type-system.md
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/explicit-nulls/run/tasty-flexible-type.check
  tests/explicit-nulls/run/tasty-flexible-type/quoted_1.scala
  tests/explicit-nulls/run/tasty-flexible-type/quoted_2.scala
Labels: needs-minor-release

#20389 Disable ScalaCheck.scala test
  compiler/test/dotc/neg-init-global-scala2-library-tasty.blacklist
Labels: prio:high

#20404 Bump from 3.4.0 to 3.5.0-RC1 for MiMA
  project/Build.scala
  project/MiMaFilters.scala
Labels: prio:high

#20461 Update `addToBackportingProject.scala`
  project/scripts/addToBackportingProject.scala
Labels: area:infrastructure

#20477 Explain unresolvable references better
  compiler/src/dotty/tools/dotc/core/TypeErrors.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/test/dotc/neg-best-effort-pickling.blacklist
  tests/neg/i11226.check
  tests/neg/i11226.scala
  tests/neg/i11226a.check
  tests/neg/i11226a.scala
  tests/neg/i16407.check
  tests/pos/i11226b.scala
Labels: area:reporting
