Repository scala/scala3, pull requests merged in 2024-04, with the labels that each got.

#19937 Remove experimental `MainAnnotation`/`newMain` (replaced with `MacroAnnotation`)
  compiler/src/dotty/tools/dotc/ast/MainProxies.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  docs/_docs/reference/experimental/main-annotation.md
  library/src/scala/annotation/MainAnnotation.scala
  library/src/scala/annotation/newMain.scala
  presentation-compiler/test/dotty/tools/pc/tests/completion/CompletionKeywordSuite.scala
  tests/neg/main-annotation-currying.scala
  tests/neg/main-annotation-generic.scala
  tests/neg/main-annotation-implicit-given.scala
  tests/neg/main-annotation-mainannotation.scala
  tests/neg/main-annotation-multiple-annot.scala
  tests/neg/main-annotation-nonmethod.scala
  tests/neg/main-annotation-nonstatic.scala
  tests/neg/main-annotation-unknown-parser-1.scala
  tests/neg/main-annotation-unknown-parser-2.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
  tests/run/main-annotation-birthday.scala
  tests/run/main-annotation-dash-dash.scala
  tests/run/main-annotation-default-value-1.scala
  tests/run/main-annotation-default-value-2.scala
  tests/run/main-annotation-example.scala
  tests/run/main-annotation-flags.scala
  tests/run/main-annotation-help-override.scala
  tests/run/main-annotation-help.scala
  tests/run/main-annotation-homemade-annot-1.scala
  tests/run/main-annotation-homemade-annot-2.scala
  tests/run/main-annotation-homemade-annot-3.scala
  tests/run/main-annotation-homemade-annot-4.scala
  tests/run/main-annotation-homemade-annot-5.scala
  tests/run/main-annotation-homemade-annot-6.scala
  tests/run/main-annotation-homemade-parser-1.scala
  tests/run/main-annotation-homemade-parser-2.scala
  tests/run/main-annotation-homemade-parser-3.scala
  tests/run/main-annotation-homemade-parser-4.scala
  tests/run/main-annotation-homemade-parser-5.scala
  tests/run/main-annotation-multiple.scala
  tests/run/main-annotation-named-params.scala
  tests/run/main-annotation-newMain.scala
  tests/run/main-annotation-no-parameters-no-parens.scala
  tests/run/main-annotation-no-parameters.scala
  tests/run/main-annotation-overload.scala
  tests/run/main-annotation-param-annot-1.scala
  tests/run/main-annotation-param-annot-2.scala
  tests/run/main-annotation-param-annot-invalid-params.scala
  tests/run/main-annotation-return-type-1.scala
  tests/run/main-annotation-return-type-2.scala
  tests/run/main-annotation-short-name.scala
  tests/run/main-annotation-simple.scala
  tests/run/main-annotation-top-level.scala
  tests/run/main-annotation-types.scala
  tests/run/main-annotation-vararg-1.scala
  tests/run/main-annotation-vararg-2.scala
  tests/run/main-annotation-wrong-param-1.scala
  tests/run/main-annotation-wrong-param-names.scala
  tests/run/main-annotation-wrong-param-number.scala
  tests/run/main-annotation-wrong-param-type.scala
  tests/run/main-calculator-example.scala
Labels: needs-minor-release

#19982 Add support for `var` in refinements
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/_docs/internals/syntax.md
  docs/_docs/reference/syntax.md
  tests/neg/i13703.check
  tests/neg/i13703.scala
  tests/neg/i19809.check
  tests/neg/i19809.scala
  tests/neg/i4496b.scala
  tests/neg/illegal-refinements.scala
  tests/neg/structural.scala
  tests/pos/i19809.scala
Labels: needs-minor-release

#19382 Inline `unapply`s in the inlining phase
  compiler/src/dotty/tools/dotc/transform/Inlining.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
Labels: needs-minor-release

#19935 Add message parameter to `@experimental` annotation
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/core/Annotations.scala
  compiler/src/dotty/tools/dotc/transform/AccessProxies.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  library/src-bootstrapped/scala/annotation/experimental.scala
  library/src-non-bootstrapped/scala/annotation/experimental.scala
  library/src/scala/runtime/stdLibPatches/language.scala
  project/MiMaFilters.scala
  tests/neg-macros/i18677-a.check
  tests/neg-macros/i18677-b.check
  tests/neg/experimental-message-experimental-flag.check
  tests/neg/experimental-message-experimental-flag/Lib_1.scala
  tests/neg/experimental-message-experimental-flag/Test_2.scala
  tests/neg/experimental-message.check
  tests/neg/experimental-message.scala
  tests/neg/use-experimental-def.check
Labels: needs-minor-release

#20198 Stabilize reflect `SymbolMethods.isSuperAccessor`
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala
  scaladoc/src/dotty/tools/scaladoc/tasty/SyntheticSupport.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: needs-minor-release

#20244 CC: Give more info when context function parameters leak
  compiler/src/dotty/tools/dotc/cc/CheckCaptures.scala
  tests/neg-custom-args/captures/effect-swaps.check
  tests/neg-custom-args/captures/effect-swaps.scala
  tests/neg-custom-args/captures/leaking-iterators.check
  tests/neg-custom-args/captures/usingLogFile.check
Labels: cc-experiment, area:experimental:cc

#20249 Introduce MethodTypeKind to quotes reflection API
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/run-macros/reflect-method-type-kind/macro_1.scala
  tests/run-macros/reflect-method-type-kind/test_2.scala
Labels: needs-minor-release

#20264 Fix conflict with `new ScalaSettings`
  compiler/test/dotty/tools/dotc/config/ScalaSettingsTests.scala
Labels: prio:blocker
