Repository scala/scala3, pull requests merged in 2024-07, with the labels that each got.

#20859 Bump scala-cli to 1.4.0
  project/Build.scala
Labels: backport:nominated, needs-minor-release

#20910 fix issue 20901: etaCollapse context bound type
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/pos/i20901/Foo.scala
  tests/pos/i20901/Foo.tastycheck
  tests/semanticdb/expect/Methods.expect.scala
  tests/semanticdb/metac.expect
Labels: backport:nominated

#20989 Use final result type to check selector bound
  compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
  tests/pos/i20860.scala
Labels: backport:nominated

#20895 Switch default source version to 3.6
  compiler/src/dotty/tools/dotc/config/SourceVersion.scala
  library/src/scala/runtime/stdLibPatches/language.scala
  tests/neg/given-loop-prevention.check
  tests/neg/i20415.scala
  tests/neg/i6716.check
  tests/neg/i6716.scala
  tests/neg/i7294.check
  tests/neg/i7294.scala
  tests/neg/looping-givens.check
  tests/neg/looping-givens.scala
  tests/pos/i20415.scala
  tests/pos/i6716.scala
  tests/pos/looping-givens.scala
  tests/pos/source-import-3-5-migration.scala
  tests/pos/source-import-3-5.scala
  tests/pos/source-import-3-6-migration.scala
  tests/pos/source-import-3-6.scala
  tests/pos/source-import-3-7-migration.scala
  tests/pos/source-import-3-7.scala
  tests/run/i6716.scala
Labels: needs-minor-release

#21009 Add workflow to release to winget
  .github/workflows/publish-winget.yml
  .github/workflows/releases.yml
Labels: area:ci, area:package-manager

#21121 Use pathing jars in cli commands
  compiler/src/dotty/tools/dotc/classpath/ClassPathFactory.scala
  compiler/src/dotty/tools/io/ClassPath.scala
  dist/bin/common
  dist/bin/common.bat
  dist/bin/scalac
  dist/bin/scalac.bat
  dist/bin/scaladoc
  dist/bin/scaladoc.bat
  project/Build.scala
  project/RepublishPlugin.scala
Labels: backport:nominated

#21160 expand classpath of pathing jars in scala_legacy command
  dist/bin/scala_legacy
Labels: backport:nominated

#21186 emit generatedNonLocalClass in backend when callback is not enabled
  compiler/src/dotty/tools/backend/jvm/CodeGen.scala
  sbt-bridge/test/xsbt/ProductsSpecification.scala
  sbt-bridge/test/xsbt/ScalaCompilerForUnitTesting.scala
  sbt-bridge/test/xsbti/TestCallback.scala
Labels: backport:nominated

#18271 [experimental feature] Support HOAS pattern with type variables for quote pattern matching
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/ast/Trees.scala
  compiler/src/dotty/tools/dotc/ast/tpd.scala
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/quoted/QuotePatterns.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  compiler/src/dotty/tools/dotc/typer/ReTyper.scala
  compiler/src/scala/quoted/runtime/impl/QuoteMatcher.scala
  docs/_docs/reference/experimental/quoted-patterns-with-polymorphic-functions.md
  library/src/scala/quoted/runtime/Patterns.scala
  library/src/scala/runtime/stdLibPatches/language.scala
  tests/neg-macros/quoted-pattern-with-bounded-type-params-regression.check
  tests/neg-macros/quoted-pattern-with-bounded-type-params-regression.scala
  tests/neg-macros/quoted-pattern-with-bounded-type-params.check
  tests/neg-macros/quoted-pattern-with-bounded-type-params.scala
  tests/neg-macros/quoted-pattern-with-type-params-regression.check
  tests/neg-macros/quoted-pattern-with-type-params-regression.scala
  tests/neg-macros/quoted-pattern-with-type-params.check
  tests/neg-macros/quoted-pattern-with-type-params.scala
  tests/pos-macros/quoted-patten-with-type-params.scala
  tests/run-macros/quote-match-poly-function-1-regression.check
  tests/run-macros/quote-match-poly-function-1-regression/Macro_1.scala
  tests/run-macros/quote-match-poly-function-1-regression/Test_2.scala
  tests/run-macros/quote-match-poly-function-1.check
  tests/run-macros/quote-match-poly-function-1/Macro_1.scala
  tests/run-macros/quote-match-poly-function-1/Test_2.scala
  tests/run-macros/quote-match-poly-function-2.check
  tests/run-macros/quote-match-poly-function-2/Macro_1.scala
  tests/run-macros/quote-match-poly-function-2/Test_2.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: area:experimental, needs-minor-release

#21234 Bump scala-cli to 1.4.1 + drop old cli management
  dist/bin-native-overrides/cli-common-platform
  dist/bin-native-overrides/cli-common-platform.bat
  project/Build.scala
Labels: backport:nominated
