Repository scala/scala3, pull requests merged in 2024-11, with the labels that each got.

#21895 Revert "Drop inaccessible subclasses from refineUsingParent"
  compiler/src/dotty/tools/dotc/core/Decorators.scala
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  tests/pos/i21790.scala
Labels: prio:blocker

#21934 Fix #21914: Don't project nested wildcard patterns to nullable
  compiler/src/dotty/tools/dotc/transform/patmat/Space.scala
  tests/patmat/i12530.check
  tests/patmat/null.check
  tests/patmat/null.scala
  tests/warn/i20121.scala
  tests/warn/i20122.scala
  tests/warn/i20123.scala
Labels: area:pattern-matching

#21937 Fix Windows OS detection in TraceNameManglingTest
  compiler/test/dotty/tools/dotc/profile/TraceNameManglingTest.scala
Labels: prio:blocker

#21942 Fix #21939: Update names and descriptions for cc and setup phases
  compiler/src/dotty/tools/dotc/cc/CheckCaptures.scala
  compiler/src/dotty/tools/dotc/cc/Setup.scala
Labels: fasttrack

#21643 Context Bounds for Polymorphic Functions
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/pos/contextbounds-for-poly-functions.scala
  tests/run/contextbounds-for-poly-functions.check
  tests/run/contextbounds-for-poly-functions.scala
Labels: release-notes, needs-minor-release

#21825 Nowarn extension matching nonpublic member
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  tests/warn/i21816.scala
Labels: backport:nominated

#21875 Fix #21868, #21869, and #21870: handle CapsOf in more places
  compiler/src/dotty/tools/dotc/cc/CaptureOps.scala
  compiler/src/dotty/tools/dotc/cc/CaptureRef.scala
  compiler/src/dotty/tools/dotc/cc/CheckCaptures.scala
  compiler/src/dotty/tools/dotc/cc/Setup.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/neg-custom-args/captures/capset-bound.scala
  tests/neg-custom-args/captures/capture-poly.scala
  tests/neg-custom-args/captures/i21868.scala
Labels: cc-experiment, area:experimental:cc

#21954 Drop phase.isTyper use in isLegalPrefix/asf
  compiler/src/dotty/tools/dotc/core/CheckRealizable.scala
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/transform/Recheck.scala
  compiler/test/dotc/pos-test-pickling.blacklist
  scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala
  tests/neg/6314-6.check
  tests/neg/i6225.scala
  tests/pos/i17222.2.scala
  tests/pos/i17222.3.scala
  tests/pos/i17222.4.scala
  tests/pos/i17222.5.scala
  tests/pos/i17222.8.scala
  tests/pos/i17222.izumi.min.scala
  tests/pos/i17222.izumi.rep/InspectorBase.scala
  tests/pos/i17222.izumi.rep/ReflectionUtil.scala
  tests/pos/i17222.scala
Labels: backport:nominated

#22053 Update a test related to scala2-library-cc-tasty
  tests/neg-custom-args/captures/i21614.check
  tests/neg-custom-args/captures/i21614.scala
Labels: fasttrack, area:experimental:cc

#22059 Fix nightly build by updating a named tuple test with language import
  tests/pos/named-tuple-downcast.scala
Labels: fasttrack, area:named-tuples
