Repository scala/scala3, pull requests merged in 2024-02, with the labels that each got.

#19654 Drop special treatment of function types in overloading resolution
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  tests/run/i19641.scala
  tests/run/i4364a.scala
Labels: backport:nominated

#19624 Disallow covariant `cap`s in the lower bound of type members
  compiler/src/dotty/tools/dotc/cc/CheckCaptures.scala
  tests/neg-custom-args/captures/i19330-alt.scala
  tests/neg-custom-args/captures/i19330-alt2.scala
  tests/neg-custom-args/captures/i19330.scala
Labels: area:experimental:cc

#19720 Fix nightly build failure + Address issue with the self-hosted runner
  .github/workflows/ci.yaml
  .github/workflows/releases.yml
Labels: prio:high

#19719 Tweak parameter accessor scheme
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  tests/run/i19711.scala
Labels: backport:nominated

#19777 Allow range selection on function parameter to select a parameter list
  presentation-compiler/src/main/dotty/tools/pc/SelectionRangeProvider.scala
  presentation-compiler/test/dotty/tools/pc/tests/SelectionRangeSuite.scala
Labels: area:presentation-compiler

#19786 Fix a REPL bad symbolic reference
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  compiler/test/dotty/tools/repl/ReplCompilerTests.scala
  compiler/test/dotty/tools/repl/ReplTest.scala
  compiler/test/dotty/tools/repl/TabcompleteTests.scala
Labels: backport:nominated

#19802 Fix test directive in i18533
  tests/neg/i18533.check
  tests/neg/i18533/Non_SCALA_ONLY.java
  tests/pos/i18533/Cat.java
  tests/pos/i18533/Dog.java
  tests/pos/i18533/Pet.java
Labels: prio:high
