Repository scala/scala3, pull requests merged in 2024-10, with the labels that each got.

#20494 Expr#show: Don't crash when the expression contains an unsupported type (like a SkolemType)
  compiler/src/scala/quoted/runtime/impl/printers/Extractors.scala
  compiler/src/scala/quoted/runtime/impl/printers/SourceCode.scala
  tests/pos-macros/skolem/Macro_1.scala
  tests/pos-macros/skolem/Test_2.scala
  tests/run-macros/i19905.check
Labels: backport:nominated

#21699 Fix incorrect caching with dependent method parameters
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/neg/i16842.check
  tests/neg/i16842.scala
  tests/pos/dep-poly-class.scala
Labels: backport:nominated

#21700 Fix #21402: Always allow type member extraction for stable scrutinees in match types.
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  tests/pos/i21402.scala
  tests/pos/match-type-extract-path-dependent.scala
Labels: needs-minor-release

#20347 Add the possibility to create a typeSymbol in the Quotes API
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  library/src/scala/quoted/Quotes.scala
  tests/neg-macros/quote-sym-newtype/Macro_1.scala
  tests/neg-macros/quote-sym-newtype/Test_2.scala
  tests/pos-macros/quote-sym-newboundedtype/Macro_1.scala
  tests/pos-macros/quote-sym-newboundedtype/Test_2.scala
  tests/pos-macros/quote-sym-newtype-in-trait/Macro_1.scala
  tests/pos-macros/quote-sym-newtype-in-trait/Test_2.scala
  tests/pos-macros/quote-sym-newtype/Macro_1.scala
  tests/pos-macros/quote-sym-newtype/Test_2.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: needs-minor-release

#21738 Revert "Fix scaladoc TastyInspector regressions"
  sbt-test/sbt-dotty/scaladoc-regressions/build.sbt
  sbt-test/sbt-dotty/scaladoc-regressions/i18231/src/main/scala/main.scala
  sbt-test/sbt-dotty/scaladoc-regressions/i20476/src/main/scala/main.scala
  sbt-test/sbt-dotty/scaladoc-regressions/project/plugins.sbt
  sbt-test/sbt-dotty/scaladoc-regressions/test
  scaladoc/src/dotty/tools/scaladoc/tasty/TastyParser.scala
  scaladoc/src/scala/tasty/inspector/TastyInspector.scala
  scaladoc/test/dotty/tools/scaladoc/no-link-warnings/LinkWarningTest.scala
Labels: prio:blocker

#21751 fix code rendering error in givens.md
  docs/_docs/reference/contextual/givens.md
Labels: backport:nominated

#21752 REPL: JLine 3.27.0 (was 3.25.1)
  project/Build.scala
Labels: area:repl, backport:nominated

#21836 Fix typo in `allTermArguments`
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/transform/TreeChecker.scala
Labels: fasttrack

#21846 Pretty-print lambdas
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  tests/printing/annot-19846b.check
  tests/printing/lambdas.check
  tests/printing/lambdas.scala
Labels: fasttrack
