Repository scala/scala3, pull requests merged in 2024-08, with the labels that each got.

#21329 Require named arguments for java defined annotations
  compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  tests/neg/i20554-a.check
  tests/neg/i20554-a/Annotation.java
  tests/neg/i20554-a/Test.scala
  tests/neg/i20554-b.check
  tests/neg/i20554-b/SimpleAnnotation.java
  tests/neg/i20554-b/Test.scala
  tests/pos-java-interop-separate/i6868/MyScala_2.scala
  tests/pos/i20554-a/Annotation.java
  tests/pos/i20554-a/Test.scala
  tests/pos/i20554-b/SimpleAnnotation.java
  tests/pos/i20554-b/Test.scala
  tests/pos/i20554-c.scala
  tests/pos/i6151/Test.scala
  tests/run-macros/i19951-java-annotations-tasty-compat-2/ScalaUser_1.scala
  tests/run-macros/i19951-java-annotations-tasty-compat.check
  tests/run-macros/i19951-java-annotations-tasty-compat/ScalaUser_2.scala
Labels: release-notes, needs-minor-release

#21338 Bump scala-cli to 1.4.3
  project/Build.scala
Labels: needs-minor-release

#21374 Update MiMa and Reference Version to 3.5.0
  project/Build.scala
Labels: backport:nominated

#21378 Bump tasty format for 28.6.x
  tasty/src/dotty/tools/tasty/TastyFormat.scala
Labels: prio:blocker, needs-minor-release

#21377 Bound TypeRepr by Matchable in Quotes
  library/src/scala/quoted/Quotes.scala
  tests/pos/i21282.scala
Labels: needs-minor-release

#21198 Enable betterMatchTypeExtractors in >= 3.6
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/core/TypeComparer.scala
  library/src/scala/runtime/stdLibPatches/language.scala
  tests/neg/mt-deskolemize-2.scala
  tests/pos/20538.scala
  tests/pos/20538b.scala
  tests/pos/mt-deskolemize.scala
Labels: needs-minor-release

#21407 Update hamzaremmal/sdkman-release-action action
  .github/workflows/publish-sdkman.yml
Labels: backport:nominated

#21408 Update hamzaremmal/sdkman-release-action & hamzaremmal/sdkman-default-action action
  .github/workflows/publish-sdkman.yml
Labels: backport:nominated

#21428 Check all top-level covariant capture sets in checkNotUniversal
  compiler/src/dotty/tools/dotc/cc/CheckCaptures.scala
  tests/neg-custom-args/captures/i21401.check
  tests/neg-custom-args/captures/i21401.scala
Labels: cc-experiment

#20144 Update asm to patched 9.7
  compiler/src/dotty/tools/backend/jvm/BackendUtils.scala
  project/Build.scala
  tests/pos-with-compiler-cc/dotc/config/ScalaSettings.scala
Labels: backport:nominated
