Repository scala/scala3, pull requests merged in 2024-12, with the labels that each got.

#22000 Refine rules for capture parameters and members
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/cc/CaptureAnnotation.scala
  compiler/src/dotty/tools/dotc/cc/CaptureRef.scala
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/cc/Setup.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  library/src/scala/caps.scala
  scala2-library-cc/src/scala/collection/Stepper.scala
  tests/neg-custom-args/captures/capset-bound2.scala
  tests/neg-custom-args/captures/capset-members.scala
  tests/neg-custom-args/captures/capture-parameters.scala
  tests/neg-custom-args/captures/capture-poly.scala
  tests/neg-custom-args/captures/i21868.scala
  tests/neg-custom-args/captures/i21868b.scala
  tests/neg-custom-args/captures/i22005.scala
  tests/neg-custom-args/captures/use-capset.check
  tests/neg-custom-args/captures/use-capset.scala
  tests/neg/cc-poly-2.check
  tests/neg/cc-poly-2.scala
  tests/pos-custom-args/captures/cc-poly-varargs.scala
  tests/pos/cc-poly-source-capability.scala
Labels: area:experimental:cc

#22054 Update MAINTENANCE.md
  MAINTENANCE.md
Labels: area:documentation

#22149 Widen singleton types when computing fields from .Fields
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/pos/i22018.scala
Labels: area:named-tuples

#21624 Fix #21619: Refactor NotNullInfo to record every reference which is retracted once.
  compiler/src/dotty/tools/dotc/core/Contexts.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/Nullables.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/explicit-nulls/neg/i21380b.scala
  tests/explicit-nulls/neg/i21380c.scala
  tests/explicit-nulls/neg/i21619.scala
  tests/explicit-nulls/pos/after-termination.scala
  tests/explicit-nulls/unsafe-common/unsafe-overload.scala
Labels: area:nullability

#22199 Fix layout of released SDK archives, restore intermiediete top-level directory
  .github/workflows/ci.yaml
  project/Build.scala
Labels: backport:nominated

#21421 use new infer expected type for singleton complations
  presentation-compiler/src/main/dotty/tools/pc/InferExpectedType.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/SingletonCompletions.scala
Labels: area:presentation-compiler

#22227 chore: use sbt/setup-sbt when using ubuntu-latest image
  .github/workflows/build-sdk.yml
  .github/workflows/language-reference.yaml
  .github/workflows/launchers.yml
  .github/workflows/scaladoc.yaml
  .github/workflows/test-cc.yml
Labels: prio:high

#22205 REPL: JLine: follow recommendation to use JNI, not JNA; also JLine 3.27.1 (was 3.27.0)
  dist/libexec/common-shared
  project/Build.scala
Labels: backport:nominated
