Repository scala/scala3, pull requests merged in 2024-03, with the labels that each got.

#19877 Restore pre-3.3.2 behavior of `inline implicit def`
  compiler/src/dotty/tools/dotc/core/Flags.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/pos/i19862.scala
Labels: backport:nominated

#19875 Adjust owner in `Interactive.contextOfPath` causing crash in `ImplicitSearch`
  compiler/src/dotty/tools/dotc/interactive/Interactive.scala
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
Labels: backport:nominated

#19839 In progress: transfer of the repository to scala/scala3
  .github/workflows/ci.yaml
  project/Build.scala
  project/scripts/cmdScaladocTests
Labels: backport:accepted

#19612 Add supports for type cast and filtering type for field and method owner in global initialization checker
  compiler/src/dotty/tools/dotc/transform/init/Objects.scala
  compiler/src/dotty/tools/dotc/transform/init/Util.scala
  tests/init-global/neg/TypeCast.scala
  tests/init-global/pos/TypeCast1.scala
  tests/init-global/pos/TypeCast2.scala
  tests/init-global/pos/TypeCast3.scala
  tests/init-global/pos/TypeCast4.scala
  tests/init-global/pos/i18882.scala
Labels: area:initialization

#19911 Fix undercompilation upon ctor change
  compiler/src/dotty/tools/dotc/sbt/package.scala
  sbt-bridge/test/xsbt/ExtractUsedNamesSpecification.scala
  sbt-test/source-dependencies/constructors/A.scala
  sbt-test/source-dependencies/constructors/B.scala
  sbt-test/source-dependencies/constructors/changes/A2.scala
  sbt-test/source-dependencies/constructors/changes/B2.scala
Labels: backport:nominated

#19983 Fix validity period of derived SingleDenotations
  compiler/src/dotty/tools/dotc/core/Denotations.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
  compiler/test-resources/repl/i18756
Labels: backport:nominated
