Repository scala/scala3, pull requests merged in 2025-03, with the labels that each got.

#22679 REPL: JLine 3.29.0 (was 3.27.1)
  project/Build.scala
Labels: area:repl, backport:nominated

#22343 Implement :jar (deprecate :require)
  compiler/src/dotty/tools/dotc/config/JavaPlatform.scala
  compiler/src/dotty/tools/dotc/config/Platform.scala
  compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala
  compiler/src/dotty/tools/repl/ParseResult.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test-resources/jars/MyLibrary.scala
  compiler/test-resources/jars/MyLibrary2.scala
  compiler/test-resources/jars/mylibrary.jar
  compiler/test-resources/jars/mylibrary2.jar
  compiler/test-resources/repl/jar-command
  compiler/test-resources/repl/jar-errors
  compiler/test-resources/repl/jar-multiple
  compiler/test/dotty/tools/repl/ReplTest.scala
  compiler/test/dotty/tools/repl/TabcompleteTests.scala
Labels: release-notes

#22652 Make SIP-62 - `betterFors` a standard feature
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  docs/_docs/reference/changed-features/better-fors.md
  docs/sidebar.yml
  library/src/scala/runtime/stdLibPatches/language.scala
  presentation-compiler/test/dotty/tools/pc/tests/tokens/SemanticTokensSuite.scala
  tests/debug/eval-in-for-comprehension.check
  tests/pos/better-fors-given.scala
  tests/run/better-fors.scala
  tests/run/fors.scala
  tests/semanticdb/expect/ForComprehension.expect.scala
  tests/semanticdb/metac.expect
Labels: release-notes, needs-minor-release

#21880 Add class parameters, flags, and privateWithin and annotations to newClass in reflect API
  compiler/src/dotty/tools/dotc/core/Symbols.scala
  compiler/src/dotty/tools/dotc/transform/TreeChecker.scala
  compiler/src/dotty/tools/dotc/typer/TypeAssigner.scala
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  compiler/src/scala/quoted/runtime/impl/printers/SourceCode.scala
  library/src/scala/quoted/Quotes.scala
  tests/neg-macros/i19842-a.check
  tests/neg-macros/i19842-a/Macro.scala
  tests/neg-macros/i19842-b.check
  tests/neg-macros/i19842-b/Macro.scala
  tests/neg-macros/newClassParamsMissingArgument.check
  tests/neg-macros/newClassParamsMissingArgument/Macro_1.scala
  tests/neg-macros/newClassParamsMissingArgument/Test_2.scala
  tests/pos-macros/newClassExtendsWithSymbolInParent/Macro_1.scala
  tests/pos-macros/newClassExtendsWithSymbolInParent/Test_2.scala
  tests/run-macros/annot-add-global-object/Macro_1.scala
  tests/run-macros/annot-add-local-object/Macro_1.scala
  tests/run-macros/annot-add-nested-object/Macro_1.scala
  tests/run-macros/newClassAnnotation.check
  tests/run-macros/newClassAnnotation/JavaAnnot.java
  tests/run-macros/newClassAnnotation/Macro_1.scala
  tests/run-macros/newClassAnnotation/Test_2.scala
  tests/run-macros/newClassExtendsJavaClass.check
  tests/run-macros/newClassExtendsJavaClass/JavaClass.java
  tests/run-macros/newClassExtendsJavaClass/Macro_1.scala
  tests/run-macros/newClassExtendsJavaClass/Main_2.scala
  tests/run-macros/newClassParams.check
  tests/run-macros/newClassParams/Macro_1.scala
  tests/run-macros/newClassParams/Test_2.scala
  tests/run-macros/newClassParamsExtendsClassParams.check
  tests/run-macros/newClassParamsExtendsClassParams/Macro_1.scala
  tests/run-macros/newClassParamsExtendsClassParams/Test_2.scala
  tests/run-macros/newClassTraitAndAbstract.check
  tests/run-macros/newClassTraitAndAbstract/Macro_1.scala
  tests/run-macros/newClassTraitAndAbstract/Test_2.scala
  tests/run-macros/newClassTypeParams.check
  tests/run-macros/newClassTypeParams/Macro_1.scala
  tests/run-macros/newClassTypeParams/Test_2.scala
  tests/run-macros/newClassTypeParamsDoc.check
  tests/run-macros/newClassTypeParamsDoc/Macro_1.scala
  tests/run-macros/newClassTypeParamsDoc/Test_2.scala
Labels: needs-minor-release

#22797 Fix #22794: Emit the definition of `Arrays.newArray` even though it's a primitive.
  compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala
  sbt-test/scalajs/backward-compat/build.sbt
  sbt-test/scalajs/backward-compat/project/plugins.sbt
  sbt-test/scalajs/backward-compat/src/test/scala/NewArrayIssue22794Test.scala
  sbt-test/scalajs/backward-compat/test
Labels: backport:accepted

#22796 Add support for running the `test` sub-command with the bisect script
  project/scripts/bisect.scala
Labels: area:dx

#22759 Fail compilation if multiple conflicting top-level private defs/vals are in the same package
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  tests/neg/i22721.check
  tests/neg/i22721/test1.scala
  tests/neg/i22721/test2.scala
  tests/neg/toplevel-overload/moredefs_1.scala
Labels: backport:nominated

#22814 Deprecate `Yno-kind-polymorphism`
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  docs/_docs/reference/other-new-features/kind-polymorphism.md
  tests/neg/no-kind-polymorphism-anykind.scala
  tests/pos/deprecated-no-kind-polymorphism-anykind.scala
Labels: release-notes, backport:nominated

#22843 Bump Scala CLI to v1.7.1 (was v1.7.0)
  .github/workflows/lts-backport.yaml
  project/Build.scala
Labels: backport:nominated
