Repository scala/scala3, pull requests merged in 2025-05, with the labels that each got.

#22543 Implement applied constructor types
  compiler/src/dotty/tools/dotc/core/NamerOps.scala
  compiler/src/dotty/tools/dotc/core/TypeUtils.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/ErrorReporting.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotc/neg-best-effort-unpickling.excludelist
  docs/_docs/internals/syntax.md
  docs/_docs/reference/experimental/modularity.md
  tests/neg/applied_constructor_types.check
  tests/neg/applied_constructor_types.scala
  tests/neg/context-function-syntax.scala
  tests/neg/deptypes.scala
  tests/neg/i7751.scala
  tests/pos/applied_constructor_types.scala
  tests/warn/applied_constructor_types.check
  tests/warn/applied_constructor_types.scala
Labels: release-notes

#23116 chore: deprecate `scala.annotation.transparentTrait`
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/SymDenotations.scala
  docs/_docs/reference/other-new-features/transparent-traits.md
  library/src/scala/annotation/transparentTrait.scala
  library/src/scala/reflect/Enum.scala
  library/src/scala/runtime/EnumValue.scala
Labels: needs-minor-release

#23197 fix: handle multiple params lists in for infer type
  presentation-compiler/src/main/dotty/tools/pc/ApplyArgsExtractor.scala
  presentation-compiler/src/main/dotty/tools/pc/InferExpectedType.scala
  presentation-compiler/src/main/dotty/tools/pc/completions/NamedArgCompletions.scala
  presentation-compiler/test/dotty/tools/pc/tests/InferExpectedTypeSuite.scala
Labels: area:presentation-compiler

#23219 chore: add `scala.language.2.13`
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/config/SourceVersion.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/transform/Pickler.scala
  compiler/src/dotty/tools/dotc/transform/PostTyper.scala
  compiler/src/dotty/tools/dotc/transform/SpecializeApplyMethods.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  library/src/scala/runtime/stdLibPatches/language.scala
  project/Build.scala
  project/MiMaFilters.scala
  project/scripts/scala2-library-tasty-mima.sh
Labels: backport:nominated

#23275 Allow caps in result types of functions to be mapped to reaches
  compiler/src/dotty/tools/dotc/cc/Capability.scala
  compiler/src/dotty/tools/dotc/cc/CaptureOps.scala
  compiler/src/dotty/tools/dotc/cc/CaptureSet.scala
  compiler/src/dotty/tools/dotc/cc/ccConfig.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  tests/neg-custom-args/captures/cc-existential-conformance.check
  tests/neg-custom-args/captures/existential-mapping.check
  tests/neg-custom-args/captures/reach-in-results.scala
  tests/neg-custom-args/captures/reaches.check
  tests/neg-custom-args/captures/reaches.scala
  tests/neg-custom-args/captures/refine-reach-shallow.scala
  tests/neg-custom-args/captures/scoped-caps.check
  tests/neg-custom-args/captures/scoped-caps.scala
  tests/neg-custom-args/captures/sep-use2.check
  tests/neg-custom-args/captures/sep-use2.scala
  tests/pos-custom-args/captures/reach-in-results.scala
Labels: area:capabilities

#23014 Change `into` scheme to be fully type-based
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
  compiler/src/dotty/tools/dotc/ast/untpd.scala
  compiler/src/dotty/tools/dotc/cc/CaptureOps.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/Flags.scala
  compiler/src/dotty/tools/dotc/core/NamerOps.scala
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/core/TypeOps.scala
  compiler/src/dotty/tools/dotc/core/Types.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
  compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
  compiler/src/dotty/tools/dotc/parsing/Parsers.scala
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  compiler/src/dotty/tools/dotc/parsing/Tokens.scala
  compiler/src/dotty/tools/dotc/printing/PlainPrinter.scala
  compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  compiler/test/dotc/run-test-pickling.excludelist
  docs/_docs/internals/syntax.md
  docs/_docs/reference/experimental/into-modifier.md
  docs/_docs/reference/experimental/into.md
  docs/sidebar.yml
  language-server/test/dotty/tools/languageserver/CompletionTest.scala
  library/src/scala/Conversion.scala
  library/src/scala/annotation/internal/$into.scala
  library/src/scala/annotation/into.scala
  project/MiMaFilters.scala
  tests/neg/i21786.scala
  tests/neg/into-inferred.check
  tests/neg/into-inferred.scala
  tests/neg/into-mods.check
  tests/neg/into-mods.scala
  tests/neg/into-override.check
  tests/neg/into-override.scala
  tests/neg/into-syntax.check
  tests/neg/into-syntax.scala
  tests/new/test.scala
  tests/pos/into-bigint.scala
  tests/pos/into-class.scala
  tests/pos/into-expr.scala
  tests/pos/into-sam.scala
  tests/pos/into-separate/Test_2.scala
  tests/pos/into-separate/classes_1.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
  tests/run/Parser.scala
  tests/run/convertible.scala
  tests/warn/convertible.scala
  tests/warn/into-as-mod.scala
Labels: area:experimental, stat:sip-in-progress
