Repository scala/scala3, pull requests merged in 2025-02, with the labels that each got.

#22441 Implicit parameters should warn at call site in >= 3.7
  compiler/src/dotty/tools/dotc/ast/Desugar.scala
  compiler/src/dotty/tools/dotc/config/MigrationVersion.scala
  compiler/src/dotty/tools/dotc/typer/Migrations.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  compiler/test/dotty/tools/dotc/CompilationTests.scala
  language-server/src/dotty/tools/languageserver/DottyLanguageServer.scala
  language-server/src/dotty/tools/languageserver/worksheet/WorksheetService.scala
  scaladoc/src/dotty/tools/scaladoc/api.scala
  staging/src/scala/quoted/staging/QuoteDriver.scala
  tests/neg/i22440.check
  tests/neg/i22440.scala
  tests/pos/i22440.scala
  tests/rewrites/i22440.check
  tests/rewrites/i22440.scala
  tests/warn/i22440.check
  tests/warn/i22440.scala
Labels: release-notes, needs-minor-release

#22582 Fix copy of annotation on @main methods
  compiler/src/dotty/tools/dotc/ast/MainProxies.scala
  tests/pos/annot-main-22364.scala
  tests/pos/annot-main-22364b.scala
  tests/pos/annot-main-22364c.scala
Labels: area:annotations

#22553 Lift arguments of explicitly constructed annotations
  compiler/src/dotty/tools/dotc/core/Mode.scala
  compiler/src/dotty/tools/dotc/typer/Applications.scala
  compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/printing/dependent-annot-default-args.check
  tests/printing/dependent-annot-default-args.scala
Labels: area:annotations

#22417 Implement `summonIgnoring`
  compiler/src/dotty/tools/dotc/interactive/Completion.scala
  compiler/src/dotty/tools/dotc/typer/Implicits.scala
  compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
  library/src/scala/quoted/Expr.scala
  library/src/scala/quoted/Quotes.scala
  project/MiMaFilters.scala
  tests/run-macros/summonIgnoring-nonrecursive.check
  tests/run-macros/summonIgnoring-nonrecursive/Macro_1.scala
  tests/run-macros/summonIgnoring-nonrecursive/Test_2.scala
  tests/run-macros/summonIgnoring.check
  tests/run-macros/summonIgnoring/Macro_1.scala
  tests/run-macros/summonIgnoring/Test_2.scala
Labels: needs-minor-release

#21698 Minimal support for dependent case classes
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/StdNames.scala
  compiler/src/dotty/tools/dotc/transform/FirstTransform.scala
  compiler/src/dotty/tools/dotc/transform/SyntheticMembers.scala
  compiler/src/dotty/tools/dotc/transform/UnrollDefinitions.scala
  compiler/src/dotty/tools/dotc/typer/Namer.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg/i8069.scala
  tests/pos/enum-refinement.scala
  tests/run-macros/tasty-extractors-2.check
  tests/run/i8073.scala
  tests/run/i8073b.scala
Labels: needs-minor-release

#21801 Revert dubious retry in vulpix
  compiler/test/dotty/tools/vulpix/ParallelTesting.scala
Labels: fasttrack, area:vulpix

#22011 Expand value references to packages to their underlying package objects
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/transform/Erasure.scala
  compiler/src/dotty/tools/dotc/typer/Checking.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  docs/_docs/reference/experimental/package-object-values.md
  docs/_docs/reference/other-new-features/toplevel-definitions.md
  docs/sidebar.yml
  library/src/scala/runtime/stdLibPatches/language.scala
  project/MiMaFilters.scala
  tests/run/pkgobjvals.check
  tests/run/pkgobjvals.scala
Labels: area:experimental, stat:sip-in-progress

#22591 Stabilise `@publicInBinary`
  library/src/scala/annotation/publicInBinary.scala
  tests/neg/i22498.check
  tests/neg/i22498.scala
  tests/neg/inline-unstable-accessors.scala
  tests/neg/publicInBinaryOverride.check
  tests/neg/publicInBinaryOverride.scala
  tests/pos-macros/i15413/Macro_1.scala
  tests/pos-macros/i15413b/Macro_1.scala
  tests/pos-macros/i19526b/Test.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
  tests/run/i13215.scala
  tests/run/i22497.scala
  tests/run/i22498.scala
  tests/run/noProtectedSuper.scala
  tests/run/publicInBinary/Lib_1.scala
Labels: release-notes, needs-minor-release

#22317 Add `@scala.annotation.internal.preview` annotation and `-preview` flag.
  compiler/src/dotty/tools/dotc/config/Feature.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Annotations.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  compiler/src/dotty/tools/dotc/core/SymUtils.scala
  compiler/src/dotty/tools/dotc/typer/CrossVersionChecks.scala
  compiler/src/dotty/tools/dotc/typer/RefChecks.scala
  docs/_docs/reference/other-new-features/preview-defs.md
  docs/sidebar.yml
  library/src/scala/annotation/internal/preview.scala
  project/MiMaFilters.scala
  tests/neg/preview-message.check
  tests/neg/preview-message.scala
  tests/neg/preview-non-viral/defs_1.scala
  tests/neg/preview-non-viral/usage_2.scala
  tests/neg/previewOverloads.scala
  tests/neg/previewOverride.scala
  tests/pos/preview-flag.scala
Labels: release-notes

#22636 Fix #21242: Add REPL flag to quit after evaluating init script
  bin/replQ
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/repl/ReplDriver.scala
  compiler/test/dotty/tools/scripting/BashExitCodeTests.scala
Labels: release-notes
