Repository scala/scala3, pull requests merged in 2025-04, with the labels that each got.

#22855 Check trailing blank line at EOF for OUTDENT
  compiler/src/dotty/tools/dotc/parsing/Scanners.scala
  compiler/src/dotty/tools/dotc/util/Chars.scala
  compiler/test/dotty/tools/repl/ReplCompilerTests.scala
Labels: backport:accepted

#23004 Update asm to 9.8.0
  compiler/src/dotty/tools/backend/jvm/BackendUtils.scala
  project/Build.scala
Labels: backport:nominated

#23066 Make sure we don't recheck closure bodies twice
  compiler/src/dotty/tools/dotc/cc/CheckCaptures.scala
  compiler/src/dotty/tools/dotc/transform/Recheck.scala
Labels: area:experimental:cc
