Repository scala/scala3, pull requests merged in 2025-07, with the labels that each got.

#23538 Bump Scala CLI to v1.8.4 (was v1.8.3)
  .github/workflows/lts-backport.yaml
  project/Build.scala
Labels: release-notes, backport:nominated

#23540 chore: add `-Yno-stdlib-patches` flag for the stdlib migration
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/core/Definitions.scala
  tests/neg/no-patches.check
  tests/neg/no-patches.scala
Labels: backport:nominated

#23618 Emit an error for quoted pattern type variable after `new`
  compiler/src/dotty/tools/dotc/reporting/ErrorMessageID.scala
  compiler/src/dotty/tools/dotc/reporting/messages.scala
  compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala
  compiler/src/dotty/tools/dotc/typer/Typer.scala
  tests/neg-macros/i22616.check
  tests/neg-macros/i22616.scala
  tests/neg-macros/i22616b.check
  tests/neg-macros/i22616b.scala
  tests/run-macros/i22616c.check
  tests/run-macros/i22616c/Macro_4.scala
  tests/run-macros/i22616c/MyTypeRepr_3.scala
  tests/run-macros/i22616c/SealedTrait3_2.scala
  tests/run-macros/i22616c/Test_5.scala
  tests/run-macros/i22616c/caseName_1.scala
Labels: backport:nominated

#23630 Make SIP-62 `better-fors` a stable feature
  compiler/src/dotty/tools/dotc/config/SourceVersion.scala
  compiler/test/dotty/tools/debug/DebugTests.scala
  docs/_docs/reference/other-new-features/better-fors.md
  docs/_docs/reference/preview/overview.md
  docs/sidebar.yml
  presentation-compiler/test/dotty/tools/pc/tests/tokens/SemanticTokensSuite.scala
  tests/debug-preview/eval-in-for-comprehension.check
  tests/debug-preview/eval-in-for-comprehension.scala
  tests/debug/eval-in-for-comprehension.check
  tests/pos/better-fors-given.scala
  tests/pos/better-fors-i21804.scala
  tests/run/better-fors-map-elim.scala
  tests/run/better-fors.scala
  tests/run/fors.scala
  tests/semanticdb/expect/ForComprehension.expect.scala
  tests/semanticdb/metac.expect
Labels: release-notes, needs-minor-release
