Repository scala/scala3, pull requests merged in 2025-08, with the labels that each got.

#23634 Fix #23576
  compiler/src/dotty/tools/dotc/transform/patmat/Space.scala
Labels: backport:nominated

#23549 Add line number magic comment support
  compiler/src/dotty/tools/dotc/ast/Positioned.scala
  compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
  compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala
  compiler/src/dotty/tools/dotc/rewrites/Rewrites.scala
  compiler/src/dotty/tools/dotc/util/SourceFile.scala
  tests/neg/magic-offset-header-a.scala
  tests/neg/magic-offset-header-a_wrapper.check
  tests/neg/magic-offset-header-a_wrapper.scala
  tests/neg/magic-offset-header-b.scala
  tests/neg/magic-offset-header-b_wrapper.check
  tests/neg/magic-offset-header-b_wrapper.scala
  tests/neg/magic-offset-header-c.scala
  tests/neg/magic-offset-header-c_wrapper.check
  tests/neg/magic-offset-header-c_wrapper.scala
  tests/neg/magic-offset-header-d_wrapper.check
  tests/neg/magic-offset-header-d_wrapper.scala
Labels: backport:nominated

#23652 Add suppression if nowarn differs
  compiler/src/dotty/tools/dotc/Run.scala
  compiler/src/dotty/tools/dotc/reporting/WConf.scala
  tests/neg/nowarn.check
  tests/neg/nowarn.scala
  tests/warn/i23651.scala
  tests/warn/nowarn.check
  tests/warn/nowarn.scala
Labels: backport:nominated

#23628 Generalize "Don't approximate a type using Nothing as prefix"
  compiler/src/dotty/tools/dotc/core/Types.scala
  tests/pos/i23627.scala
Labels: backport:nominated

#23262 Make runtimeChecked a standard feature
  docs/_docs/reference/experimental/runtimeChecked.md
  docs/_docs/reference/other-new-features/runtimeChecked.md
  docs/sidebar.yml
  library/src/scala/annotation/internal/RuntimeChecked.scala
  library/src/scala/runtime/stdLibPatches/Predef.scala
  project/MiMaFilters.scala
  tests/run-tasty-inspector/stdlibExperimentalDefinitions.scala
Labels: needs-minor-release

#23379 Add an Ordering given instance for named tuples
  library/src/scala/NamedTuple.scala
  project/MiMaFilters.scala
  tests/run/named-tuple-ordering.check
  tests/run/named-tuple-ordering.scala
Labels: needs-minor-release

#23702 Bump Scala CLI to v1.8.5 (was v1.8.4)
  .github/workflows/lts-backport.yaml
  project/Build.scala
Labels: release-notes, backport:nominated
